var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return $jscomp.createTemplateTagFirstArgWithRaw(a,a)};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_ES6=!1;$jscomp.ASSUME_ES2020=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.INSTRUMENT_ASYNC_CONTEXT=!0;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};
$jscomp.global=$jscomp.ASSUME_ES2020?globalThis:$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE=typeof Symbol==="function"&&typeof Symbol("x")==="symbol";$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b,c){if(!c||a!=null){c=$jscomp.propertyToPolyfillSymbol[b];if(c==null)return a[b];c=a[c];return c!==void 0?c:a[b]}};
$jscomp.TYPED_ARRAY_CLASSES=function(){var a="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");$jscomp.global.BigInt64Array&&(a.push("BigInt64"),a.push("BigUint64"));return a}();$jscomp.polyfillTypedArrayMethod=function(a,b,c,d){if(b)for(var e=0;e<$jscomp.TYPED_ARRAY_CLASSES.length;e++){var f=$jscomp.TYPED_ARRAY_CLASSES[e]+"Array.prototype."+a;$jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,b,c,d):$jscomp.polyfillUnisolated(f,b,c,d)}};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=e.length===1;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&c==="es6"?d[e]:null;b=b(c);b!=null&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]===void 0&&(c=Math.random()*1E9>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.toObject=function(a){if(a==null)throw new TypeError("No nullish arg");return Object(a)};
$jscomp.assign=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.assign=="function"?Object.assign:function(a,b){a=$jscomp.toObject(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.setPrototypeOf=="function"?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;b!=void 0&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();c.jumpTo!=void 0&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;this.properties_.length>0;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(f,g){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});return a},"es6","es3");$jscomp.polyfill("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")},"es9","es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.makeAsyncIterator=function(a){var b=a[Symbol.asyncIterator];return b!==void 0?b.call(a):new $jscomp.AsyncIteratorFromSyncWrapper($jscomp.makeIterator(a))};
$jscomp.AsyncIteratorFromSyncWrapper=function(a){this[Symbol.asyncIterator]=function(){return this};this[Symbol.iterator]=function(){return a};this.next=function(b){return Promise.resolve(a.next(b))};this["throw"]=function(b){return new Promise(function(c,d){var e=a["throw"];e!==void 0?c(e.call(a,b)):(e=a["return"],e!==void 0&&e.call(a),d(new TypeError("no `throw` method")))})};a["return"]!==void 0&&(this["return"]=function(b){return Promise.resolve(a["return"](b))})};
$jscomp.AsyncGeneratorWrapper$ActionEnum={YIELD_VALUE:0,YIELD_STAR:1,AWAIT_VALUE:2};$jscomp.AsyncGeneratorWrapper$ActionRecord=function(a,b){this.action=a;this.value=b};$jscomp.AsyncGeneratorWrapper$GeneratorMethod={NEXT:"next",THROW:"throw",RETURN:"return"};$jscomp.AsyncGeneratorWrapper$ExecutionFrame_=function(a,b,c,d){this.method=a;this.param=b;this.resolve=c;this.reject=d};$jscomp.AsyncGeneratorWrapper$ExecutionNode_=function(a,b){this.frame=a;this.next=b};
$jscomp.AsyncGeneratorWrapper$ExecutionQueue_=function(){this.tail_=this.head_=null};$jscomp.AsyncGeneratorWrapper$ExecutionQueue_.prototype.isEmpty=function(){return this.head_===null};$jscomp.AsyncGeneratorWrapper$ExecutionQueue_.prototype.first=function(){if(this.head_)return this.head_.frame;throw Error("no frames in executionQueue");};$jscomp.AsyncGeneratorWrapper$ExecutionQueue_.prototype.drop=function(){this.head_&&(this.head_=this.head_.next,this.head_||(this.tail_=null))};
$jscomp.AsyncGeneratorWrapper$ExecutionQueue_.prototype.enqueue=function(a){a=new $jscomp.AsyncGeneratorWrapper$ExecutionNode_(a,null);this.tail_?this.tail_.next=a:this.head_=a;this.tail_=a};
$jscomp.AsyncGeneratorWrapper=function(a){this.generator_=a;this.delegate_=null;this.executionQueue_=new $jscomp.AsyncGeneratorWrapper$ExecutionQueue_;this[Symbol.asyncIterator]=function(){return this};var b=this;this.boundHandleDelegateResult_=function(c){b.handleDelegateResult_(c)};this.boundHandleDelegateError_=function(c){b.handleDelegateError_(c)};this.boundRejectAndClose_=function(c){b.rejectAndClose_(c)}};
$jscomp.AsyncGeneratorWrapper.prototype.enqueueMethod_=function(a,b){var c=this;return new Promise(function(d,e){var f=c.executionQueue_.isEmpty();c.executionQueue_.enqueue(new $jscomp.AsyncGeneratorWrapper$ExecutionFrame_(a,b,d,e));f&&c.runFrame_()})};$jscomp.AsyncGeneratorWrapper.prototype.next=function(a){return this.enqueueMethod_($jscomp.AsyncGeneratorWrapper$GeneratorMethod.NEXT,a)};
$jscomp.AsyncGeneratorWrapper.prototype["return"]=function(a){return this.enqueueMethod_($jscomp.AsyncGeneratorWrapper$GeneratorMethod.RETURN,new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,a))};$jscomp.AsyncGeneratorWrapper.prototype["throw"]=function(a){return this.enqueueMethod_($jscomp.AsyncGeneratorWrapper$GeneratorMethod.THROW,a)};
$jscomp.AsyncGeneratorWrapper.prototype.runFrame_=function(){if(!this.executionQueue_.isEmpty())try{this.delegate_?this.runDelegateFrame_():this.runGeneratorFrame_()}catch(a){this.rejectAndClose_(a)}};
$jscomp.AsyncGeneratorWrapper.prototype.runGeneratorFrame_=function(){var a=this,b=this.executionQueue_.first();try{var c=this.generator_[b.method](b.param);if(c.value instanceof $jscomp.AsyncGeneratorWrapper$ActionRecord)switch(c.value.action){case $jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE:Promise.resolve(c.value.value).then(function(d){b.resolve({value:d,done:c.done});a.executionQueue_.drop();a.runFrame_()},function(d){b.reject(d);a.executionQueue_.drop();a.runFrame_()})["catch"](this.boundRejectAndClose_);
break;case $jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR:a.delegate_=$jscomp.makeAsyncIterator(c.value.value);b.method=$jscomp.AsyncGeneratorWrapper$GeneratorMethod.NEXT;b.param=void 0;a.runFrame_();break;case $jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE:Promise.resolve(c.value.value).then(function(d){b.method=$jscomp.AsyncGeneratorWrapper$GeneratorMethod.NEXT;b.param=d;a.runFrame_()},function(d){b.method=$jscomp.AsyncGeneratorWrapper$GeneratorMethod.THROW;b.param=d;a.runFrame_()})["catch"](this.boundRejectAndClose_);
break;default:throw Error("Unrecognized AsyncGeneratorWrapper$ActionEnum");}else b.resolve(c),a.executionQueue_.drop(),a.runFrame_()}catch(d){b.reject(d),a.executionQueue_.drop(),a.runFrame_()}};
$jscomp.AsyncGeneratorWrapper.prototype.runDelegateFrame_=function(){if(!this.delegate_)throw Error("no delegate to perform execution");var a=this.executionQueue_.first();if(a.method in this.delegate_)try{this.delegate_[a.method](a.param).then(this.boundHandleDelegateResult_,this.boundHandleDelegateError_)["catch"](this.boundRejectAndClose_)}catch(b){this.handleDelegateError_(b)}else this.delegate_=null,this.runFrame_()};
$jscomp.AsyncGeneratorWrapper.prototype.handleDelegateResult_=function(a){var b=this.executionQueue_.first();a.done===!0?(this.delegate_=null,b.method=$jscomp.AsyncGeneratorWrapper$GeneratorMethod.NEXT,b.param=a.value):(b.resolve({value:a.value,done:!1}),this.executionQueue_.drop());this.runFrame_()};
$jscomp.AsyncGeneratorWrapper.prototype.handleDelegateError_=function(a){var b=this.executionQueue_.first();this.delegate_=null;b.method=$jscomp.AsyncGeneratorWrapper$GeneratorMethod.THROW;b.param=a;this.runFrame_()};
$jscomp.AsyncGeneratorWrapper.prototype.rejectAndClose_=function(a){this.executionQueue_.isEmpty()||(this.executionQueue_.first().reject(a),this.executionQueue_.drop());this.delegate_&&"return"in this.delegate_&&(this.delegate_["return"](void 0),this.delegate_=null);this.generator_["return"](void 0);this.runFrame_()};
var __defProp=Object.defineProperty,__getOwnPropDesc=Object.getOwnPropertyDescriptor,__getOwnPropNames=Object.getOwnPropertyNames,__hasOwnProp=Object.prototype.hasOwnProperty,__export=function(a,b){for(var c in b)__defProp(a,c,{get:b[c],enumerable:!0})},__copyProps=function(a,b,c,d){if(b&&typeof b==="object"||typeof b==="function")for(var e=(0,$jscomp.makeIterator)(__getOwnPropNames(b)),f=e.next(),g={};!f.done;g={key$jscomp$13:void 0},f=e.next())g.key$jscomp$13=f.value,__hasOwnProp.call(a,g.key$jscomp$13)||
g.key$jscomp$13===c||__defProp(a,g.key$jscomp$13,{get:function(h){return function(){return b[h.key$jscomp$13]}}(g),enumerable:!(d=__getOwnPropDesc(b,g.key$jscomp$13))||d.enumerable});return a},__toCommonJS=function(a){return __copyProps(__defProp({},"__esModule",{value:!0}),a)},index_exports={};
__export(index_exports,{DEFAULT_DELIMITER:function(){return DEFAULT_DELIMITER},DELIMITERS:function(){return DELIMITERS},decode:function(){return decode},decodeFromLines:function(){return decodeFromLines},decodeStream:function(){return decodeStream},decodeStreamSync:function(){return decodeStreamSync},encode:function(){return encode},encodeLines:function(){return encodeLines}});module.exports=__toCommonJS(index_exports);
var LIST_ITEM_MARKER="-",LIST_ITEM_PREFIX="- ",COMMA=",",COLON=":",SPACE=" ",PIPE="|",DOT=".",OPEN_BRACKET="[",CLOSE_BRACKET="]",OPEN_BRACE="{",CLOSE_BRACE="}",NULL_LITERAL="null",TRUE_LITERAL="true",FALSE_LITERAL="false",BACKSLASH="\\",DOUBLE_QUOTE='"',NEWLINE="\n",CARRIAGE_RETURN="\r",TAB="\t",DELIMITERS={comma:COMMA,tab:TAB,pipe:PIPE},DEFAULT_DELIMITER=DELIMITERS.comma;
function escapeString(a){return a.replace(/\\/g,""+BACKSLASH+BACKSLASH).replace(/"/g,""+BACKSLASH+DOUBLE_QUOTE).replace(/\n/g,BACKSLASH+"n").replace(/\r/g,BACKSLASH+"r").replace(/\t/g,BACKSLASH+"t")}
function unescapeString(a){for(var b="",c=0;c<a.length;){if(a[c]===BACKSLASH){if(c+1>=a.length)throw new SyntaxError("Invalid escape sequence: backslash at end of string");var d=a[c+1];if(d==="n"){b+=NEWLINE;c+=2;continue}if(d==="t"){b+=TAB;c+=2;continue}if(d==="r"){b+=CARRIAGE_RETURN;c+=2;continue}if(d===BACKSLASH){b+=BACKSLASH;c+=2;continue}if(d===DOUBLE_QUOTE){b+=DOUBLE_QUOTE;c+=2;continue}throw new SyntaxError("Invalid escape sequence: \\"+d);}b+=a[c];c++}return b}
function findClosingQuote(a,b){for(var c=b+1;c<a.length;)if(a[c]===BACKSLASH&&c+1<a.length)c+=2;else{if(a[c]===DOUBLE_QUOTE)return c;c++}return-1}function findUnquotedChar(a,b,c){var d=!1;for(c=c===void 0?0:c;c<a.length;)if(a[c]===BACKSLASH&&c+1<a.length&&d)c+=2;else{if(a[c]===DOUBLE_QUOTE)d=!d;else if(a[c]===b&&!d)return c;c++}return-1}function isBooleanOrNullLiteral(a){return a===TRUE_LITERAL||a===FALSE_LITERAL||a===NULL_LITERAL}
function isNumericLiteral(a){if(!a||a.length>1&&a[0]==="0"&&a[1]!==".")return!1;a=Number(a);return!Number.isNaN(a)&&Number.isFinite(a)}
function parseArrayHeaderLine(a,b){var c=a.trimStart(),d=-1;if(c.startsWith(DOUBLE_QUOTE)){var e=findClosingQuote(c,0);if(e===-1||!c.slice(e+1).startsWith(OPEN_BRACKET))return;d=a.indexOf(OPEN_BRACKET,a.length-c.length+e+1)}else d=a.indexOf(OPEN_BRACKET);if(d!==-1){var f=a.indexOf(CLOSE_BRACKET,d);if(f!==-1){e=f+1;c=a.indexOf(OPEN_BRACE,f);if(c!==-1&&c<a.indexOf(COLON,f)){var g=a.indexOf(CLOSE_BRACE,c);g!==-1&&(e=g+1)}e=a.indexOf(COLON,Math.max(f,e));if(e!==-1){if(d>0){var h=a.slice(0,d).trim();h=
h.startsWith(DOUBLE_QUOTE)?parseStringLiteral(h):h}g=a.slice(e+1).trim();d=a.slice(d+1,f);try{var m=parseBracketSegment(d,b)}catch(q){return}d=m;m=d.length;d=d.delimiter;var p;c!==-1&&c<e&&(f=a.indexOf(CLOSE_BRACE,c),f!==-1&&f<e&&(p=parseDelimitedValues(a.slice(c+1,f),d).map(function(q){return parseStringLiteral(q.trim())})));return{header:{key:h,length:m,delimiter:d,fields:p},inlineValues:g||void 0}}}}}
function parseBracketSegment(a,b){var c=a,d=b;c.endsWith(TAB)?(d=DELIMITERS.tab,c=c.slice(0,-1)):c.endsWith(PIPE)&&(d=DELIMITERS.pipe,c=c.slice(0,-1));c=Number.parseInt(c,10);if(Number.isNaN(c))throw new TypeError("Invalid array length: "+a);return{length:c,delimiter:d}}
function parseDelimitedValues(a,b){for(var c=[],d="",e=!1,f=0;f<a.length;){var g=a[f];g===BACKSLASH&&f+1<a.length&&e?(d+=g+a[f+1],f+=2):(g===DOUBLE_QUOTE?(e=!e,d+=g):g!==b||e?d+=g:(c.push(d.trim()),d=""),f++)}(d||c.length>0)&&c.push(d.trim());return c}function mapRowValuesToPrimitives(a){return a.map(function(b){return parsePrimitiveToken(b)})}
function parsePrimitiveToken(a){a=a.trim();if(!a)return"";if(a.startsWith(DOUBLE_QUOTE))return parseStringLiteral(a);if(isBooleanOrNullLiteral(a)){if(a===TRUE_LITERAL)return!0;if(a===FALSE_LITERAL)return!1;if(a===NULL_LITERAL)return null}return isNumericLiteral(a)?(a=Number.parseFloat(a),Object.is(a,-0)?0:a):a}
function parseStringLiteral(a){a=a.trim();if(a.startsWith(DOUBLE_QUOTE)){var b=findClosingQuote(a,0);if(b===-1)throw new SyntaxError("Unterminated string: missing closing quote");if(b!==a.length-1)throw new SyntaxError("Unexpected characters after closing quote");return unescapeString(a.slice(1,b))}return a}
function parseUnquotedKey(a,b){for(var c=b;c<a.length&&a[c]!==COLON;)c++;if(c>=a.length||a[c]!==COLON)throw new SyntaxError("Missing colon after key");var d=a.slice(b,c).trim();c++;return{key:d,end:c}}function parseQuotedKey(a,b){var c=findClosingQuote(a,b);if(c===-1)throw new SyntaxError("Unterminated quoted key");var d=unescapeString(a.slice(b+1,c));c+=1;if(c>=a.length||a[c]!==COLON)throw new SyntaxError("Missing colon after key");c++;return{key:d,end:c}}
function parseKeyToken(a,b){var c=a[b]===DOUBLE_QUOTE;return Object.assign({},c?parseQuotedKey(a,b):parseUnquotedKey(a,b),{isQuoted:c})}function isArrayHeaderContent(a){return a.trim().startsWith(OPEN_BRACKET)&&findUnquotedChar(a,COLON)!==-1}function isKeyValueContent(a){return findUnquotedChar(a,COLON)!==-1}function createScanState(){return{lineNumber:0,blankLines:[]}}
function parseLineIncremental(a,b,c,d){b.lineNumber++;for(var e=b.lineNumber,f=0;f<a.length&&a[f]===SPACE;)f++;var g=a.slice(f);if(g.trim()){b=computeDepthFromIndent(f,c);if(d){for(d=0;d<a.length&&(a[d]===SPACE||a[d]===TAB);)d++;if(a.slice(0,d).includes(TAB))throw new SyntaxError("Line "+e+": Tabs are not allowed in indentation in strict mode");if(f>0&&f%c!==0)throw new SyntaxError("Line "+e+": Indentation must be exact multiple of "+c+", but found "+f+" spaces");}return{raw:a,indent:f,content:g,
depth:b,lineNumber:e}}a=computeDepthFromIndent(f,c);b.blankLines.push({lineNumber:e,indent:f,depth:a})}function parseLinesSync(a,b,c,d){var e,f,g,h;return $jscomp.generator.createGenerator(parseLinesSync,function(m){m.nextAddress==1&&(e=(0,$jscomp.makeIterator)(a),f=e.next());if(m.nextAddress!=3){if(f.done)return m.jumpTo(0);g=f.value;h=parseLineIncremental(g,d,b,c);return h===void 0?m.jumpTo(3):m.yield(h,3)}f=e.next();return m.jumpTo(2)})}
function parseLinesAsync(a,b,c,d){return new $jscomp.AsyncGeneratorWrapper(function f(){var g,h,m,p,q,n,u;return $jscomp.generator.createGenerator(f,function(k){switch(k.nextAddress){case 1:k.setCatchFinallyBlocks(2,3),p=(0,$jscomp.makeAsyncIterator)(a);case 5:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,p.next()),8);case 8:h=k.yieldResult;if(h.done){k.jumpTo(3);break}q=h.value;n=parseLineIncremental(q,d,b,c);if(n===void 0){k.jumpTo(5);
break}return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,n),5);case 3:k.enterFinallyBlock();k.setFinallyBlock(11);if(!h||h.done||!(m=p["return"])){k.jumpTo(11);break}return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,m.call(p)),11);case 11:k.enterFinallyBlock(0,0,1);if(g)throw g.error;k.leaveFinallyBlock(12,1);break;case 12:k.leaveFinallyBlock(0);break;case 2:u=k.enterCatchBlock(),
g={error:u},k.jumpTo(3)}})}())}function computeDepthFromIndent(a,b){return Math.floor(a/b)}function assertExpectedCount(a,b,c,d){if(d.strict&&a!==b)throw new RangeError("Expected "+b+" "+c+", but got "+a);}function validateNoExtraListItems(a,b,c){if((a==null?void 0:a.depth)===b&&a.content.startsWith(LIST_ITEM_PREFIX))throw new RangeError("Expected "+c+" list array items, but found more");}
function validateNoExtraTabularRows(a,b,c){if((a==null?void 0:a.depth)===b&&!a.content.startsWith(LIST_ITEM_PREFIX)&&isDataRow(a.content,c.delimiter))throw new RangeError("Expected "+c.length+" tabular rows, but found more");}function validateNoBlankLinesInRange(a,b,c,d,e){if(d&&(c=c.find(function(f){return f.lineNumber>a&&f.lineNumber<b})))throw new SyntaxError("Line "+c.lineNumber+": Blank lines inside "+e+" are not allowed in strict mode");}
function isDataRow(a,b){var c=a.indexOf(COLON),d=a.indexOf(b);return c===-1||d!==-1&&d<c?!0:!1}var StreamingLineCursor=function(a,b){this.buffer=[];this.generator=void 0;this.done=!1;this.scanState=this.lastLine=void 0;this.generator=a;this.scanState=b};StreamingLineCursor.prototype.getBlankLines=function(){return this.scanState.blankLines};
StreamingLineCursor.prototype.peek=function(){var a=this,b;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(c){if(c.nextAddress==1)return a.buffer.length>0?c["return"](a.buffer[0]):a.done?c["return"]():c.yield(a.generator.next(),2);b=c.yieldResult;if(b.done)return a.done=!0,c["return"]();a.buffer.push(b.value);return c["return"](b.value)})};
StreamingLineCursor.prototype.next=function(){var a=this,b;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(c){if(c.nextAddress==1)return c.yield(a.peek(),2);b=c.yieldResult;b!==void 0&&(a.buffer.shift(),a.lastLine=b);return c["return"](b)})};StreamingLineCursor.prototype.advance=function(){var a=this;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(b){return b.yield(a.next(),0)})};StreamingLineCursor.prototype.current=function(){return this.lastLine};
StreamingLineCursor.prototype.atEnd=function(){var a=this;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(b){return b.nextAddress==1?b.yield(a.peek(),2):b["return"](b.yieldResult===void 0)})};StreamingLineCursor.prototype.peekSync=function(){if(this.buffer.length>0)return this.buffer[0];if(!this.done){var a=this.generator.next();if(a.done)this.done=!0;else return this.buffer.push(a.value),a.value}};
StreamingLineCursor.prototype.nextSync=function(){var a=this.peekSync();a!==void 0&&(this.buffer.shift(),this.lastLine=a);return a};StreamingLineCursor.prototype.advanceSync=function(){this.nextSync()};StreamingLineCursor.prototype.atEndSync=function(){return this.peekSync()===void 0};
function decodeStreamSync$1(a,b){var c,d,e,f,g,h,m,p,q,n,u;return $jscomp.generator.createGenerator(decodeStreamSync$1,function(k){switch(k.nextAddress){case 1:if(((c=b)==null?void 0:c.expandPaths)!==void 0)throw Error("expandPaths is not supported in streaming decode");h={indent:(f=(d=b)==null?void 0:d.indent)!=null?f:2,strict:(g=(e=b)==null?void 0:e.strict)!=null?g:!0};m=createScanState();p=new StreamingLineCursor(parseLinesSync(a,h.indent,h.strict,m),m);if(q=p.peekSync()){k.jumpTo(2);break}return k.yield({type:"startObject"},
3);case 3:return k.yield({type:"endObject"},4);case 4:return k["return"]();case 2:if(!isArrayHeaderContent(q.content)){k.jumpTo(5);break}n=parseArrayHeaderLine(q.content,DEFAULT_DELIMITER);if(!n){k.jumpTo(5);break}p.advanceSync();return k.yieldAll(decodeArrayFromHeaderSync(n.header,n.inlineValues,p,0,h),7);case 7:return k["return"]();case 5:p.advanceSync();if(!p.atEndSync()||isKeyValueLineSync(q)){k.jumpTo(8);break}return k.yield({type:"primitive",value:parsePrimitiveToken(q.content.trim())},9);case 9:return k["return"]();
case 8:return k.yield({type:"startObject"},10);case 10:return k.yieldAll(decodeKeyValueSync(q.content,p,0,h),12);case 12:if(p.atEndSync()){k.jumpTo(14);break}u=p.peekSync();if(!u||u.depth!==0){k.jumpTo(14);break}p.advanceSync();return k.yieldAll(decodeKeyValueSync(u.content,p,0,h),12);case 14:return k.yield({type:"endObject"},0)}})}
function decodeKeyValueSync(a,b,c,d){var e,f,g,h,m,p,q;return $jscomp.generator.createGenerator(decodeKeyValueSync,function(n){switch(n.nextAddress){case 1:e=parseArrayHeaderLine(a,DEFAULT_DELIMITER);if(!e||!e.header.key){n.jumpTo(2);break}return n.yield({type:"key",key:e.header.key},3);case 3:return n.yieldAll(decodeArrayFromHeaderSync(e.header,e.inlineValues,b,c,d),4);case 4:return n["return"]();case 2:return f=parseKeyToken(a,0),g=f.key,h=f.isQuoted,m=a.indexOf(COLON,g.length),p=m>=0?a.slice(m+
1).trim():"",n.yield(h?{type:"key",key:g,wasQuoted:!0}:{type:"key",key:g},5);case 5:if(p){n.jumpTo(6);break}q=b.peekSync();if(!(q&&q.depth>c)){n.jumpTo(7);break}return n.yield({type:"startObject"},8);case 8:return n.yieldAll(decodeObjectFieldsSync(b,c+1,d),9);case 9:return n.yield({type:"endObject"},10);case 10:return n["return"]();case 7:return n.yield({type:"startObject"},11);case 11:return n.yield({type:"endObject"},12);case 12:return n["return"]();case 6:return n.yield({type:"primitive",value:parsePrimitiveToken(p)},
0)}})}function decodeObjectFieldsSync(a,b,c){var d,e;return $jscomp.generator.createGenerator(decodeObjectFieldsSync,function(f){if(a.atEndSync())return f.jumpTo(0);e=a.peekSync();if(!e||e.depth<b)return f.jumpTo(0);d===void 0&&e.depth>=b&&(d=e.depth);if(e.depth!==d)return f.jumpTo(0);a.advanceSync();return f.yieldAll(decodeKeyValueSync(e.content,a,d,c),1)})}
function decodeArrayFromHeaderSync(a,b,c,d,e){return $jscomp.generator.createGenerator(decodeArrayFromHeaderSync,function(f){switch(f.nextAddress){case 1:return f.yield({type:"startArray",length:a.length},2);case 2:if(!b){f.jumpTo(3);break}return f.yieldAll(decodeInlinePrimitiveArraySync(a,b,e),4);case 4:return f.yield({type:"endArray"},5);case 5:return f["return"]();case 3:if(!(a.fields&&a.fields.length>0)){f.jumpTo(6);break}return f.yieldAll(decodeTabularArraySync(a,c,d,e),7);case 7:return f.yield({type:"endArray"},
8);case 8:return f["return"]();case 6:return f.yieldAll(decodeListArraySync(a,c,d,e),9);case 9:return f.yield({type:"endArray"},0)}})}
function decodeInlinePrimitiveArraySync(a,b,c){var d,e,f,g;return $jscomp.generator.createGenerator(decodeInlinePrimitiveArraySync,function(h){if(h.nextAddress==1){if(!b.trim())return assertExpectedCount(0,a.length,"inline array items",c),h["return"]();d=mapRowValuesToPrimitives(parseDelimitedValues(b,a.delimiter));assertExpectedCount(d.length,a.length,"inline array items",c);e=(0,$jscomp.makeIterator)(d);f=e.next()}if(h.nextAddress!=3){if(f.done)return h.jumpTo(0);g=f.value;return h.yield({type:"primitive",
value:g},3)}f=e.next();return h.jumpTo(2)})}
function decodeTabularArraySync(a,b,c,d){var e,f,g,h,m,p,q;return $jscomp.generator.createGenerator(decodeTabularArraySync,function(n){switch(n.nextAddress){case 1:e=c+1,f=0;case 2:if(b.atEndSync()||!(f<a.length)){n.jumpTo(4);break}m=b.peekSync();if(!m||m.depth<e){n.jumpTo(4);break}if(m.depth!==e){n.jumpTo(4);break}g===void 0&&(g=m.lineNumber);h=m.lineNumber;b.advanceSync();p=parseDelimitedValues(m.content,a.delimiter);assertExpectedCount(p.length,a.fields.length,"tabular row values",d);q=mapRowValuesToPrimitives(p);
return n.yieldAll(yieldObjectFromFields(a.fields,q),6);case 6:f++;n.jumpTo(2);break;case 4:assertExpectedCount(f,a.length,"tabular rows",d),d.strict&&g!==void 0&&h!==void 0&&validateNoBlankLinesInRange(g,h,b.getBlankLines(),d.strict,"tabular array"),d.strict&&validateNoExtraTabularRows(b.peekSync(),e,a),n.jumpToEnd()}})}
function decodeListArraySync(a,b,c,d){var e,f,g,h,m,p,q;return $jscomp.generator.createGenerator(decodeListArraySync,function(n){switch(n.nextAddress){case 1:e=c+1,f=0;case 2:if(b.atEndSync()||!(f<a.length)){n.jumpTo(4);break}m=b.peekSync();if(!m||m.depth<e){n.jumpTo(4);break}p=m.content.startsWith(LIST_ITEM_PREFIX)||m.content===LIST_ITEM_MARKER;if(m.depth!==e||!p){n.jumpTo(4);break}g===void 0&&(g=m.lineNumber);h=m.lineNumber;return n.yieldAll(decodeListItemSync(b,e,d),6);case 6:if(q=b.current())h=
q.lineNumber;f++;n.jumpTo(2);break;case 4:assertExpectedCount(f,a.length,"list array items",d),d.strict&&g!==void 0&&h!==void 0&&validateNoBlankLinesInRange(g,h,b.getBlankLines(),d.strict,"list array"),d.strict&&validateNoExtraListItems(b.peekSync(),e,a.length),n.jumpToEnd()}})}
function decodeListItemSync(a,b,c){var d,e,f,g,h,m,p,q,n,u,k,t;return $jscomp.generator.createGenerator(decodeListItemSync,function(l){switch(l.nextAddress){case 1:d=a.nextSync();if(!d)throw new ReferenceError("Expected list item");if(d.content!==LIST_ITEM_MARKER){if(d.content.startsWith(LIST_ITEM_PREFIX))e=d.content.slice(LIST_ITEM_PREFIX.length);else throw new SyntaxError('Expected list item to start with "'+LIST_ITEM_PREFIX+'"');l.jumpTo(2);break}f=b+1;if((g=a.peekSync())&&!(g.depth<f)){l.jumpTo(3);
break}return l.yield({type:"startObject"},4);case 4:return l.yield({type:"endObject"},5);case 5:return l["return"]();case 3:return g.depth!==f||g.content.startsWith(LIST_ITEM_PREFIX)?l.yield({type:"startObject"},8):l.yield({type:"startObject"},11);case 8:return l.yield({type:"endObject"},9);case 9:return l["return"]();case 11:if(a.atEndSync()){l.jumpTo(13);break}h=a.peekSync();if(!h||h.depth<f){l.jumpTo(13);break}if(h.depth!==f||h.content.startsWith(LIST_ITEM_PREFIX)){l.jumpTo(13);break}a.advanceSync();
return l.yieldAll(decodeKeyValueSync(h.content,a,f,c),11);case 13:return l.yield({type:"endObject"},16);case 16:return l["return"]();case 2:if(e.trim()){l.jumpTo(17);break}return l.yield({type:"startObject"},18);case 18:return l.yield({type:"endObject"},19);case 19:return l["return"]();case 17:if(!isArrayHeaderContent(e)){l.jumpTo(20);break}m=parseArrayHeaderLine(e,DEFAULT_DELIMITER);if(!m){l.jumpTo(20);break}return l.yieldAll(decodeArrayFromHeaderSync(m.header,m.inlineValues,a,b,c),22);case 22:return l["return"]();
case 20:p=parseArrayHeaderLine(e,DEFAULT_DELIMITER);if(!(p&&p.header.key&&p.header.fields)){l.jumpTo(23);break}q=p.header;return l.yield({type:"startObject"},24);case 24:return l.yield({type:"key",key:q.key},25);case 25:return l.yieldAll(decodeArrayFromHeaderSync(q,p.inlineValues,a,b+1,c),26);case 26:n=b+1;case 27:if(a.atEndSync()){l.jumpTo(29);break}u=a.peekSync();if(!u||u.depth<n){l.jumpTo(29);break}if(u.depth!==n||u.content.startsWith(LIST_ITEM_PREFIX)){l.jumpTo(29);break}a.advanceSync();return l.yieldAll(decodeKeyValueSync(u.content,
a,n,c),27);case 29:return l.yield({type:"endObject"},32);case 32:return l["return"]();case 23:if(!isKeyValueContent(e)){l.jumpTo(33);break}return l.yield({type:"startObject"},34);case 34:return l.yieldAll(decodeKeyValueSync(e,a,b+1,c),35);case 35:k=b+1;case 36:if(a.atEndSync()){l.jumpTo(38);break}t=a.peekSync();if(!t||t.depth<k){l.jumpTo(38);break}if(t.depth!==k||t.content.startsWith(LIST_ITEM_PREFIX)){l.jumpTo(38);break}a.advanceSync();return l.yieldAll(decodeKeyValueSync(t.content,a,k,c),36);case 38:return l.yield({type:"endObject"},
41);case 41:return l["return"]();case 33:return l.yield({type:"primitive",value:parsePrimitiveToken(e)},0)}})}function isKeyValueLineSync(a){a=a.content;if(a.startsWith('"')){var b=findClosingQuote(a,0);return b===-1?!1:a.slice(b+1).includes(COLON)}return a.includes(COLON)}
function decodeStream$1(a,b){return new $jscomp.AsyncGeneratorWrapper(function d(){var e,f,g,h,m,p,q,n,u,k,t;return $jscomp.generator.createGenerator(d,function(l){switch(l.nextAddress){case 1:if(((e=b)==null?void 0:e.expandPaths)!==void 0)throw Error("expandPaths is not supported in streaming decode");p={indent:(h=(f=b)==null?void 0:f.indent)!=null?h:2,strict:(m=(g=b)==null?void 0:g.strict)!=null?m:!0};q=createScanState();return Symbol.asyncIterator in a?(n=new StreamingLineCursor(parseLinesAsync(a,
p.indent,p.strict,q),q),l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.peek()),5)):l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeStreamSync$1(a,b)),0);case 5:if(u=l.yieldResult){l.jumpTo(6);break}return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),7);case 7:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endObject"}),8);case 8:return l["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 6:if(!isArrayHeaderContent(u.content)){l.jumpTo(9);break}k=parseArrayHeaderLine(u.content,DEFAULT_DELIMITER);if(!k){l.jumpTo(9);break}return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.advance()),11);case 11:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,
decodeArrayFromHeaderAsync(k.header,k.inlineValues,n,0,p)),12);case 12:return l["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 9:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.advance()),13);case 13:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.atEnd()),14);case 14:if(!l.yieldResult||
isKeyValueLineSync(u)){l.jumpTo(15);break}return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"primitive",value:parsePrimitiveToken(u.content.trim())}),16);case 16:return l["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 15:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),
17);case 17:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(u.content,n,0,p)),19);case 19:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.atEnd()),22);case 22:if(l.yieldResult){l.jumpTo(21);break}return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.peek()),23);case 23:t=l.yieldResult;
if(!t||t.depth!==0){l.jumpTo(21);break}return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,n.advance()),24);case 24:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(t.content,n,0,p)),19);case 21:return l.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endObject"}),0)}})}())}
function decodeKeyValueAsync(a,b,c,d){return new $jscomp.AsyncGeneratorWrapper(function f(){var g,h,m,p,q,n,u;return $jscomp.generator.createGenerator(f,function(k){switch(k.nextAddress){case 1:g=parseArrayHeaderLine(a,DEFAULT_DELIMITER);if(!g||!g.header.key){k.jumpTo(2);break}return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"key",key:g.header.key}),3);case 3:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,
decodeArrayFromHeaderAsync(g.header,g.inlineValues,b,c,d)),4);case 4:return k["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 2:return h=parseKeyToken(a,0),m=h.key,p=h.isQuoted,q=a.indexOf(COLON,m.length),n=q>=0?a.slice(q+1).trim():"",k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,p?{type:"key",key:m,wasQuoted:!0}:{type:"key",key:m}),5);case 5:if(n){k.jumpTo(6);
break}return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.peek()),7);case 7:u=k.yieldResult;if(!(u&&u.depth>c)){k.jumpTo(8);break}return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),9);case 9:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeObjectFieldsAsync(b,c+1,d)),10);case 10:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endObject"}),11);case 11:return k["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 8:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),12);case 12:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endObject"}),13);case 13:return k["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
void 0));case 6:return k.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"primitive",value:parsePrimitiveToken(n)}),0)}})}())}
function decodeObjectFieldsAsync(a,b,c){return new $jscomp.AsyncGeneratorWrapper(function e(){var f,g;return $jscomp.generator.createGenerator(e,function(h){switch(h.nextAddress){case 1:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.atEnd()),5);case 5:if(h.yieldResult){h.jumpTo(0);break}return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.peek()),6);case 6:g=h.yieldResult;
if(!g||g.depth<b){h.jumpTo(0);break}f===void 0&&g.depth>=b&&(f=g.depth);if(g.depth!==f){h.jumpTo(0);break}return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.advance()),8);case 8:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(g.content,a,f,c)),1)}})}())}
function decodeArrayFromHeaderAsync(a,b,c,d,e){return new $jscomp.AsyncGeneratorWrapper(function g(){return $jscomp.generator.createGenerator(g,function(h){switch(h.nextAddress){case 1:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startArray",length:a.length}),2);case 2:if(!b){h.jumpTo(3);break}return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeInlinePrimitiveArraySync(a,
b,e)),4);case 4:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endArray"}),5);case 5:return h["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 3:if(!(a.fields&&a.fields.length>0)){h.jumpTo(6);break}return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeTabularArrayAsync(a,c,d,e)),7);case 7:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endArray"}),8);case 8:return h["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 6:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeListArrayAsync(a,c,d,e)),9);case 9:return h.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endArray"}),0)}})}())}
function decodeTabularArrayAsync(a,b,c,d){return new $jscomp.AsyncGeneratorWrapper(function f(){var g,h,m,p,q,n,u,k;return $jscomp.generator.createGenerator(f,function(t){switch(t.nextAddress){case 1:g=c+1,h=0;case 2:return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.atEnd()),5);case 5:if(t.yieldResult||!(h<a.length)){t.jumpTo(4);break}return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,
b.peek()),6);case 6:q=t.yieldResult;if(!q||q.depth<g){t.jumpTo(4);break}if(q.depth!==g){t.jumpTo(4);break}m===void 0&&(m=q.lineNumber);p=q.lineNumber;return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.advance()),8);case 8:return n=parseDelimitedValues(q.content,a.delimiter),assertExpectedCount(n.length,a.fields.length,"tabular row values",d),u=mapRowValuesToPrimitives(n),t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,
yieldObjectFromFields(a.fields,u)),9);case 9:h++;t.jumpTo(2);break;case 4:assertExpectedCount(h,a.length,"tabular rows",d);d.strict&&m!==void 0&&p!==void 0&&validateNoBlankLinesInRange(m,p,b.getBlankLines(),d.strict,"tabular array");if(!d.strict){t.jumpTo(0);break}k=validateNoExtraTabularRows;return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.peek()),11);case 11:k(t.yieldResult,g,a),t.jumpToEnd()}})}())}
function decodeListArrayAsync(a,b,c,d){return new $jscomp.AsyncGeneratorWrapper(function f(){var g,h,m,p,q,n,u,k;return $jscomp.generator.createGenerator(f,function(t){switch(t.nextAddress){case 1:g=c+1,h=0;case 2:return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.atEnd()),5);case 5:if(t.yieldResult||!(h<a.length)){t.jumpTo(4);break}return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,
b.peek()),6);case 6:q=t.yieldResult;if(!q||q.depth<g){t.jumpTo(4);break}n=q.content.startsWith(LIST_ITEM_PREFIX)||q.content===LIST_ITEM_MARKER;if(q.depth!==g||!n){t.jumpTo(4);break}m===void 0&&(m=q.lineNumber);p=q.lineNumber;return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeListItemAsync(b,g,d)),8);case 8:if(u=b.current())p=u.lineNumber;h++;t.jumpTo(2);break;case 4:assertExpectedCount(h,a.length,"list array items",d);d.strict&&
m!==void 0&&p!==void 0&&validateNoBlankLinesInRange(m,p,b.getBlankLines(),d.strict,"list array");if(!d.strict){t.jumpTo(0);break}k=validateNoExtraListItems;return t.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,b.peek()),10);case 10:k(t.yieldResult,g,a.length),t.jumpToEnd()}})}())}
function decodeListItemAsync(a,b,c){return new $jscomp.AsyncGeneratorWrapper(function e(){var f,g,h,m,p,q,n,u,k,t,l,w;return $jscomp.generator.createGenerator(e,function(r){switch(r.nextAddress){case 1:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.next()),2);case 2:f=r.yieldResult;if(!f)throw new ReferenceError("Expected list item");if(f.content!==LIST_ITEM_MARKER){if(f.content.startsWith(LIST_ITEM_PREFIX))g=f.content.slice(LIST_ITEM_PREFIX.length);
else throw new SyntaxError('Expected list item to start with "'+LIST_ITEM_PREFIX+'"');r.jumpTo(3);break}h=b+1;return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.peek()),4);case 4:if((m=r.yieldResult)&&!(m.depth<h)){r.jumpTo(5);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),6);case 6:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endObject"}),7);case 7:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 5:return m.depth!==h||m.content.startsWith(LIST_ITEM_PREFIX)?r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),10):r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),13);case 10:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endObject"}),11);case 11:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 13:if(a.atEnd()){r.jumpTo(15);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.peek()),16);case 16:p=r.yieldResult;if(!p||p.depth<h){r.jumpTo(15);break}if(p.depth!==h||p.content.startsWith(LIST_ITEM_PREFIX)){r.jumpTo(15);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,
a.advance()),18);case 18:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(p.content,a,h,c)),13);case 15:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endObject"}),20);case 20:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 3:if(g.trim()){r.jumpTo(21);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"startObject"}),22);case 22:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endObject"}),23);case 23:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 21:if(!isArrayHeaderContent(g)){r.jumpTo(24);break}q=parseArrayHeaderLine(g,DEFAULT_DELIMITER);if(!q){r.jumpTo(24);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,
decodeArrayFromHeaderAsync(q.header,q.inlineValues,a,b,c)),26);case 26:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 24:n=parseArrayHeaderLine(g,DEFAULT_DELIMITER);if(!(n&&n.header.key&&n.header.fields)){r.jumpTo(27);break}u=n.header;return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),28);case 28:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"key",key:u.key}),29);case 29:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeArrayFromHeaderAsync(u,n.inlineValues,a,b+1,c)),30);case 30:k=b+1;case 31:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.atEnd()),34);case 34:if(r.yieldResult){r.jumpTo(33);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,
a.peek()),35);case 35:t=r.yieldResult;if(!t||t.depth<k){r.jumpTo(33);break}if(t.depth!==k||t.content.startsWith(LIST_ITEM_PREFIX)){r.jumpTo(33);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.advance()),37);case 37:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(t.content,a,k,c)),31);case 33:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"endObject"}),39);case 39:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 27:if(!isKeyValueContent(g)){r.jumpTo(40);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"startObject"}),41);case 41:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(g,a,b+
1,c)),42);case 42:l=b+1;case 43:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.atEnd()),46);case 46:if(r.yieldResult){r.jumpTo(45);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,a.peek()),47);case 47:w=r.yieldResult;if(!w||w.depth<l){r.jumpTo(45);break}if(w.depth!==l||w.content.startsWith(LIST_ITEM_PREFIX)){r.jumpTo(45);break}return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.AWAIT_VALUE,
a.advance()),49);case 49:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_STAR,decodeKeyValueAsync(w.content,a,l,c)),43);case 45:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,{type:"endObject"}),51);case 51:return r["return"](new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,void 0));case 40:return r.yield(new $jscomp.AsyncGeneratorWrapper$ActionRecord($jscomp.AsyncGeneratorWrapper$ActionEnum.YIELD_VALUE,
{type:"primitive",value:parsePrimitiveToken(g)}),0)}})}())}function yieldObjectFromFields(a,b){var c;return $jscomp.generator.createGenerator(yieldObjectFromFields,function(d){switch(d.nextAddress){case 1:return d.yield({type:"startObject"},2);case 2:c=0;case 3:return c<a.length?d.yield({type:"key",key:a[c]},6):d.yield({type:"endObject"},0);case 6:return d.yield({type:"primitive",value:b[c]},4);case 4:c++,d.jumpTo(3)}})}
function normalizeValue(a){if(a===null)return null;if(typeof a==="object"&&a!==null&&"toJSON"in a&&typeof a.toJSON==="function"){var b=a.toJSON();if(b!==a)return normalizeValue(b)}if(typeof a==="string"||typeof a==="boolean")return a;if(typeof a==="number")return Object.is(a,-0)?0:Number.isFinite(a)?a:null;if(typeof a==="bigint")return a>=Number.MIN_SAFE_INTEGER&&a<=Number.MAX_SAFE_INTEGER?Number(a):a.toString();if(a instanceof Date)return a.toISOString();if(Array.isArray(a))return a.map(normalizeValue);
if(a instanceof Set)return Array.from(a).map(normalizeValue);if(a instanceof Map)return Object.fromEntries(Array.from(a,function(d){var e=(0,$jscomp.makeIterator)(d);d=e.next().value;e=e.next().value;return[String(d),normalizeValue(e)]}));if(isPlainObject(a)){b={};for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=normalizeValue(a[c]));return b}return null}function isJsonPrimitive(a){return a===null||typeof a==="string"||typeof a==="number"||typeof a==="boolean"}
function isJsonArray(a){return Array.isArray(a)}function isJsonObject(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)}function isEmptyObject(a){return Object.keys(a).length===0}function isPlainObject(a){if(a===null||typeof a!=="object")return!1;a=Object.getPrototypeOf(a);return a===null||a===Object.prototype}function isArrayOfPrimitives(a){return a.length===0||a.every(function(b){return isJsonPrimitive(b)})}
function isArrayOfArrays(a){return a.length===0||a.every(function(b){return isJsonArray(b)})}function isArrayOfObjects(a){return a.length===0||a.every(function(b){return isJsonObject(b)})}function isValidUnquotedKey(a){return/^[A-Z_][\w.]*$/i.test(a)}function isIdentifierSegment(a){return/^[A-Z_]\w*$/i.test(a)}
function isSafeUnquoted(a,b){b=b===void 0?DEFAULT_DELIMITER:b;return!a||a!==a.trim()||isBooleanOrNullLiteral(a)||isNumericLike(a)||a.includes(":")||a.includes('"')||a.includes("\\")||/[[\]{}]/.test(a)||/[\n\r\t]/.test(a)||a.includes(b)||a.startsWith(LIST_ITEM_MARKER)?!1:!0}function isNumericLike(a){return/^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i.test(a)||/^0\d+$/.test(a)}var QUOTED_KEY_MARKER=Symbol("quotedKey");
function expandPathsSafe(a,b){if(Array.isArray(a))return a.map(function(p){return expandPathsSafe(p,b)});if(isJsonObject(a)){for(var c={},d=a[QUOTED_KEY_MARKER],e=(0,$jscomp.makeIterator)(Object.entries(a)),f=e.next();!f.done;f=e.next()){var g=(0,$jscomp.makeIterator)(f.value);f=g.next().value;g=g.next().value;var h=void 0,m=(h=d)==null?void 0:h.has(f);if(f.includes(DOT)&&!m&&(h=f.split(DOT),h.every(function(p){return isIdentifierSegment(p)}))){insertPathSafe(c,h,expandPathsSafe(g,b),b);continue}g=
expandPathsSafe(g,b);if(f in c)if(h=c[f],canMerge(h,g))mergeObjects(h,g,b);else{if(b)throw new TypeError('Path expansion conflict at key "'+f+'": cannot merge '+typeof h+" with "+typeof g);c[f]=g}else c[f]=g}return c}return a}
function insertPathSafe(a,b,c,d){for(var e=0;e<b.length-1;e++){var f=b[e],g=a[f];if(g===void 0)g={},a=a[f]=g;else if(isJsonObject(g))a=g;else{if(d)throw new TypeError('Path expansion conflict at segment "'+f+'": expected object but found '+typeof g);g={};a=a[f]=g}}b=b[b.length-1];e=a[b];if(e===void 0)a[b]=c;else if(canMerge(e,c))mergeObjects(e,c,d);else{if(d)throw new TypeError('Path expansion conflict at key "'+b+'": cannot merge '+typeof e+" with "+typeof c);a[b]=c}}
function mergeObjects(a,b,c){b=(0,$jscomp.makeIterator)(Object.entries(b));for(var d=b.next();!d.done;d=b.next()){var e=(0,$jscomp.makeIterator)(d.value);d=e.next().value;e=e.next().value;var f=a[d];if(f===void 0)a[d]=e;else if(canMerge(f,e))mergeObjects(f,e,c);else{if(c)throw new TypeError('Path expansion conflict at key "'+d+'": cannot merge '+typeof f+" with "+typeof e);a[d]=e}}}function canMerge(a,b){return isJsonObject(a)&&isJsonObject(b)}
function buildValueFromEvents(a){var b={stack:[],root:void 0};a=(0,$jscomp.makeIterator)(a);for(var c=a.next();!c.done;c=a.next())applyEvent(b,c.value);return finalizeState(b)}
function applyEvent(a,b){var c=a.stack;switch(b.type){case "startObject":var d={},e=new Set;if(c.length!==0){var f=c[c.length-1];if(f.type==="object"){if(f.currentKey===void 0)throw Error("Object startObject event without preceding key");f.obj[f.currentKey]=d;f.currentKey=void 0}else f.type==="array"&&f.arr.push(d)}c.push({type:"object",obj:d,quotedKeys:e});break;case "endObject":if(c.length===0)throw Error("Unexpected endObject event");d=c.pop();if(d.type!=="object")throw Error("Mismatched endObject event");
d.quotedKeys.size>0&&Object.defineProperty(d.obj,QUOTED_KEY_MARKER,{value:d.quotedKeys,enumerable:!1,writable:!1,configurable:!1});c.length===0&&(a.root=d.obj);break;case "startArray":d=[];if(c.length!==0)if(e=c[c.length-1],e.type==="object"){if(e.currentKey===void 0)throw Error("Array startArray event without preceding key");e.obj[e.currentKey]=d;e.currentKey=void 0}else e.type==="array"&&e.arr.push(d);c.push({type:"array",arr:d});break;case "endArray":if(c.length===0)throw Error("Unexpected endArray event");
d=c.pop();if(d.type!=="array")throw Error("Mismatched endArray event");c.length===0&&(a.root=d.arr);break;case "key":if(c.length===0)throw Error("Key event outside of object context");c=c[c.length-1];if(c.type!=="object")throw Error("Key event in non-object context");c.currentKey=b.key;b.wasQuoted&&c.quotedKeys.add(b.key);break;case "primitive":if(c.length===0)a.root=b.value;else if(c=c[c.length-1],c.type==="object"){if(c.currentKey===void 0)throw Error("Primitive event without preceding key in object");
c.obj[c.currentKey]=b.value;c.currentKey=void 0}else c.type==="array"&&c.arr.push(b.value)}}function finalizeState(a){if(a.stack.length!==0)throw Error("Incomplete event stream: stack not empty at end");if(a.root===void 0)throw Error("No root value built from events");return a.root}
function tryFoldKeyChain(a,b,c,d,e,f,g){if(d.keyFolding==="safe"&&isJsonObject(b)&&(d=collectSingleKeyChain(a,b,g!=null?g:d.flattenDepth),a=d.segments,b=d.tail,d=d.leafValue,!(a.length<2||!a.every(function(h){return isIdentifierSegment(h)})||(g=buildFoldedKey(a),f=f?""+f+DOT+g:g,c.includes(g)||e&&e.has(f)))))return{foldedKey:g,remainder:b,leafValue:d,segmentCount:a.length}}
function collectSingleKeyChain(a,b,c){for(a=[a];a.length<c&&isJsonObject(b);){var d=Object.keys(b);if(d.length!==1)break;d=d[0];b=b[d];a.push(d)}return!isJsonObject(b)||isEmptyObject(b)?{segments:a,tail:void 0,leafValue:b}:{segments:a,tail:b,leafValue:b}}function buildFoldedKey(a){return a.join(DOT)}function encodePrimitive(a,b){return a===null?NULL_LITERAL:typeof a==="boolean"||typeof a==="number"?String(a):encodeStringLiteral(a,b)}
function encodeStringLiteral(a,b){b=b===void 0?DEFAULT_DELIMITER:b;return isSafeUnquoted(a,b)?a:""+DOUBLE_QUOTE+escapeString(a)+DOUBLE_QUOTE}function encodeKey(a){return isValidUnquotedKey(a)?a:""+DOUBLE_QUOTE+escapeString(a)+DOUBLE_QUOTE}function encodeAndJoinPrimitives(a,b){b=b===void 0?DEFAULT_DELIMITER:b;return a.map(function(c){return encodePrimitive(c,b)}).join(b)}
function formatHeader(a,b){var c=b==null?void 0:b.key,d=b==null?void 0:b.fields,e,f=(e=b==null?void 0:b.delimiter)!=null?e:COMMA;e="";c&&(e+=encodeKey(c));e+="["+a+(f!==DEFAULT_DELIMITER?f:"")+"]";d&&(c=d.map(function(g){return encodeKey(g)}),e+="{"+c.join(f)+"}");return e+":"}
function encodeJsonValue(a,b,c){var d;return $jscomp.generator.createGenerator(encodeJsonValue,function(e){if(e.nextAddress==1){if(!isJsonPrimitive(a))return e.jumpTo(2);d=encodePrimitive(a,b.delimiter);return d===""?e.jumpTo(3):e.yield(d,3)}return e.nextAddress!=2?e["return"]():isJsonArray(a)?e.yieldAll(encodeArrayLines(void 0,a,c,b),0):isJsonObject(a)?e.yieldAll(encodeObjectLines(a,c,b),0):e.jumpTo(0)})}
function encodeObjectLines(a,b,c,d,e,f){var g,h,m,p,q,n,u,k,t;return $jscomp.generator.createGenerator(encodeObjectLines,function(l){l.nextAddress==1&&(g=Object.keys(a),b!==0||d||(d=new Set(g.filter(function(w){return w.includes(".")}))),m=(h=f)!=null?h:c.flattenDepth,p=(0,$jscomp.makeIterator)(Object.entries(a)),q=p.next());if(l.nextAddress!=3){if(q.done)return l.jumpTo(0);n=q.value;u=(0,$jscomp.makeIterator)(n);k=u.next().value;t=u.next().value;return l.yieldAll(encodeKeyValuePairLines(k,t,b,c,
g,d,e,m),3)}q=p.next();return l.jumpTo(2)})}
function encodeKeyValuePairLines(a,b,c,d,e,f,g,h){var m,p,q,n,u,k,t,l,w,r,y,z,x;return $jscomp.generator.createGenerator(encodeKeyValuePairLines,function(v){switch(v.nextAddress){case 1:m=g?""+g+DOT+a:a;q=(p=h)!=null?p:d.flattenDepth;if(d.keyFolding!=="safe"||!e){v.jumpTo(2);break}n=tryFoldKeyChain(a,b,e,d,f,g,q);if(!n){v.jumpTo(2);break}u=n;k=u.foldedKey;t=u.remainder;l=u.leafValue;w=u.segmentCount;r=encodeKey(k);if(t!==void 0){v.jumpTo(4);break}if(isJsonPrimitive(l))return v.yield(indentedLine(c,r+
": "+encodePrimitive(l,d.delimiter),d.indent),12);if(isJsonArray(l))return v.yieldAll(encodeArrayLines(k,l,c,d),11);if(!isJsonObject(l)||!isEmptyObject(l)){v.jumpTo(4);break}return v.yield(indentedLine(c,r+":",d.indent),10);case 10:return v["return"]();case 11:return v["return"]();case 12:return v["return"]();case 4:if(!isJsonObject(t)){v.jumpTo(2);break}return v.yield(indentedLine(c,r+":",d.indent),14);case 14:return y=q-w,z=g?""+g+DOT+k:k,v.yieldAll(encodeObjectLines(t,c+1,d,f,z,y),15);case 15:return v["return"]();
case 2:x=encodeKey(a);if(isJsonPrimitive(b))return v.yield(indentedLine(c,x+": "+encodePrimitive(b,d.delimiter),d.indent),0);if(isJsonArray(b))return v.yieldAll(encodeArrayLines(a,b,c,d),0);if(!isJsonObject(b)){v.jumpTo(0);break}return v.yield(indentedLine(c,x+":",d.indent),21);case 21:if(isEmptyObject(b))v.jumpTo(0);else return v.yieldAll(encodeObjectLines(b,c+1,d,f,m,q),0)}})}
function encodeArrayLines(a,b,c,d){var e;return $jscomp.generator.createGenerator(encodeArrayLines,function(f){switch(f.nextAddress){case 1:if(b.length!==0){f.jumpTo(2);break}return f.yield(indentedLine(c,formatHeader(0,{key:a,delimiter:d.delimiter}),d.indent),3);case 3:return f["return"]();case 2:if(!isArrayOfPrimitives(b)){f.jumpTo(4);break}return f.yield(indentedLine(c,encodeInlineArrayLine(b,d.delimiter,a),d.indent),5);case 5:return f["return"]();case 4:if(!isArrayOfArrays(b)){f.jumpTo(6);break}if(!b.every(function(g){return isArrayOfPrimitives(g)})){f.jumpTo(6);
break}return f.yieldAll(encodeArrayOfArraysAsListItemsLines(a,b,c,d),8);case 8:return f["return"]();case 6:if(!isArrayOfObjects(b)){f.jumpTo(9);break}return(e=extractTabularHeader(b))?f.yieldAll(encodeArrayOfObjectsAsTabularLines(a,b,e,c,d),11):f.yieldAll(encodeMixedArrayAsListItemsLines(a,b,c,d),11);case 11:return f["return"]();case 9:return f.yieldAll(encodeMixedArrayAsListItemsLines(a,b,c,d),0)}})}
function encodeArrayOfArraysAsListItemsLines(a,b,c,d){var e,f,g,h;return $jscomp.generator.createGenerator(encodeArrayOfArraysAsListItemsLines,function(m){switch(m.nextAddress){case 1:return m.yield(indentedLine(c,formatHeader(b.length,{key:a,delimiter:d.delimiter}),d.indent),2);case 2:e=(0,$jscomp.makeIterator)(b),f=e.next();case 3:if(f.done){m.jumpTo(0);break}g=f.value;if(!isArrayOfPrimitives(g)){m.jumpTo(4);break}h=encodeInlineArrayLine(g,d.delimiter);return m.yield(indentedListItem(c+1,h,d.indent),
4);case 4:f=e.next(),m.jumpTo(3)}})}function encodeInlineArrayLine(a,b,c){c=formatHeader(a.length,{key:c,delimiter:b});b=encodeAndJoinPrimitives(a,b);return a.length===0?c:c+" "+b}function encodeArrayOfObjectsAsTabularLines(a,b,c,d,e){return $jscomp.generator.createGenerator(encodeArrayOfObjectsAsTabularLines,function(f){return f.nextAddress==1?f.yield(indentedLine(d,formatHeader(b.length,{key:a,fields:c,delimiter:e.delimiter}),e.indent),2):f.yieldAll(writeTabularRowsLines(b,c,d+1,e),0)})}
function extractTabularHeader(a){if(a.length!==0){var b=Object.keys(a[0]);if(b.length!==0&&isTabularArray(a,b))return b}}function isTabularArray(a,b){for(var c=(0,$jscomp.makeIterator)(a),d=c.next();!d.done;d=c.next()){d=d.value;if(Object.keys(d).length!==b.length)return!1;for(var e=(0,$jscomp.makeIterator)(b),f=e.next();!f.done;f=e.next())if(f=f.value,!(f in d&&isJsonPrimitive(d[f])))return!1}return!0}
function writeTabularRowsLines(a,b,c,d){var e,f,g;return $jscomp.generator.createGenerator(writeTabularRowsLines,function(h){h.nextAddress==1&&(e=(0,$jscomp.makeIterator)(a),f=e.next(),g={});if(h.nextAddress!=3){if(f.done)return h.jumpTo(0);g.row$jscomp$1=f.value;return h.yield(indentedLine(c,encodeAndJoinPrimitives(b.map(function(m){return function(p){return m.row$jscomp$1[p]}}(g)),d.delimiter),d.indent),3)}g={row$jscomp$1:void 0};f=e.next();return h.jumpTo(2)})}
function encodeMixedArrayAsListItemsLines(a,b,c,d){var e,f,g;return $jscomp.generator.createGenerator(encodeMixedArrayAsListItemsLines,function(h){switch(h.nextAddress){case 1:return h.yield(indentedLine(c,formatHeader(b.length,{key:a,delimiter:d.delimiter}),d.indent),2);case 2:e=(0,$jscomp.makeIterator)(b),f=e.next();case 3:if(f.done){h.jumpTo(0);break}g=f.value;return h.yieldAll(encodeListItemValueLines(g,c+1,d),4);case 4:f=e.next(),h.jumpTo(3)}})}
function encodeObjectAsListItemLines(a,b,c){var d,e,f,g,h,m,p,q,n,u;return $jscomp.generator.createGenerator(encodeObjectAsListItemLines,function(k){switch(k.nextAddress){case 1:if(!isEmptyObject(a)){k.jumpTo(2);break}return k.yield(indentedLine(b,LIST_ITEM_MARKER,c.indent),3);case 3:return k["return"]();case 2:d=Object.entries(a);e=(0,$jscomp.makeIterator)(d[0]);f=e.next().value;g=e.next().value;h=d.slice(1);if(!isJsonArray(g)||!isArrayOfObjects(g)){k.jumpTo(4);break}m=extractTabularHeader(g);if(!m){k.jumpTo(4);
break}return k.yield(indentedListItem(b,formatHeader(g.length,{key:f,fields:m,delimiter:c.delimiter}),c.indent),6);case 6:return k.yieldAll(writeTabularRowsLines(g,m,b+2,c),7);case 7:if(!(h.length>0)){k.jumpTo(8);break}return k.yieldAll(encodeObjectLines(Object.fromEntries(h),b+1,c),8);case 8:return k["return"]();case 4:p=encodeKey(f);if(isJsonPrimitive(g))return k.yield(indentedListItem(b,p+": "+encodePrimitive(g,c.delimiter),c.indent),11);if(isJsonArray(g))return g.length===0?k.yield(indentedListItem(b,
""+p+formatHeader(0,{delimiter:c.delimiter}),c.indent),11):isArrayOfPrimitives(g)?k.yield(indentedListItem(b,""+p+encodeInlineArrayLine(g,c.delimiter),c.indent),11):k.yield(indentedListItem(b,""+p+formatHeader(g.length,{delimiter:c.delimiter}),c.indent),22);if(!isJsonObject(g)){k.jumpTo(11);break}return k.yield(indentedListItem(b,p+":",c.indent),15);case 15:if(isEmptyObject(g)){k.jumpTo(11);break}return k.yieldAll(encodeObjectLines(g,b+2,c),11);case 22:q=(0,$jscomp.makeIterator)(g),n=q.next();case 23:if(n.done){k.jumpTo(11);
break}u=n.value;return k.yieldAll(encodeListItemValueLines(u,b+2,c),24);case 24:n=q.next();k.jumpTo(23);break;case 11:if(h.length>0)return k.yieldAll(encodeObjectLines(Object.fromEntries(h),b+1,c),0);k.jumpTo(0)}})}
function encodeListItemValueLines(a,b,c){var d,e,f;return $jscomp.generator.createGenerator(encodeListItemValueLines,function(g){switch(g.nextAddress){case 1:if(isJsonPrimitive(a))return g.yield(indentedListItem(b,encodePrimitive(a,c.delimiter),c.indent),0);if(isJsonArray(a))return isArrayOfPrimitives(a)?g.yield(indentedListItem(b,encodeInlineArrayLine(a,c.delimiter),c.indent),0):g.yield(indentedListItem(b,formatHeader(a.length,{delimiter:c.delimiter}),c.indent),10);if(!isJsonObject(a)){g.jumpTo(0);
break}return g.yieldAll(encodeObjectAsListItemLines(a,b,c),0);case 10:d=(0,$jscomp.makeIterator)(a),e=d.next();case 11:if(e.done){g.jumpTo(0);break}f=e.value;return g.yieldAll(encodeListItemValueLines(f,b+1,c),12);case 12:e=d.next(),g.jumpTo(11)}})}function indentedLine(a,b,c){return" ".repeat(c*a)+b}function indentedListItem(a,b,c){return indentedLine(a,LIST_ITEM_PREFIX+b,c)}
function applyReplacer(a,b){var c=b("",a,[]);return c===void 0?transformChildren(a,b,[]):transformChildren(normalizeValue(c),b,[])}function transformChildren(a,b,c){return isJsonObject(a)?transformObject(a,b,c):isJsonArray(a)?transformArray(a,b,c):a}
function transformObject(a,b,c){var d={};a=(0,$jscomp.makeIterator)(Object.entries(a));for(var e=a.next();!e.done;e=a.next()){var f=(0,$jscomp.makeIterator)(e.value);e=f.next().value;var g=f.next().value;f=[].concat((0,$jscomp.arrayFromIterable)(c),[e]);g=b(e,g,f);g!==void 0&&(d[e]=transformChildren(normalizeValue(g),b,f))}return d}
function transformArray(a,b,c){for(var d=[],e=0;e<a.length;e++){var f=a[e],g=[].concat((0,$jscomp.arrayFromIterable)(c),[e]);f=b(String(e),f,g);f!==void 0&&(f=normalizeValue(f),d.push(transformChildren(f,b,g)))}return d}function encode(a,b){return Array.from(encodeLines(a,b)).join("\n")}function decode(a,b){return decodeFromLines(a.split("\n"),b)}function encodeLines(a,b){var c=normalizeValue(a),d=resolveOptions(b);return encodeJsonValue(d.replacer?applyReplacer(c,d.replacer):c,d,0)}
function decodeFromLines(a,b){var c=resolveDecodeOptions(b),d=buildValueFromEvents(decodeStreamSync$1(a,{indent:c.indent,strict:c.strict}));return c.expandPaths==="safe"?expandPathsSafe(d,c.strict):d}function decodeStreamSync(a,b){return decodeStreamSync$1(a,b)}function decodeStream(a,b){return decodeStream$1(a,b)}
function resolveOptions(a){var b,c,d,e;return{indent:(b=a==null?void 0:a.indent)!=null?b:2,delimiter:(c=a==null?void 0:a.delimiter)!=null?c:DEFAULT_DELIMITER,keyFolding:(d=a==null?void 0:a.keyFolding)!=null?d:"off",flattenDepth:(e=a==null?void 0:a.flattenDepth)!=null?e:Number.POSITIVE_INFINITY,replacer:a==null?void 0:a.replacer}}
function resolveDecodeOptions(a){var b,c,d;return{indent:(b=a==null?void 0:a.indent)!=null?b:2,strict:(c=a==null?void 0:a.strict)!=null?c:!0,expandPaths:(d=a==null?void 0:a.expandPaths)!=null?d:"off"}};
