jobs:
   # Build OpenAF
   - name  : Build OpenAFOS
     exec  : >
        global.path = (isDef(args.path)) ? args.path : ".";
        if (isUnDef(args.openafJSON)) args.openafJSON = global.path + "/openaf.json";
        if (isUnDef(args.openafDIST)) args.openafDIST = "nightly";
        __expr = "withDir=" + global.path + ";withJSON=" + args.openafJSON + ";withDist=" + args.openafDIST;
        af.load(global.path + "/buildos.js");

   # Repack the recently build openaf
   - name  : Repack OpenAFOS
     deps  :
        - Build OpenAFOS
     exec  : >
        log("Repacking...");
        sh("java -jar " + global.path + "/openaf.jar --repack", "", undefined, true);

   # Copy OpenAF to the right place for use
   - name  : Copy OpenAF
     deps  :
        - Build OpenAFOS
        - Repack OpenAFOS
     exec  : >
        log("Copying...");
        //sh("cp " + global.path + "/openaf.jar " + global.path + "/dist/openaf.jar", "", undefined, true);
        io.mkdir(global.path + "/dist");
        io.cp(global.path + "/openaf.jar", global.path + "/dist/openaf.jar");

todo:
   - Build OpenAFOS
   - Repack OpenAFOS
   - Copy OpenAF
