(function(p){var h="object"==typeof self&&self.self===self&&self||"object"==typeof global&&global.global===global&&global;if("function"===typeof define&&define.amd)define(["underscore","jquery","exports"],function(d,k,z){h.Backbone=p(h,z,d,k)});else if("undefined"!==typeof exports){var d=require("underscore"),k;try{k=require("jquery")}catch(B){}p(h,exports,d,k)}else h.Backbone=p(h,{},h._,h.jQuery||h.Zepto||h.ender||h.$)})(function(p,h,d,k){var B=p.Backbone,C=Array.prototype.slice;h.VERSION="1.3.3";
h.$=k;h.noConflict=function(){p.Backbone=B;return this};h.emulateHTTP=!1;h.emulateJSON=!1;var z=function(a,b,c){switch(a){case 1:return function(){return d[b](this[c])};case 2:return function(a){return d[b](this[c],a)};case 3:return function(a,f){return d[b](this[c],D(a,this),f)};case 4:return function(a,f,g){return d[b](this[c],D(a,this),f,g)};default:return function(){var a=C.call(arguments);a.unshift(this[c]);return d[b].apply(d,a)}}},w=function(a,b,c){d.each(b,function(b,f){d[f]&&(a.prototype[f]=
z(b,f,c))})},D=function(a,b){return d.isFunction(a)?a:d.isObject(a)&&!b._isModel(a)?M(a):d.isString(a)?function(b){return b.get(a)}:a},M=function(a){var b=d.matches(a);return function(a){return b(a.attributes)}};k=h.Events={};var E=/\s+/,r=function(a,b,c,e,f){var g=0,h;if(c&&"object"===typeof c)for(void 0!==e&&("context"in f)&&void 0===f.context&&(f.context=e),h=d.keys(c);g<h.length;g++)b=r(a,b,h[g],c[h[g]],f);else if(c&&E.test(c))for(h=c.split(E);g<h.length;g++)b=a(b,h[g],e,f);else b=a(b,c,e,f);
return b};k.on=function(a,b,c){return F(this,a,b,c)};var F=function(a,b,c,e,f){a._events=r(N,a._events||{},b,c,{context:e,ctx:a,listening:f});f&&((a._listeners||(a._listeners={}))[f.id]=f);return a};k.listenTo=function(a,b,c){if(!a)return this;var e=a._listenId||(a._listenId=d.uniqueId("l")),f=this._listeningTo||(this._listeningTo={}),g=f[e];g||(g=this._listenId||(this._listenId=d.uniqueId("l")),g=f[e]={obj:a,objId:e,id:g,listeningTo:f,count:0});F(a,b,c,this,g);return this};var N=function(a,b,c,e){if(c){b=
a[b]||(a[b]=[]);var f=e.context,d=e.ctx;(e=e.listening)&&e.count++;b.push({callback:c,context:f,ctx:f||d,listening:e})}return a};k.off=function(a,b,c){if(!this._events)return this;this._events=r(O,this._events,a,b,{context:c,listeners:this._listeners});return this};k.stopListening=function(a,b,c){var e=this._listeningTo;if(!e)return this;a=a?[a._listenId]:d.keys(e);for(var f=0;f<a.length;f++){var g=e[a[f]];if(!g)break;g.obj.off(b,c,this)}return this};var O=function(a,b,c,e){if(a){var f=0,g,h=e.context;
e=e.listeners;if(b||c||h){for(var G=b?[b]:d.keys(a);f<G.length;f++){b=G[f];var k=a[b];if(!k)break;for(var v=[],m=0;m<k.length;m++)g=k[m],c&&c!==g.callback&&c!==g.callback._callback||h&&h!==g.context?v.push(g):(g=g.listening)&&0===--g.count&&(delete e[g.id],delete g.listeningTo[g.objId]);v.length?a[b]=v:delete a[b]}return a}for(a=d.keys(e);f<a.length;f++)g=e[a[f]],delete e[g.id],delete g.listeningTo[g.objId]}};k.once=function(a,b,c){var e=r(H,{},a,b,d.bind(this.off,this));"string"===typeof a&&null==
c&&(b=void 0);return this.on(e,b,c)};k.listenToOnce=function(a,b,c){b=r(H,{},b,c,d.bind(this.stopListening,this,a));return this.listenTo(a,b)};var H=function(a,b,c,e){if(c){var f=a[b]=d.once(function(){e(b,f);c.apply(this,arguments)});f._callback=c}return a};k.trigger=function(a){if(!this._events)return this;for(var b=Math.max(0,arguments.length-1),c=Array(b),e=0;e<b;e++)c[e]=arguments[e+1];r(P,this._events,a,void 0,c);return this};var P=function(a,b,c,e){if(a){c=a[b];var f=a.all;c&&f&&(f=f.slice());
c&&I(c,e);f&&I(f,[b].concat(e))}return a},I=function(a,b){var c,e=-1,f=a.length,d=b[0],h=b[1],k=b[2];switch(b.length){case 0:for(;++e<f;)(c=a[e]).callback.call(c.ctx);break;case 1:for(;++e<f;)(c=a[e]).callback.call(c.ctx,d);break;case 2:for(;++e<f;)(c=a[e]).callback.call(c.ctx,d,h);break;case 3:for(;++e<f;)(c=a[e]).callback.call(c.ctx,d,h,k);break;default:for(;++e<f;)(c=a[e]).callback.apply(c.ctx,b)}};k.bind=k.on;k.unbind=k.off;d.extend(h,k);var x=h.Model=function(a,b){var c=a||{};b||(b={});this.cid=
d.uniqueId(this.cidPrefix);this.attributes={};b.collection&&(this.collection=b.collection);b.parse&&(c=this.parse(c,b)||{});var e=d.result(this,"defaults"),c=d.defaults(d.extend({},e,c),e);this.set(c,b);this.changed={};this.initialize.apply(this,arguments)};d.extend(x.prototype,k,{changed:null,validationError:null,idAttribute:"id",cidPrefix:"c",initialize:function(){},toJSON:function(a){return d.clone(this.attributes)},sync:function(){return h.sync.apply(this,arguments)},get:function(a){return this.attributes[a]},
escape:function(a){return d.escape(this.get(a))},has:function(a){return null!=this.get(a)},matches:function(a){return!!d.iteratee(a,this)(this.attributes)},set:function(a,b,c){if(null==a)return this;var e;"object"===typeof a?(e=a,c=b):(e={})[a]=b;c||(c={});if(!this._validate(e,c))return!1;var f=c.unset;a=c.silent;var g=[],h=this._changing;this._changing=!0;h||(this._previousAttributes=d.clone(this.attributes),this.changed={});var k=this.attributes,t=this.changed,v=this._previousAttributes,m;for(m in e)b=
e[m],d.isEqual(k[m],b)||g.push(m),d.isEqual(v[m],b)?delete t[m]:t[m]=b,f?delete k[m]:k[m]=b;this.idAttribute in e&&(this.id=this.get(this.idAttribute));if(!a)for(g.length&&(this._pending=c),b=0;b<g.length;b++)this.trigger("change:"+g[b],this,k[g[b]],c);if(h)return this;if(!a)for(;this._pending;)c=this._pending,this._pending=!1,this.trigger("change",this,c);this._changing=this._pending=!1;return this},unset:function(a,b){return this.set(a,void 0,d.extend({},b,{unset:!0}))},clear:function(a){var b=
{},c;for(c in this.attributes)b[c]=void 0;return this.set(b,d.extend({},a,{unset:!0}))},hasChanged:function(a){return null==a?!d.isEmpty(this.changed):d.has(this.changed,a)},changedAttributes:function(a){if(!a)return this.hasChanged()?d.clone(this.changed):!1;var b=this._changing?this._previousAttributes:this.attributes,c={},e;for(e in a){var f=a[e];d.isEqual(b[e],f)||(c[e]=f)}return d.size(c)?c:!1},previous:function(a){return null!=a&&this._previousAttributes?this._previousAttributes[a]:null},previousAttributes:function(){return d.clone(this._previousAttributes)},
fetch:function(a){a=d.extend({parse:!0},a);var b=this,c=a.success;a.success=function(e){var f=a.parse?b.parse(e,a):e;if(!b.set(f,a))return!1;c&&c.call(a.context,b,e,a);b.trigger("sync",b,e,a)};y(this,a);return this.sync("read",this,a)},save:function(a,b,c){var e;null==a||"object"===typeof a?(e=a,c=b):(e={})[a]=b;c=d.extend({validate:!0,parse:!0},c);var f=c.wait;if(e&&!f){if(!this.set(e,c))return!1}else if(!this._validate(e,c))return!1;var g=this,h=c.success,k=this.attributes;c.success=function(a){g.attributes=
k;var b=c.parse?g.parse(a,c):a;f&&(b=d.extend({},e,b));if(b&&!g.set(b,c))return!1;h&&h.call(c.context,g,a,c);g.trigger("sync",g,a,c)};y(this,c);e&&f&&(this.attributes=d.extend({},k,e));a=this.isNew()?"create":c.patch?"patch":"update";"patch"!==a||c.attrs||(c.attrs=e);a=this.sync(a,this,c);this.attributes=k;return a},destroy:function(a){a=a?d.clone(a):{};var b=this,c=a.success,e=a.wait,f=function(){b.stopListening();b.trigger("destroy",b,b.collection,a)};a.success=function(d){e&&f();c&&c.call(a.context,
b,d,a);b.isNew()||b.trigger("sync",b,d,a)};var g=!1;this.isNew()?d.defer(a.success):(y(this,a),g=this.sync("delete",this,a));e||f();return g},url:function(){var a=d.result(this,"urlRoot")||d.result(this.collection,"url")||J();if(this.isNew())return a;var b=this.get(this.idAttribute);return a.replace(/[^\/]$/,"$&/")+encodeURIComponent(b)},parse:function(a,b){return a},clone:function(){return new this.constructor(this.attributes)},isNew:function(){return!this.has(this.idAttribute)},isValid:function(a){return this._validate({},
d.extend({},a,{validate:!0}))},_validate:function(a,b){if(!b.validate||!this.validate)return!0;a=d.extend({},this.attributes,a);a=this.validationError=this.validate(a,b)||null;if(!a)return!0;this.trigger("invalid",this,a,d.extend(b,{validationError:a}));return!1}});w(x,{keys:1,values:1,pairs:1,invert:1,pick:0,omit:0,chain:1,isEmpty:1},"attributes");var A=h.Collection=function(a,b){b||(b={});b.model&&(this.model=b.model);void 0!==b.comparator&&(this.comparator=b.comparator);this._reset();this.initialize.apply(this,
arguments);a&&this.reset(a,d.extend({silent:!0},b))},Q={add:!0,remove:!0,merge:!0},R={add:!0,remove:!1},K=function(a,b,c){c=Math.min(Math.max(c,0),a.length);var e=Array(a.length-c),f=b.length,d;for(d=0;d<e.length;d++)e[d]=a[d+c];for(d=0;d<f;d++)a[d+c]=b[d];for(d=0;d<e.length;d++)a[d+f+c]=e[d]};d.extend(A.prototype,k,{model:x,initialize:function(){},toJSON:function(a){return this.map(function(b){return b.toJSON(a)})},sync:function(){return h.sync.apply(this,arguments)},add:function(a,b){return this.set(a,
d.extend({merge:!1},b,R))},remove:function(a,b){b=d.extend({},b);var c=!d.isArray(a);a=c?[a]:a.slice();a=this._removeModels(a,b);!b.silent&&a.length&&(b.changes={added:[],merged:[],removed:a},this.trigger("update",this,b));return c?a[0]:a},set:function(a,b){if(null!=a){b=d.extend({},Q,b);b.parse&&!this._isModel(a)&&(a=this.parse(a,b)||[]);var c=!d.isArray(a);a=c?[a]:a.slice();var e=b.at;null!=e&&(e=+e);e>this.length&&(e=this.length);0>e&&(e+=this.length+1);var f=[],g=[],h=[],k=[],t={},v=b.add,m=b.merge,
q=b.remove,p=!1,r=this.comparator&&null==e&&!1!==b.sort,w=d.isString(this.comparator)?this.comparator:null,l,n;for(n=0;n<a.length;n++){l=a[n];var u=this.get(l);u?(m&&l!==u&&(l=this._isModel(l)?l.attributes:l,b.parse&&(l=u.parse(l,b)),u.set(l,b),h.push(u),r&&!p&&(p=u.hasChanged(w))),t[u.cid]||(t[u.cid]=!0,f.push(u)),a[n]=u):v&&(l=a[n]=this._prepareModel(l,b))&&(g.push(l),this._addReference(l,b),t[l.cid]=!0,f.push(l))}if(q){for(n=0;n<this.length;n++)l=this.models[n],t[l.cid]||k.push(l);k.length&&this._removeModels(k,
b)}t=!1;f.length&&!r&&v&&q?(t=this.length!==f.length||d.some(this.models,function(a,b){return a!==f[b]}),this.models.length=0,K(this.models,f,0),this.length=this.models.length):g.length&&(r&&(p=!0),K(this.models,g,null==e?this.length:e),this.length=this.models.length);p&&this.sort({silent:!0});if(!b.silent){for(n=0;n<g.length;n++)null!=e&&(b.index=e+n),l=g[n],l.trigger("add",l,this,b);(p||t)&&this.trigger("sort",this,b);if(g.length||k.length||h.length)b.changes={added:g,removed:k,merged:h},this.trigger("update",
this,b)}return c?a[0]:a}},reset:function(a,b){b=b?d.clone(b):{};for(var c=0;c<this.models.length;c++)this._removeReference(this.models[c],b);b.previousModels=this.models;this._reset();a=this.add(a,d.extend({silent:!0},b));b.silent||this.trigger("reset",this,b);return a},push:function(a,b){return this.add(a,d.extend({at:this.length},b))},pop:function(a){var b=this.at(this.length-1);return this.remove(b,a)},unshift:function(a,b){return this.add(a,d.extend({at:0},b))},shift:function(a){var b=this.at(0);
return this.remove(b,a)},slice:function(){return C.apply(this.models,arguments)},get:function(a){if(null!=a)return this._byId[a]||this._byId[this.modelId(a.attributes||a)]||a.cid&&this._byId[a.cid]},has:function(a){return null!=this.get(a)},at:function(a){0>a&&(a+=this.length);return this.models[a]},where:function(a,b){return this[b?"find":"filter"](a)},findWhere:function(a){return this.where(a,!0)},sort:function(a){var b=this.comparator;if(!b)throw Error("Cannot sort a set without a comparator");
a||(a={});var c=b.length;d.isFunction(b)&&(b=d.bind(b,this));1===c||d.isString(b)?this.models=this.sortBy(b):this.models.sort(b);a.silent||this.trigger("sort",this,a);return this},pluck:function(a){return this.map(a+"")},fetch:function(a){a=d.extend({parse:!0},a);var b=a.success,c=this;a.success=function(e){c[a.reset?"reset":"set"](e,a);b&&b.call(a.context,c,e,a);c.trigger("sync",c,e,a)};y(this,a);return this.sync("read",this,a)},create:function(a,b){b=b?d.clone(b):{};var c=b.wait;a=this._prepareModel(a,
b);if(!a)return!1;c||this.add(a,b);var e=this,f=b.success;b.success=function(a,b,d){c&&e.add(a,d);f&&f.call(d.context,a,b,d)};a.save(null,b);return a},parse:function(a,b){return a},clone:function(){return new this.constructor(this.models,{model:this.model,comparator:this.comparator})},modelId:function(a){return a[this.model.prototype.idAttribute||"id"]},_reset:function(){this.length=0;this.models=[];this._byId={}},_prepareModel:function(a,b){if(this._isModel(a))return a.collection||(a.collection=
this),a;b=b?d.clone(b):{};b.collection=this;a=new this.model(a,b);if(!a.validationError)return a;this.trigger("invalid",this,a.validationError,b);return!1},_removeModels:function(a,b){for(var c=[],e=0;e<a.length;e++){var d=this.get(a[e]);if(d){var g=this.indexOf(d);this.models.splice(g,1);this.length--;delete this._byId[d.cid];var h=this.modelId(d.attributes);null!=h&&delete this._byId[h];b.silent||(b.index=g,d.trigger("remove",d,this,b));c.push(d);this._removeReference(d,b)}}return c},_isModel:function(a){return a instanceof
x},_addReference:function(a,b){this._byId[a.cid]=a;b=this.modelId(a.attributes);null!=b&&(this._byId[b]=a);a.on("all",this._onModelEvent,this)},_removeReference:function(a,b){delete this._byId[a.cid];b=this.modelId(a.attributes);null!=b&&delete this._byId[b];this===a.collection&&delete a.collection;a.off("all",this._onModelEvent,this)},_onModelEvent:function(a,b,c,e){if(b){if(("add"===a||"remove"===a)&&c!==this)return;"destroy"===a&&this.remove(b,e);if("change"===a){var d=this.modelId(b.previousAttributes()),
g=this.modelId(b.attributes);d!==g&&(null!=d&&delete this._byId[d],null!=g&&(this._byId[g]=b))}}this.trigger.apply(this,arguments)}});w(A,{forEach:3,each:3,map:3,collect:3,reduce:0,foldl:0,inject:0,reduceRight:0,foldr:0,find:3,detect:3,filter:3,select:3,reject:3,every:3,all:3,some:3,any:3,include:3,includes:3,contains:3,invoke:0,max:3,min:3,toArray:1,size:1,first:3,head:3,take:3,initial:3,rest:3,tail:3,drop:3,last:3,without:0,difference:0,indexOf:3,shuffle:1,lastIndexOf:3,isEmpty:1,chain:1,sample:3,
partition:3,groupBy:3,countBy:3,sortBy:3,indexBy:3,findIndex:3,findLastIndex:3},"models");var w=h.View=function(a){this.cid=d.uniqueId("view");d.extend(this,d.pick(a,S));this._ensureElement();this.initialize.apply(this,arguments)},T=/^(\S+)\s*(.*)$/,S="model collection el id attributes className tagName events".split(" ");d.extend(w.prototype,k,{tagName:"div",$:function(a){return this.$el.find(a)},initialize:function(){},render:function(){return this},remove:function(){this._removeElement();this.stopListening();
return this},_removeElement:function(){this.$el.remove()},setElement:function(a){this.undelegateEvents();this._setElement(a);this.delegateEvents();return this},_setElement:function(a){this.$el=a instanceof h.$?a:h.$(a);this.el=this.$el[0]},delegateEvents:function(a){a||(a=d.result(this,"events"));if(!a)return this;this.undelegateEvents();for(var b in a){var c=a[b];d.isFunction(c)||(c=this[c]);if(c){var e=b.match(T);this.delegate(e[1],e[2],d.bind(c,this))}}return this},delegate:function(a,b,c){this.$el.on(a+
".delegateEvents"+this.cid,b,c);return this},undelegateEvents:function(){this.$el&&this.$el.off(".delegateEvents"+this.cid);return this},undelegate:function(a,b,c){this.$el.off(a+".delegateEvents"+this.cid,b,c);return this},_createElement:function(a){return document.createElement(a)},_ensureElement:function(){if(this.el)this.setElement(d.result(this,"el"));else{var a=d.extend({},d.result(this,"attributes"));this.id&&(a.id=d.result(this,"id"));this.className&&(a["class"]=d.result(this,"className"));
this.setElement(this._createElement(d.result(this,"tagName")));this._setAttributes(a)}},_setAttributes:function(a){this.$el.attr(a)}});h.sync=function(a,b,c){var e=U[a];d.defaults(c||(c={}),{emulateHTTP:h.emulateHTTP,emulateJSON:h.emulateJSON});var f={type:e,dataType:"json"};c.url||(f.url=d.result(b,"url")||J());null!=c.data||!b||"create"!==a&&"update"!==a&&"patch"!==a||(f.contentType="application/json",f.data=JSON.stringify(c.attrs||b.toJSON(c)));c.emulateJSON&&(f.contentType="application/x-www-form-urlencoded",
f.data=f.data?{model:f.data}:{});if(c.emulateHTTP&&("PUT"===e||"DELETE"===e||"PATCH"===e)){f.type="POST";c.emulateJSON&&(f.data._method=e);var g=c.beforeSend;c.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",e);if(g)return g.apply(this,arguments)}}"GET"===f.type||c.emulateJSON||(f.processData=!1);var k=c.error;c.error=function(a,b,e){c.textStatus=b;c.errorThrown=e;k&&k.call(c.context,a,b,e)};a=c.xhr=h.ajax(d.extend(f,c));b.trigger("request",b,a,c);return a};var U={create:"POST",
update:"PUT",patch:"PATCH","delete":"DELETE",read:"GET"};h.ajax=function(){return h.$.ajax.apply(h.$,arguments)};var L=h.Router=function(a){a||(a={});a.routes&&(this.routes=a.routes);this._bindRoutes();this.initialize.apply(this,arguments)},V=/\((.*?)\)/g,W=/(\(\?)?:\w+/g,X=/\*\w+/g,Y=/[\-{}\[\]+?.,\\\^$|#\s]/g;d.extend(L.prototype,k,{initialize:function(){},route:function(a,b,c){d.isRegExp(a)||(a=this._routeToRegExp(a));d.isFunction(b)&&(c=b,b="");c||(c=this[b]);var e=this;h.history.route(a,function(d){d=
e._extractParameters(a,d);!1!==e.execute(c,d,b)&&(e.trigger.apply(e,["route:"+b].concat(d)),e.trigger("route",b,d),h.history.trigger("route",e,b,d))});return this},execute:function(a,b,c){a&&a.apply(this,b)},navigate:function(a,b){h.history.navigate(a,b);return this},_bindRoutes:function(){if(this.routes){this.routes=d.result(this,"routes");for(var a,b=d.keys(this.routes);null!=(a=b.pop());)this.route(a,this.routes[a])}},_routeToRegExp:function(a){a=a.replace(Y,"\\$&").replace(V,"(?:$1)?").replace(W,
function(a,c){return c?a:"([^/?]+)"}).replace(X,"([^?]*?)");return new RegExp("^"+a+"(?:\\?([\\s\\S]*))?$")},_extractParameters:function(a,b){var c=a.exec(b).slice(1);return d.map(c,function(a,b){return b===c.length-1?a||null:a?decodeURIComponent(a):null})}});var q=h.History=function(){this.handlers=[];this.checkUrl=d.bind(this.checkUrl,this);"undefined"!==typeof window&&(this.location=window.location,this.history=window.history)},Z=/^[#\/]|\s+$/g,aa=/^\/+|\/+$/g,ba=/#.*$/;q.started=!1;d.extend(q.prototype,
k,{interval:50,atRoot:function(){return this.location.pathname.replace(/[^\/]$/,"$&/")===this.root&&!this.getSearch()},matchRoot:function(){return this.decodeFragment(this.location.pathname).slice(0,this.root.length-1)+"/"===this.root},decodeFragment:function(a){return decodeURI(a.replace(/%25/g,"%2525"))},getSearch:function(){var a=this.location.href.replace(/#.*/,"").match(/\?.+/);return a?a[0]:""},getHash:function(a){return(a=(a||this).location.href.match(/#(.*)$/))?a[1]:""},getPath:function(){var a=
this.decodeFragment(this.location.pathname+this.getSearch()).slice(this.root.length-1);return"/"===a.charAt(0)?a.slice(1):a},getFragment:function(a){null==a&&(a=this._usePushState||!this._wantsHashChange?this.getPath():this.getHash());return a.replace(Z,"")},start:function(a){if(q.started)throw Error("Backbone.history has already been started");q.started=!0;this.options=d.extend({root:"/"},this.options,a);this.root=this.options.root;this._wantsHashChange=!1!==this.options.hashChange;this._hasHashChange=
"onhashchange"in window&&(void 0===document.documentMode||7<document.documentMode);this._useHashChange=this._wantsHashChange&&this._hasHashChange;this._wantsPushState=!!this.options.pushState;this._hasPushState=!(!this.history||!this.history.pushState);this._usePushState=this._wantsPushState&&this._hasPushState;this.fragment=this.getFragment();this.root=("/"+this.root+"/").replace(aa,"/");if(this._wantsHashChange&&this._wantsPushState)if(this._hasPushState||this.atRoot())this._hasPushState&&this.atRoot()&&
this.navigate(this.getHash(),{replace:!0});else return a=this.root.slice(0,-1)||"/",this.location.replace(a+"#"+this.getPath()),!0;this._hasHashChange||!this._wantsHashChange||this._usePushState||(this.iframe=document.createElement("iframe"),this.iframe.src="javascript:0",this.iframe.style.display="none",this.iframe.tabIndex=-1,a=document.body,a=a.insertBefore(this.iframe,a.firstChild).contentWindow,a.document.open(),a.document.close(),a.location.hash="#"+this.fragment);a=window.addEventListener||
function(a,c){return attachEvent("on"+a,c)};this._usePushState?a("popstate",this.checkUrl,!1):this._useHashChange&&!this.iframe?a("hashchange",this.checkUrl,!1):this._wantsHashChange&&(this._checkUrlInterval=setInterval(this.checkUrl,this.interval));if(!this.options.silent)return this.loadUrl()},stop:function(){var a=window.removeEventListener||function(a,c){return detachEvent("on"+a,c)};this._usePushState?a("popstate",this.checkUrl,!1):this._useHashChange&&!this.iframe&&a("hashchange",this.checkUrl,
!1);this.iframe&&(document.body.removeChild(this.iframe),this.iframe=null);this._checkUrlInterval&&clearInterval(this._checkUrlInterval);q.started=!1},route:function(a,b){this.handlers.unshift({route:a,callback:b})},checkUrl:function(a){a=this.getFragment();a===this.fragment&&this.iframe&&(a=this.getHash(this.iframe.contentWindow));if(a===this.fragment)return!1;this.iframe&&this.navigate(a);this.loadUrl()},loadUrl:function(a){if(!this.matchRoot())return!1;a=this.fragment=this.getFragment(a);return d.some(this.handlers,
function(b){if(b.route.test(a))return b.callback(a),!0})},navigate:function(a,b){if(!q.started)return!1;b&&!0!==b||(b={trigger:!!b});a=this.getFragment(a||"");var c=this.root;if(""===a||"?"===a.charAt(0))c=c.slice(0,-1)||"/";c+=a;a=this.decodeFragment(a.replace(ba,""));if(this.fragment!==a){this.fragment=a;if(this._usePushState)this.history[b.replace?"replaceState":"pushState"]({},document.title,c);else if(this._wantsHashChange)this._updateHash(this.location,a,b.replace),this.iframe&&a!==this.getHash(this.iframe.contentWindow)&&
(c=this.iframe.contentWindow,b.replace||(c.document.open(),c.document.close()),this._updateHash(c.location,a,b.replace));else return this.location.assign(c);if(b.trigger)return this.loadUrl(a)}},_updateHash:function(a,b,c){c?(c=a.href.replace(/(javascript:|#).*$/,""),a.replace(c+"#"+b)):a.hash="#"+b}});h.history=new q;x.extend=A.extend=L.extend=w.extend=q.extend=function(a,b){var c=this,e;e=a&&d.has(a,"constructor")?a.constructor:function(){return c.apply(this,arguments)};d.extend(e,c,b);e.prototype=
d.create(c.prototype,a);e.prototype.constructor=e;e.__super__=c.prototype;return e};var J=function(){throw Error('A "url" property or function must be specified');},y=function(a,b){var c=b.error;b.error=function(d){c&&c.call(b.context,a,d,b);a.trigger("error",a,d,b)}};return h});
