var jLinq,jlinq,jl;
(function(){var b={command:{query:0,select:1,action:2},exp:{get_path:/\./g,escape_regex:/[\-\[\]\{\}\(\)\*\+\?\.\,\\\^\$\|\#\s]/g},type:{nothing:-1,undefined:0,string:1,number:2,array:3,regex:4,bool:5,method:6,datetime:7,object:99},library:{commands:{},types:{},addType:function(a,c){b.library.types[a]=c},extend:function(a){b.util.isType(b.type.array,a)||(a=[a]);b.util.each(a,function(a){b.library.commands[a.name]=a})},query:function(a,c){if(!b.util.isType(b.type.array,a))throw"jLinq can only query arrays of objects.";a=
c.clone||null==c.clone&&jLinq.alwaysClone?b.util.clone(a):a;var d={instance:{ignoreCase:jLinq.ignoreCase,not:!1,lastCommand:null,lastField:null,records:a,removed:[],or:function(){d.startNewCommandSet()},query:{}},canRepeatCommand:function(a){return null!=d.instance.lastCommand&&a.length==d.instance.lastCommand.method.length+1&&b.util.isType(b.type.string,a[0])},commands:[[]],execute:function(){var a=[],c=d.instance;b.util.each(d.instance.records,function(b){c.record=b;d.evaluate(c)?a.push(b):d.instance.removed.push(b)});
d.instance.records=a},findValue:b.util.findValue,evaluate:function(a){for(var b=0,c=d.commands.length;b<c;b++)if(d.evaluateSet(d.commands[b],a))return!0;return!1},evaluateSet:function(a,c){for(var e in a)if(a.hasOwnProperty(e)){var f=a[e];c.value=d.findValue(c.record,f.path);c.compare=function(a){return b.util.compare(c.value,a,c)};c.when=function(a){return b.util.when(c.value,a,c)};try{var g=f.method.apply(c,f.args);f.not&&(g=!g);if(!g)return!1}catch(l){return!1}}return!0},repeat:function(){d.instance.lastCommand&&
null!=arguments&&(arguments=b.util.toArray(arguments),d.canRepeatCommand(arguments)&&(d.instance.lastField=arguments[0],arguments=b.util.select(arguments,null,1,null)),d.queue(d.instance.lastCommand,arguments))},queue:function(a,c){d.instance.lastCommand=a;c={name:a.name,method:a.method,field:d.instance.lastField,count:a.method.length,args:c,not:d.not};c.args.length>a.method.length&&(c.field=c.args[0],c.args=b.util.remaining(c.args,1),d.instance.lastField=c.field);c.path=c.field;d.commands[d.commands.length-
1].push(c);d.not=!1},startNewCommandSet:function(){d.commands.push([])},setNot:function(){d.not=!d.not}};b.util.each(b.library.commands,function(a){if(a.type==b.command.query){var c=function(){d.queue(a,arguments);return d.instance.query};d.instance.query[a.name]=c;var e=b.util.operatorName(a.name);d.instance.query["or"+e]=function(){d.startNewCommandSet();return c.apply(null,arguments)};d.instance.query["orNot"+e]=function(){d.startNewCommandSet();d.setNot();return c.apply(null,arguments)};d.instance.query["and"+
e]=function(){return c.apply(null,arguments)};d.instance.query["andNot"+e]=function(){d.setNot();return c.apply(null,arguments)};d.instance.query["not"+e]=function(){d.setNot();return c.apply(null,arguments)}}else a.type==b.command.select?d.instance.query[a.name]=function(){d.execute();var c=d.instance;c.compare=function(a,d){return b.util.compare(a,d,c)};c.when=function(a,d){return b.util.when(a,d,c)};return a.method.apply(c,arguments)}:a.type==b.command.action&&(d.instance.query[a.name]=function(){var c=
d.instance;c.compare=function(a,d){return b.util.compare(a,d,c)};c.when=function(a,d){return b.util.when(a,d,c)};a.method.apply(c,arguments);return d.instance.query})});d.instance.query.or=function(){d.startNewCommandSet();d.repeat(arguments);return d.instance.query};d.instance.query.and=function(){d.repeat(arguments);return d.instance.query};d.instance.query.not=function(){d.setNot();d.repeat(arguments);return d.instance.query};d.instance.query.andNot=function(){d.setNot();d.repeat(arguments);return d.instance.query};
d.instance.query.orNot=function(){d.startNewCommandSet();d.setNot();d.repeat(arguments);return d.instance.query};return d.instance.query}},util:{trim:function(a){a=(null==a?"":a).toString();return a.replace(/^\s*|\s*$/g,"")},cloneArray:function(a){var c=[];b.util.each(a,function(a){c.push(b.util.clone(a))});return c},clone:function(a){if(b.util.isType(b.type.array,a))return b.util.cloneArray(a);if(b.util.isType(b.type.object,a)){var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b.util.clone(a[d]));
return c}return a},invoke:function(a,c){c=c.concat();var d=c[0],e=b.util.findValue(a,d);c=b.util.select(c,null,1,null);d=d.replace(/\..*$/,"");d=b.util.findValue(a,d);try{return e.apply(d===e?a:d,c)}catch(f){return null}},getPath:function(a){return b.util.toString(a).split(b.exp.get_path)},findValue:function(a,c){if(b.util.isType(b.type.array,c))return b.util.invoke(a,c);if(b.util.isType(b.type.string,c)){c=b.util.getPath(c);for(var d=0;null!=a&&d<c.length;)a=a[c[d++]]}return a},elementAt:function(a,
c){return a&&0<a.length&&c<a.length&&0<=c?a[c]:null},regexEscape:function(a){return(a?a:"").toString().replace(b.exp.escape_regex,"\\$&")},regexMatch:function(a,c,d){b.util.isType(b.type.regex,a)&&(a=a.source);a=new RegExp(b.util.toString(a),d?"gi":"g");return null!=b.util.toString(c).match(a)},operatorName:function(a){return a.replace(/^\w/,function(a){return a.toUpperCase()})},compare:function(a,c,d){a=b.util.when(a,c,d);return 1==a?a:!1},when:function(a,c,d){var e=b.util.getType(a),f;for(f in c)if(c.hasOwnProperty(f)&&
b.type[f]==e)return c[f].apply(d,[a]);return c.other?c.other.apply(d,[a]):null},each:function(a,c){var d=0,b;for(b in a)a.hasOwnProperty(b)&&c(a[b],d++)},grab:function(a,c){var d=[];b.util.each(a,function(a){d.push(c(a))});return d},until:function(a,c){for(var d=0,b=a.length;d<b;d++)if(!0===c(a[d],d+1))return!0;return!1},isType:function(a,c){return b.util.getType(c)==a},getType:function(a){if(null==a)return b.type.nothing;for(var c in b.library.types)if(b.library.types[c](a))return c;return b.type.object},
remaining:function(a,c){for(var d=[];c<a.length;c++)d.push(a[c]);return d},apply:function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d]);return a},reorder:function(a,c,d){return b.util._performSort(a,c,d)},_performSort:function(a,c,d){var e=c.splice(0,1);if(0==e.length)return a;var e=e[0],f=b.util.isType(b.type.array,e),h=f?e[0]:e,k=h.match(/^\-/),h=k?h.substr(1):h;k&&(f?e[0]=h:e=h);a.sort(function(a,c){a=b.util.findValue(a,e);c=b.util.findValue(c,e);null==a&&null==c?c=a=0:null==a&&null!=c?
(a=0,c=1):null!=a&&null==c?(a=1,c=0):d&&b.util.isType(b.type.string,a)&&b.util.isType(b.type.string,c)?(a=a.toLowerCase(),c=c.toLowerCase()):a.length&&c.length&&(a=a.length,c=c.length);c=a<c?-1:a>c?1:0;return k?-c:c});if(0<c.length){var g=[];a=b.util.group(a,e,d);b.util.each(a,function(a){var e=c.slice();a=b.util._performSort(a,e,d);g=g.concat(a)});a=g}return a},group:function(a,c,d){for(var e={},f=0,h=a.length;f<h;f++){var k=a[f],g=b.util.toString(b.util.findValue(k,c)),g=d?g.toUpperCase():g;e[g]?
e[g].push(k):e[g]=[k]}return e},equals:function(a,c,d){return b.util.when(a,{string:function(){return b.util.regexMatch("^"+b.util.regexEscape(c)+"$",a,d)},other:function(){return null==a&&null==c||a===c}})},toArray:function(a){var c=[];if(a.length)for(var d=0;d<a.length;d++)c.push(a[d]);else for(d in a)a.hasOwnProperty(d)&&c.push(a[d]);return c},toString:function(a){return null==a?"":a.toString()},skipTake:function(a,c,d,e){d=null==d?0:d;e=null==e?a.length:e;return d>=a.length||0==e?[]:b.util.select(a,
c,d,d+e)},select:function(a,c,d,b){b=null==b?a.length:b;a=a.slice(null==d?0:d,b);if(jLinq.util.isType(jLinq.type.object,c)){var e=c;c=function(a){var c={},b;for(b in e)e.hasOwnProperty(b)&&(c[b]=a[b]?a[b]:e[b]);return c}}if(jLinq.util.isType(jLinq.type.method,c))for(d=0;d<a.length;d++)b=a[d],a[d]=c.apply(b,[b]);return a}}};b.library.addType(b.type.nothing,function(a){return null==a});b.library.addType(b.type.array,function(a){return a instanceof Array});b.library.addType(b.type.string,function(a){return a.substr&&
a.toLowerCase});b.library.addType(b.type.number,function(a){return a.toFixed&&a.toExponential});b.library.addType(b.type.regex,function(a){return a instanceof RegExp});b.library.addType(b.type.bool,function(a){return 1==a||0==a});b.library.addType(b.type.method,function(a){return a instanceof Function});b.library.addType(b.type.datetime,function(a){return a instanceof Date});b.library.extend([{name:"ignoreCase",type:b.command.action,method:function(){this.ignoreCase=!0}},{name:"reverse",type:b.command.action,
method:function(){this.records.reverse()}},{name:"useCase",type:b.command.action,method:function(){this.ignoreCase=!1}},{name:"each",type:b.command.action,method:function(a){jLinq.util.each(this.records,function(c){a(c)})}},{name:"attach",type:b.command.action,method:function(a,c){this.when(c,{method:function(){jLinq.util.each(this.records,function(b){b[a]=c(b)})},other:function(){jLinq.util.each(this.records,function(b){b[a]=c})}})}},{name:"join",type:b.command.action,method:function(a,c,b,e){jLinq.util.each(this.records,
function(d){d[c]=jLinq.from(a).equals(e,d[b]).select()})}},{name:"assign",type:b.command.action,method:function(a,c,b,e,f){jLinq.util.each(this.records,function(d){d[c]=jLinq.from(a).equals(e,d[b]).first(f)})}},{name:"sort",type:b.command.action,method:function(){var a=jLinq.util.toArray(arguments);this.records=jLinq.util.reorder(this.records,a,this.ignoreCase)}},{name:"equals",type:b.command.query,method:function(a){return jLinq.util.equals(this.value,a,this.ignoreCase)}},{name:"starts",type:b.command.query,
method:function(a){return this.compare({array:function(){return jLinq.util.equals(this.value[0],a,this.ignoreCase)},other:function(){return jLinq.util.regexMatch("^"+jLinq.util.regexEscape(a),this.value,this.ignoreCase)}})}},{name:"ends",type:b.command.query,method:function(a){return this.compare({array:function(){return jLinq.util.equals(this.value[this.value.length-1],a,this.ignoreCase)},other:function(){return jLinq.util.regexMatch(jLinq.util.regexEscape(a)+"$",this.value,this.ignoreCase)}})}},
{name:"contains",type:b.command.query,method:function(a){return this.compare({array:function(){var c=this.ignoreCase;return jLinq.util.until(this.value,function(b){return jLinq.util.equals(b,a,c)})},other:function(){return jLinq.util.regexMatch(jLinq.util.regexEscape(a),this.value,this.ignoreCase)}})}},{name:"match",type:b.command.query,method:function(a){return this.compare({array:function(){var c=this.ignoreCase;return jLinq.util.until(this.value,function(b){return jLinq.util.regexMatch(a,b,c)})},
other:function(){return jLinq.util.regexMatch(a,this.value,this.ignoreCase)}})}},{name:"type",type:b.command.query,method:function(a){return jLinq.util.isType(a,this.value)}},{name:"greater",type:b.command.query,method:function(a){return this.compare({array:function(){return this.value.length>a},string:function(){return this.value.length>a},other:function(){return this.value>a}})}},{name:"greaterEquals",type:b.command.query,method:function(a){return this.compare({array:function(){return this.value.length>=
a},string:function(){return this.value.length>=a},other:function(){return this.value>=a}})}},{name:"less",type:b.command.query,method:function(a){return this.compare({array:function(){return this.value.length<a},string:function(){return this.value.length<a},other:function(){return this.value<a}})}},{name:"lessEquals",type:b.command.query,method:function(a){return this.compare({array:function(){return this.value.length<=a},string:function(){return this.value.length<=a},other:function(){return this.value<=
a}})}},{name:"between",type:b.command.query,method:function(a,c){return this.compare({array:function(){return this.value.length>a&&this.value.length<c},string:function(){return this.value.length>a&&this.value.length<c},other:function(){return this.value>a&&this.value<c}})}},{name:"betweenEquals",type:b.command.query,method:function(a,c){return this.compare({array:function(){return this.value.length>=a&&this.value.length<=c},string:function(){return this.value.length>=a&&this.value.length<=c},other:function(){return this.value>=
a&&this.value<=c}})}},{name:"empty",type:b.command.query,method:function(){return this.compare({array:function(){return 0==this.value.length},string:function(){return 0==jLinq.util.trim(this.value).length},other:function(){return null==this.value}})}},{name:"is",type:b.command.query,method:function(){return this.compare({bool:function(){return!0===this.value},other:function(){return null!=this.value}})}},{name:"min",type:b.command.select,method:function(a){a=jLinq.util.reorder(this.records,[a],this.ignoreCase);
return jLinq.util.elementAt(a,0)}},{name:"max",type:b.command.select,method:function(a){a=jLinq.util.reorder(this.records,[a],this.ignoreCase);return jLinq.util.elementAt(a,a.length-1)}},{name:"sum",type:b.command.select,method:function(a){var c;jLinq.util.each(this.records,function(b){b=jLinq.util.findValue(b,a);c=null==c?b:c+b});return c}},{name:"average",type:b.command.select,method:function(a){var b;jLinq.util.each(this.records,function(c){c=jLinq.util.findValue(c,a);b=null==b?c:b+c});return b/
this.records.length}},{name:"skip",type:b.command.select,method:function(a,b){this.records=this.when(b,{method:function(){return jLinq.util.skipTake(this.records,b,a,null)},object:function(){return jLinq.util.skipTake(this.records,b,a,null)},other:function(){return jLinq.util.skipTake(this.records,null,a,null)}});return this.query}},{name:"take",type:b.command.select,method:function(a,b){return this.when(b,{method:function(){return jLinq.util.skipTake(this.records,b,null,a)},object:function(){return jLinq.util.skipTake(this.records,
b,null,a)},other:function(){return jLinq.util.skipTake(this.records,null,null,a)}})}},{name:"skipTake",type:b.command.select,method:function(a,b,d){return this.when(d,{method:function(){return jLinq.util.skipTake(this.records,d,a,b)},object:function(){return jLinq.util.skipTake(this.records,d,a,b)},other:function(){return jLinq.util.skipTake(this.records,null,a,b)}})}},{name:"select",type:b.command.select,method:function(a){return this.when(a,{method:function(){return jLinq.util.select(this.records,
a)},object:function(){return jLinq.util.select(this.records,a)},other:function(){return this.records}})}},{name:"distinct",type:b.command.select,method:function(a){var b=jLinq.util.group(this.records,a,this.ignoreCase);return jLinq.util.grab(b,function(b){return jLinq.util.findValue(b[0],a)})}},{name:"group",type:b.command.select,method:function(a){return jLinq.util.group(this.records,a,this.ignoreCase)}},{name:"define",type:b.command.select,method:function(a){var b=this.when(a,{method:function(){return jLinq.util.select(this.records,
a)},object:function(){return jLinq.util.select(this.records,a)},other:function(){return this.records}});return jLinq.from(b)}},{name:"any",type:b.command.select,method:function(){return 0<this.records.length}},{name:"none",type:b.command.select,method:function(){return 0==this.records.length}},{name:"all",type:b.command.select,method:function(){return 0==this.removed.length}},{name:"first",type:b.command.select,method:function(a){var b=jLinq.util.elementAt(this.records,0);return null==b?a:b}},{name:"last",
type:b.command.select,method:function(a){var b=jLinq.util.elementAt(this.records,this.records.length-1);return null==b?a:b}},{name:"at",type:b.command.select,method:function(a,b){a=jLinq.util.elementAt(this.records,a);return null==a?b:a}},{name:"count",type:b.command.select,method:function(){return this.records.length}},{name:"removed",type:b.command.select,method:function(a){return this.when(a,{method:function(){return jLinq.util.select(this.removed,a)},object:function(){return jLinq.util.select(this.removed,
a)},other:function(){return this.removed}})}},{name:"where",type:b.command.select,method:function(a){var b=this,d=[];jLinq.util.each(this.records,function(c){!0===a.apply(b,[c])&&d.push(c)});var e=jLinq.from(d);this.ignoreCase||e.useCase();return e}}]);jl=jlinq=jLinq={alwaysClone:!1,ignoreCase:!0,command:b.command,type:b.type,extend:function(){b.library.extend.apply(null,arguments)},query:function(a,b){return library.framework.query(a,b)},from:function(a){return b.library.query(a,{clone:!1})},getCommands:function(){return b.util.grab(b.library.commands,
function(a){return{name:a.name,typeId:a.type,type:a.type==b.command.select?"select":a.type==b.command.query?"query":a.type==b.command.action?"action":"unknown"}})},util:{trim:b.util.trim,findValue:b.util.findValue,elementAt:b.util.elementAt,regexEscape:b.util.regexEscape,regexMatch:b.util.regexMatch,equals:b.util.equals,group:b.util.group,reorder:b.util.reorder,when:b.util.when,toArray:b.util.toArray,each:b.util.each,grab:b.util.grab,until:b.util.until,isType:b.util.isType,getType:b.util.getType,
apply:b.util.apply,select:b.util.select,skipTake:b.util.skipTake}}})();
