var ODoc=function(a){this.odoc={};isDefined(a)&&this.addAll(a)};ODoc.prototype.add=function(a,b,d){this.odoc[a]=compress({k:b,t:d})};ODoc.prototype.get=function(a){return uncompress(this.odoc[a])};ODoc.prototype.getKeys=function(){return Object.keys(this.odoc)};ODoc.prototype.getAll=function(){var a={},b;for(b in this.odoc)a[b]=uncompress(this.odoc[b]);return a};ODoc.prototype.addAll=function(a){for(var b in a)this.odoc[b]=compress(a[b])};
var ODocs=function(a,b,d,c){this.aodocs={};this.aodocskeys={};this.keyLoadFromWeb=this.loadFromWeb=!1;this.offline=c;this.keysfile="__odockeys";this.arrayurls=d;this.aFilename=isUndefined(a)?getOpenAFJar():a;try{this.load(),this.offline||this.backgroundLoadWeb()}catch(e){}isDefined(b)&&this.addAll(b)};ODocs.prototype.addAll=function(a){for(var b in a)this.aodocs[b]=new ODoc(a[b]),this.aodocskeys[b]=this.aodocs[b].getKeys()};
ODocs.prototype.save=function(){plugin("ZIP");var a=new ZIP,b={};try{a.loadFile(this.aFilename+"/.odoc.db"),b=af.fromJson(af.fromBytes2String(a.getFile(this.keysfile)))}catch(c){}for(var d in this.aodocs)a.putFile(d,af.fromString2Bytes(beautifier(this.aodocs[d].getAll()))),b[d]=this.aodocs[d].getKeys();a.putFile(this.keysfile,af.fromString2Bytes(beautifier(b)));io.writeFileBytes(this.aFilename+"/.odoc.db",a.generate({compressionLevel:9}));a.close()};
ODocs.prototype.saveWeb=function(){plugin("ZIP");var a=new ZIP;af.mkdir(this.aFilename);var b={};try{b=af.fromJson(a.gunzip(af.fromBytes2String(io.readFileBytes(this.aFilename+"/"+this.keysfile+".gz"))))}catch(c){}for(var d in this.aodocs)io.writeFileBytes(this.aFilename+"/"+d+".gz",a.gzip(af.fromString2Bytes(beautifier(this.aodocs[d].getAll())))),b[d]=this.aodocs[d].getKeys();io.writeFileBytes(this.aFilename+"/"+this.keysfile+".gz",a.gzip(af.fromString2Bytes(beautifier(b))))};
ODocs.prototype.loadWeb=function(a){function b(a){for(var b in d.arrayurls)try{var c=new HTTP(d.arrayurls[b]+"/"+a,"GET","",{},!0,500);if(isDefined(c))return c.responseBytes();break}catch(g){}return null}plugin("HTTP");var d=this;try{var c;this.keyLoadFromWeb=!1;c=b(this.keysfile+".gz");null!=c&&(this.aodocskeys=merge(af.fromJson(af.fromBytes2String(io.gunzip(c))),this.aodocskeys),this.keyLoadFromWeb=!0);c=b(a+".gz");if(null!=c){var e=af.fromJson(af.fromBytes2String(io.gunzip(c)));this.aodocs[a]=
new ODoc(e);return this.loadFromWeb=!0}return!1}catch(f){return this.loadFromWeb=!1}};
ODocs.prototype.load=function(a){plugin("ZIP");var b;this.aFilename.match(/\.(jar|db|zip)$/)?(b=new ZIP,b.loadFile(this.aFilename),b=new ZIP(b.getFile(".odoc.db"))):(b=new ZIP,b.loadFile(this.aFilename+"/.odoc.db"));this.offline&&(this.keyLoadFromWeb=!1);var d=b.list(),c;for(c in d)if(c==this.keysfile){var e=b.getFile(c);1<e.length&&(this.aodocskeys=merge(af.fromJson(af.fromBytes2String(e)),this.aodocskeys))}else if(c==a){var e=d[c].name,f=af.fromJson(af.fromBytes2String(b.getFile(e)));this.aodocs[e]=
new ODoc(f)}b.close()};ODocs.prototype.search=function(a,b){b=isUndefined(b)?Object.keys(this.aodocskeys):b;var d=[],c;for(c in this.aodocskeys)if(0<=b.indexOf(c)){var e=$from(this.aodocskeys[c]).equals(a);if(e.any())return a=$from(this.aodocskeys[c]).useCase().equals(a),1==a.count()?a.select(function(a){return{id:c,key:a}}):e.select(function(a){return{id:c,key:a}});e=$from(this.aodocskeys[c]).contains(a).select(function(a){return{id:c,key:a}});d=d.concat(e)}return d};
ODocs.prototype.backgroundLoadWeb=function(a){var b=this;plugin("Threads");var d=new Threads;d.addThread(function(c){b.loadWeb(a);d.stop(!0)});d.startNoWait()};ODocs.prototype.get=function(a,b){this.aodocs={};if(isUndefined(this.aodocskeys)||this.aodocskeys=={}||isUndefined(this.aodocs[a]))this.load(a),this.offline||this.backgroundLoadWeb(a);return this.aodocs[a].get(b)};ODocs.prototype.getODoc=function(a){return this.aodocs[a]};var ODocsGen=function(a){this.aMapOfFiles=a;this.odoc={};this.genODocs()};
ODocsGen.prototype.genODoc=function(a){a=io.readFileString(a).replace(/\r/mg,"").replace(/\\\n/mg,"%%br%%").replace(/([\n|%%br%%])[ |\t]+\*+[ |\t]/mg,"$1").replace(/\n+/mg," ").match(/\<odoc\>.+?\<\/odoc\>/img);var b=new ODoc,d;for(d in a){var c=new XMLList(a[d]),e=(c.key+"").replace(/\%\%br\%\%/g,"");b.add(e.replace(/[\(|\{|\[|\:].+/,""),c.key+"",(c.text()+"").replace(/\%\%br\%\%/g,"\n"))}return b};
ODocsGen.prototype.genODocs=function(){for(var a in this.aMapOfFiles)log("Generating odoc for "+a),this.odoc[a]=this.genODoc(this.aMapOfFiles[a])};ODocsGen.prototype.getODoc=function(){var a=clone(this.odoc),b;for(b in this.odoc)a[b]=a[b].getAll();return a};ODocsGen.prototype.getODocKeys=function(){var a={},b;for(b in this.odoc)a[b]=this.odoc[b].getKeys();return a};
