var params=processExpr(" "),ojob_shouldRun=!0,ojob_args={};1==Object.keys(params).length&&""==Object.keys(params)[0]&&ojob_showHelp();isDef(params["-h"])&&""==params["-h"]&&(delete params["-h"],ojob_showHelp());isDef(params["-compile"])&&""==params["-compile"]&&(delete params["-compile"],ojob_compile());isDef(params["-tojson"])&&""==params["-tojson"]&&(delete params["-tojson"],ojob_tojson());isDef(params["-jobs"])&&""==params["-jobs"]&&(delete params["-jobs"],ojob_jobs());
isDef(params["-todo"])&&""==params["-todo"]&&(delete params["-todo"],ojob_todo());isDef(params["-deps"])&&""==params["-deps"]&&(delete params["-deps"],ojob_draw());isDef(params["-jobhelp"])&&""==params["-jobhelp"]&&(delete params["-jobhelp"],ojob_jobhelp());1<=Object.keys(params).length&&ojob_shouldRun&&ojob_runFile();
function ojob_showHelp(){print("Usage: ojob aYamlFile.yaml [options]\n");print("  -compile       Compile all includes and current file into a single yaml output.");print("  -tojson        Outputs all includes and current fiel into a single json output.");print("  -jobs          List all jobs available.");print("  -todo          List the final todo list.");print("  -deps          Draws a list of dependencies of todo jobs on a file.");print("  -jobhelp (job) Display any available help information for a job.");
print("");print("(version "+af.getVersion()+", "+Packages.wedo.openaf.AFCmdBase.LICENSE+")");ojob_shouldRun=!1}function ojob__getFile(){var a=Object.keys(params);if(1<=a.length)return a=a[0],delete params[a],a;printErr("Didn't recognize the aYamlFile.yaml\n");ojob_showHelp()}function ojob_compile(){var a=ojob__getFile();isDef(a)&&print(af.toYAML(ow.loadOJob().previewFile(a)));ojob_shouldRun=!1}
function ojob_tojson(){var a=ojob__getFile();isDef(a)&&sprint(ow.loadOJob().previewFile(a));ojob_shouldRun=!1}function ojob_jobs(){var a=ojob__getFile();isDef(a)&&print(af.toYAML($stream(ow.loadOJob().previewFile(a).jobs).map("name").toArray().sort()));ojob_shouldRun=!1}
function ojob_draw(){function a(b){b=$from(f.jobs).equals("name",b).first();if(!isUnDef(b))return isDef(b.deps)?b.deps:[]}function c(b,a){b=$from(f.jobs).equals("name",b).first();isUnDef(a)&&(a={from:[],to:[]});if(isUnDef(b))return a;a={to:a.to.concat(b.to),from:(isDef(b.from)?[b.from]:[]).concat(a.from)};var g=c(b.from);a.from=g.from.concat(a.from.concat(g.to));b=c(b.to);a.to=b.from.concat(a.to.concat(b.to));return a}function d(b){var c="";b=a(b);if(isUnDef(b))c+="!!NOT FOUND!!";else for(var h in b){var c=
c+(" :"+b[h]),e=d(b[h]);0<e.length&&(c+=" ("+e+")")}return c}var k=ojob__getFile();ow.loadOJob();var f=ow.oJob.previewFile(k);f.ojob.sequential&&print("Sequential dependencies are enabled.\n");ansiStart();print(ansiColor("bold,underline","\nDependencies:"));$from(f.todo).select(function(b){b=isDef(b.name)?b.name:b;printnl("["+ansiColor("bold",b)+"]");a(b);print(d(b))});print(ansiColor("bold,underline","\nPaths:"));$from(f.todo).select(function(a){a=isDef(a.name)?a.name:a;var b=c(a),d="",e;for(e in b.from)d+=
isDef(b.from[e])?b.from[e]+" -> ":"";d+="["+ansiColor("bold",a)+"]";for(e in b.to)d+=isDef(b.to[e])?" -> "+b.to[e]:"";print(d)});ansiStop();ojob_shouldRun=!1}
function ojob_jobhelp(){var a=ojob__getFile(),c=Object.keys(params);if(1<=c.length){c=c[0];delete params[c];if(isDef(a))if(a=$from(ow.loadOJob().previewFile(a).jobs).equals("name",c).select({name:"n/a",help:"n/a"})[0],isDef(a))print(a.name),print(repeat(a.name.length,"-")),print(""),print(a.help);else{printErr("Didn't find job help for '"+c+"'.");return}ojob_shouldRun=!1}else printErr("Didn't recognize the job to try to obtain help from.\n"),ojob_showHelp()}
function ojob_todo(){var a=ojob__getFile();if(isDef(a)){var a=ow.loadOJob().previewFile(a).todo,c=[],d;for(d in a)isObject(a[d])?c.push(a[d].name):c.push(a[d]);print(af.toYAML(c))}ojob_shouldRun=!1}function ojob_runFile(){if(ojob_shouldRun){var a=ojob__getFile();__expr=$from(params).select(function(a){var c=Object.keys(a)[0];return c+"="+a[c]}).join(" ");isDef(a)&&oJobRunFile(a,ojob_args)}};
