plugin("Console");var __ansiflag=!0,__pinflag=!1,__pinprefix="",CONSOLESEPARATOR="-- ",CONSOLEHISTORY=".openaf-console_history",CONSOLEPROFILE=".openaf-console_profile",RESERVEDWORDS="help|exit|time|output|beautify|desc|scope|alias|watch|clear|purge|pause|sql|esql|dsql|pin",__alias={opack:'__expr=__aliasparam;load(getOpenAFJar() + "::js/opack.js");'},__aliasparam,__message="",__afDBs={};
function __desc(a,b,c){var d=[],f=[],e=!1,g,l=!1,h=[];a=a.replace(/^Packages\./,"");try{g=java.lang.Class.forName(a),d=g.getMethods(),f=g.getConstructors()}catch(n){try{g=java.lang.Class.forName("wedo.openaf."+a),d=g.getMethods(),f=g.getConstructors()}catch(w){try{g=java.lang.Class.forName("wedo.openaf.plugins."+a),d=g.getMethods(),f=g.getConstructors()}catch(y){try{"[object JavaObject]"===Object.prototype.toString.call(af.eval(a))?(g=af.eval(a+".getClass()"),d=g.getMethods(),f=g.getConstructors()):
e=!0}catch(z){e=!0}}}}if(e){d=[];if(a.match(/ *JSON */))return h;try{f=function(a){a=a.toString().replace(t,"");a=a.slice(a.indexOf("(")+1,a.indexOf(")")).match(u);null===a&&(a=[]);return a};if("function"!==typeof af.eval(a)){if("[object Array]"===Object.prototype.toString.call(af.eval(a)))b||__outputConsoleComments("ARRAY: #"+af.eval(a+".length")+" entries");else{if("object"!==typeof af.eval(a))return b||"undefined"!=typeof af.eval(a)&&__outputConsoleComments("TYPE: "+typeof af.eval(a)),h;var v=
Object.prototype.toString.call(af.eval(a)).replace(/\[object ([a-zA-Z0-9_]+)\]/,"$1"),p=Object.keys(af.eval(a)).sort();for(k in p)h.push(p[k]),b||__outputConsoleComments("KEY: "+p[k]);if("Object"==v&&!a.match(/\.constructor$/)&&!c){var r=__desc(a+".constructor",b,!0),h=h.concat(r);if(1>r.length){var m=af.getScopeIds(),k;for(k in m)try{eval(m[k]+" instanceof Object")&&eval(a+" instanceof "+m[k])&&(h=h.concat(__desc(String(m[k]),b,!0)))}catch(n){}}}}a.match(/\.constructor$/)||c||(h=h.concat(__desc(af.eval(a+
".constructor.name"),b,!0)));return h}var d=[],d=d.concat(Object.keys(af.eval(a+".prototype")).sort()),t=/((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg,u=/([^\s,]+)/g;for(k in d)if("constructor"!==d[k]&&h.push(d[k]),b||(__outputConsoleCommentsNoEnd(CONSOLESEPARATOR+"FUNC: "+d[k]),__outputConsoleCommentsNoEnd("(")),!b){var q=f(af.eval(a+".prototype."+d[k]));c=!0;for(x in q)!c&&x<q.length?__outputConsoleCommentsNoEnd(", "):c=!1,__outputConsoleNoEnd(q[x]);__outputConsoleCommentsEnd(")")}}catch(n){}}else{a=function(a,
c){for(var d in a.sort(function(a,b){return a.getName()<b.getName()?-1:a.getName()>b.getName()?1:0})){var e=a[d];if(l&&(e.getAnnotation(Packages.org.mozilla.javascript.annotations.JSFunction)||e.getAnnotation(Packages.org.mozilla.javascript.annotations.JSConstructor))||!l)if(b?h.push(e.getName()+""):(__outputConsoleCommentsNoEnd(CONSOLESEPARATOR+e.getName()),__outputConsoleCommentsNoEnd("(")),!b){var f=e.getParameterTypes(),g=!0;for(x in f)!g&&x<f.length?__outputConsoleCommentsNoEnd(", "):g=!1,__outputConsoleNoEnd((f[x].getCanonicalName()+
"").replace(/^.*\./,""));__outputConsoleCommentsNoEnd(")");c&&"void"!=e.getReturnType().getCanonicalName()&&__outputConsoleNoEnd(" : "+(e.getReturnType().getCanonicalName()+"").replace(/^.*\./,""));__outputConsoleCommentsEnd("")}}};try{g.asSubclass(Packages.org.mozilla.javascript.ScriptableObject)&&(l=!0)}catch(n){l=!1}a(f,!1);a(d,!0)}return h}
function __scope(a,b){var c=af.getScopeIds(),d=[];for(i in c.sort())0<a.length&&!c[i].match(new RegExp(a,"i"))||(b?d.push(c[i]):__outputConsoleComments(c[i]));return d}
function __sql(a,b,c,d){var f=a.match(/^([^ ]+) +(.*)/,""),e;if(isUndefined(f[1]))__outputConsoleError("Needs to be a DB object followed by a SQL statement");else if(e=af.eval(f[1]),"[object DB]"!=Object.prototype.toString.call(e))__outputConsoleError("Needs to be a DB object followed by a SQL statement");else{a="";var g;timeCommand&&(g=now());if(b)b=e.u(f[2]),d?a+="Executed over #"+b+" lines.":__outputConsoleComments("Executed over #"+b+" lines.");else if(b=f[2],b=b.replace(/\;\s*/,""),c){b=e.qsRS(b);
timeCommand&&(__timeResult=now()-g);for(c=1;c<=b.getMetaData().getColumnCount();c++)a+=b.getMetaData().getColumnName(c)+": "+b.getMetaData().getColumnTypeName(c)+"("+b.getMetaData().getColumnDisplaySize(c)+(0<b.getMetaData().getScale(c)?","+b.getMetaData().getScale(c):"")+")\n";if(!d)for(d=0,c=String(a).replace(/\"/g,"").replace(/([^\\])\\n/g,"$1\n").split(/\n/);0<=d;)d=__pauseArray(c,d);b.close()}else if(b=e.q(b),timeCommand&&(__timeResult=now()-g),0<b.results.length){if(c||(a=printTable(b.results,
con.getConsoleReader().getTerminal().getWidth(),d)),!d){d=0;for(c=String(a).replace(/\"/g,"").replace(/([^\\])\\n/g,"$1\n").split(/\n/);0<=d;)d=__pauseArray(c,d);__outputConsoleComments(b.results.length+" rows selected.")}}else d?a+="No results.":__outputConsoleComments("No results.");timeCommand&&__time(__timeResult);return a}}function __pin(a){__pinflag?(__pinflag=!1,__pinprefix=""):(__pinflag=!0,__pinprefix=a)}var __timeResult;
function __time(a,b){isUndefined(a)?(isDefined(b)&&b.match(/off|0/i)&&(timeCommand=!1),isDefined(b)&&b.match(/on|1/i)&&(timeCommand=!0),""==b&&(timeCommand=timeCommand?!1:!0),timeCommand?__outputConsoleComments("Timing of commands is enabled."):__outputConsoleComments("Timing of commands is disabled.")):timeCommand&&__outputConsoleComments("Elapsed time: "+a/1E3+"s")}
function __output(a){a.match(/off|0/i)&&(outputCommand=!1);a.match(/on|1/i)&&(outputCommand=!0);""==a&&(outputCommand=outputCommand?!1:!0);outputCommand?__outputConsoleComments("Output of commands is enabled."):__outputConsoleComments("Output of commands is disabled.")}
function __beautify(a){a.match(/off|0/i)&&(beautifyCommand=!1);a.match(/on|1/i)&&(beautifyCommand=!0);""==a&&(beautifyCommand=beautifyCommand?!1:!0);beautifyCommand?__outputConsoleComments("Output beautify of commands is enabled."):__outputConsoleComments("Output beautify of commands is disabled.")}
function __watch(a){if(a.match(/^off$|^0$/i))watchCommand=!1;else if(a.match(/^on$|^1$/i))watchCommand=!0;else if(""==a)watchCommand?__outputConsoleComments("Watch is active."):__outputConsoleComments("Watch is not active.");else if(a.match(/^[0-9]+ .+/)){var b=Number(a.match(/^([0-9]+) /)[1]),c=a.match(/ (.+)/)[1];a=-2;plugin("Threads");var d=new Threads;d.addThread(function(){var a="";try{a=__processCmdLine(c,!0)}catch(g){a=g.message}isDefined(a)&&beautifyCommand&&(a=String(stringify(a)).replace(/\\t/g,
"\t").replace(/([^\\])\\n/g,"$1\n").replace(/\\r/g,"\r"));__clear();__outputConsole(a);__outputConsoleCommentsEnd("Press 'q' to quit. (refreshed at "+new Date+")")});try{for(d.startWithFixedRate(b);3!=a&&113!=a;){sleep(500);var f=Number(con.readCharNB());0<f&&(a=f)}d.stop();__clear()}catch(e){printErr(e.message),d.stop(!0)}}else watchLine=a,watchCommand=!0,__outputConsoleComments("Watch is active for '"+watchLine+"'")}
function addAlias(a){if(a.match(/\=/))if(0<=RESERVEDWORDS.split(/\|/).indexOf(a.replace(/\=.*/,"")))__outputConsoleError("Can't assign an alias to a reserved word.");else{var b=a.replace(/^([a-zA-Z0-9_]+)=(.+)/,"$1");a=a.replace(/^([a-zA-Z0-9_]+)=(.+)/,"$2");__alias[b]=a}else for(b in __alias)"preto"!=b&&"decrypt"!=b&&(__outputConsoleCommentsNoEnd(b+": "),__outputConsoleEnd(__alias[b]))}
function __help(a){if(isUndefined(a)||0>=a.length)__outputConsoleComments("help     Display this help text"),__outputConsoleComments("exit     Exit this console"),__outputConsoleComments("time     Turns on or off the timing of any script command provided (default off)"),__outputConsoleComments("output   Turns on or off the output of commands (default on)"),__outputConsoleComments("beautify Turns on or off the beautify of output (default on)"),__outputConsoleComments("desc     Provides a description of the available methods for a class (example 'desc AF')"),
__outputConsoleComments("scope    Lists the current OpenAF javascript scope loaded filtered by a regexp (example 'scope sha')"),__outputConsoleComments("alias    Create an alias for an openaf-console command line (example 'alias ola=print(\"hi\");')"),__outputConsoleComments("watch    Turns on or off an execution before every console prompt (example 'watch new Date();')"),__outputConsoleComments("pause    Pauses the output of a command if bigger than the terminal height (default off)"),__outputConsoleComments("sql      Executes a SQL query, over a db connection, displaying the result in a table (example 'sql adm select...')"),
__outputConsoleComments("dsql     Returns the list of columns produced by a SQL query over a db connection."),__outputConsoleComments("esql     Executes the SQL statement, over a db connection (example 'esql db update...')"),__outputConsoleComments("pin      Pins the next command as a prefix for the next commands until an empty command (example 'pin sql db...')"),__outputConsoleComments("clear    Tries to clear the screen."),__outputConsoleComments("purge    Purge all the command history"),__outputConsoleComments("[others] Executed as a OpenAF script command (example 'print(\"ADEUS!!!\");')");
else{var b;b="scope"==a?searchHelp("",void 0,["scope"]):searchHelp(a);if(1==b.length)__outputConsoleComments(b[0].fullkey),__outputConsoleComments(repeat(b[0].fullkey.length,"-")),__outputConsoleComments(b[0].text);else if(1<b.length)for(var c in b)__outputConsoleComments(b[c].key);else __outputConsoleComments("Term '"+a+"' not found.")}}function __outputConsole(a){__outputConsoleEnd(a)}
function __outputConsoleNoEnd(a){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag?(jansi.AnsiConsole.systemInstall(),printnl(jansi.Ansi.ansi().boldOff().fg(jansi.Ansi.Color.CYAN).a(a).a(jansi.Ansi.Attribute.RESET)),jansi.AnsiConsole.systemUninstall()):printnl(a)}
function __outputConsoleEnd(a){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag?(jansi.AnsiConsole.systemInstall(),print(jansi.Ansi.ansi().boldOff().fg(jansi.Ansi.Color.CYAN).a(a).a(jansi.Ansi.Attribute.RESET)),jansi.AnsiConsole.systemUninstall()):print(a)}function __outputConsoleComments(a){__outputConsoleCommentsEnd(CONSOLESEPARATOR+a)}
function __outputConsoleCommentsNoEnd(a){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag?(jansi.AnsiConsole.systemInstall(),printnl(jansi.Ansi.ansi().bold().a(a).a(jansi.Ansi.Attribute.RESET)),jansi.AnsiConsole.systemUninstall()):printnl(a)}
function __outputConsoleCommentsEnd(a){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag?(jansi.AnsiConsole.systemInstall(),print(jansi.Ansi.ansi().bold().a(a).a(jansi.Ansi.Attribute.RESET)),jansi.AnsiConsole.systemUninstall()):print(a)}
function __outputConsoleError(a){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag?(jansi.AnsiConsole.systemInstall(),printErr(jansi.Ansi.ansi().boldOff().fg(jansi.Ansi.Color.RED).a(CONSOLESEPARATOR+a).a(jansi.Ansi.Attribute.RESET)),jansi.AnsiConsole.systemUninstall()):printErr(CONSOLESEPARATOR+a)}
function __clear(){con.getConsoleReader().getTerminal().isAnsiSupported()&&__ansiflag&&(jansi.AnsiConsole.systemInstall(),printnl(jansi.Ansi.ansi().eraseScreen().cursor(0,0).reset()),jansi.AnsiConsole.systemUninstall())}
function __readProfile(a){var b="";try{b=af.readFileString(a),b=b.replace(/^([a-zA-Z0-9_]+)( +|$)(.*)/mg,function(a,b,f,e){return b.match(RESERVEDWORDS)?(a=e.replace(/"/g,'\\"'),'__showResultProcessCmdLine(__processCmdLine("'+b+" "+a+'"));'):a}),af.compile(b)}catch(c){if(!c.message.match(/java\.io\.FileNotFoundException/))throw c;}}
function __pause(a){a.match(/off|0/i)&&(pauseCommand=!1);a.match(/on|1/i)&&(pauseCommand=!0);""==a&&(pauseCommand=pauseCommand?!1:!0);pauseCommand?__outputConsoleComments("Pause of output is enabled."):__outputConsoleComments("Pause of output is disabled.")}
function __processCmdLine(a,b){var c=!1;a=a.replace(/^ *([^ ].*)/,"$1");try{if("exit"!=a){isUndefined(__alias[a.replace(/^([^ ]+).*/,"$1")])||(__aliasparam=a.replace(/^[^ ]+ */,""),isUndefined(__aliasparam)&&(__aliasparam=""),a=__alias[a.replace(/^([^ ]+).*/,"$1")]);a.match(/^alias(?: +|$)/)&&(c=!0,addAlias(a.replace(/^alias */,"")));a.match(/^desc(?: +|$)/)&&(c=!0,__desc(a.replace(/^desc */,""),!1));a.match(/^help(?: +|$)/)&&(c=!0,__help(a.replace(/^help */,""),!1));if(a.match(/^sql(?: +|$)/)){var c=
!0,d=__sql(a.replace(/^sql */,""),!1,!1,b);if(b)return d}if(a.match(/^esql(?: +|$)/)&&(c=!0,d=__sql(a.replace(/^esql */,""),!0,!1,b),b)||a.match(/^dsql(?: +|$)/)&&(c=!0,d=__sql(a.replace(/^dsql */,""),!1,!0,b),b))return d;a.match(/^scope(?: +|$)/)&&(c=!0,__scope(a.replace(/^scope */,""),!1));a.match(/^time(?: +|$)/)&&(c=!0,__time(void 0,a.replace(/^time */,"")));a.match(/^output(?: +|$)/)&&(c=!0,__output(a.replace(/^output */,"")));a.match(/^beautify(?: +|$)/)&&(c=!0,__beautify(a.replace(/^beautify */,
"")));a.match(/^watch(?: +|$)/)&&(c=!0,__watch(a.replace(/^watch */,"")));a.match(/^purge(?: +|$)/)&&(c=!0,jLineFileHistory.purge());a.match(/^clear(?: +|$)/)&&(c=!0,__clear());a.match(/^pause(?: +|$)/)&&(c=!0,__pause(a.replace(/^pause */,"")));a.match(/^pin(?: +|$)/)&&(c=!0,__pin(a.replace(/^pin */,"")));var f;if(!c&&(timeCommand?(__start=now(),f=af.eval(a),__end=now(),__timeResult=__end-__start):f=af.eval(a),outputCommand&&"undefined"!==typeof f))return f}}catch(e){__outputConsoleError(e.message)}}
function __showResultProcessCmdLine(a,b){if(isDefined(a))if(pauseCommand){var c=0;for(__lines=beautifyCommand?String(stringify(a)).replace(/\\t/g,"\t").replace(/\\r/g,"\r").replace(/([^\\])\\n/g,"$1\n").split(/\n/):String(a).replace(/\"/g,"").replace(/([^\\])\\n/g,"$1\n").split(/\n/);0<=c;)c=__pauseArray(__lines,c)}else beautifyCommand?__outputConsole(String(stringify(a)).replace(/\\t/g,"\t").replace(/([^\\])\\n/g,"$1\n").replace(/\\r/g,"\r")):__outputConsole(a);timeCommand&&!b.match(/^time(?: +|$)/)&&
__time(__timeResult)}function __checkVersion(){var a=new Threads;a.addThread(function(){var b=checkLatestVersion(),c=getVersion();-1!=b&&b>c&&(__message="There is a new OpenAF version available: "+b+". Run 'openaf --update' to update.");a.stop(!0)});a.startNoWait()}
function __pauseArray(a,b){var c=con.getConsoleReader().getTerminal().getHeight(),d=a.length;if(d<=c)return __outputConsole(a.join("\n")),-1;isUndefined(b)||0>b?b=0:b>d-c+1&&(b=d-c+1);__outputConsole(a.slice(b,b+c-1).join("\n"));if(b+c-1<d-2){__outputConsoleCommentsNoEnd(Math.floor(100*(b+c-1)/d)+"% (Press any key to continue or 'q' to quit)");a=con.readChar("")+"";__outputConsoleCommentsNoEnd("\r"+repeat(con.getConsoleReader().getTerminal().getWidth()," ")+"\r");if(113!=a.charCodeAt(0)&&81!=a.charCodeAt(0)){if(27==
a.charCodeAt(0)&&(a=con.readChar("")+"",a.charCodeAt(0),91==a.charCodeAt(0))){a=con.readChar("")+"";if(49==a.charCodeAt(0)&&(a=con.readChar("")+"",126==a.charCodeAt(0)))return 0;if(52==a.charCodeAt(0)&&(a=con.readChar("")+"",126==a.charCodeAt(0)))return d-c+1;if(53==a.charCodeAt(0)&&(a=con.readChar("")+"",126==a.charCodeAt(0)))return 0>b-c-1?0:b-c+1;if(54==a.charCodeAt(0)&&(a=con.readChar("")+"",126==a.charCodeAt(0)))return b+c+1;if(65==a.charCodeAt(0))return 0>b-1?0:b-1;if(66==a.charCodeAt(0))return b+
1}return b+c+1}return-1}}function __pauseString(a){var b=0;for(a=a.split(/\n/);0<=b;)b=__pauseArray(a,b)}var con=new Console,jansi=JavaImporter(Packages.org.fusesource.jansi),cmd="",timeCommand=!1,start,end,outputCommand=!0,beautifyCommand=!0,pauseCommand=!1,watchCommand=!1,watchLine="";con.getConsoleReader().setHistoryEnabled(!0);con.getConsoleReader().setExpandEvents(!1);__outputConsoleComments("OpenAF console (OpenAF version "+getVersion()+") (type help for commands)");var historyFile,jLineFileHistory;
plugin("Threads");var initThread=new Threads;
initThread.addThread(function(a){historyFile=java.lang.System.getProperty("user.home")+"/"+CONSOLEHISTORY;jLineFileHistory=new Packages.jline.console.history.FileHistory(new java.io.File(historyFile));con.getConsoleReader().setHistory(jLineFileHistory);con.getConsoleReader().addCompleter(new Packages.wedo.openaf.jline.OpenAFConsoleCompleter(function(a,c,d){if(null==a)return null;var b=0;if(a.substr(0,c).match(/(([a-zA-Z0-9_\[\]\(\)\"\']+\.)+)([a-zA-Z0-9_\[\]\(\)\"\']*)$/)){a=a.substr(0,c).match(/(([a-zA-Z0-9_\[\]\(\)\"\']+\.)+)([a-zA-Z0-9_\[\]\(\)\"\']*)$/);
b=c-a[3].length;a[1]=a[1].replace(/\.$/,"");a[3]=a[3].replace(/\.$/,"");try{var e=__desc(a[1].replace(/.+[\[\(\"\']([^\]\)]+)$/,"$1"),!0);for(elem in e)0==e[elem].indexOf(a[3])&&d.add(e[elem])}catch(g){logErr(g)}}else if(a.substr(0,c).match(/[^a-zA-Z0-9_\[\]\(\)\"\']*[a-zA-Z0-9_\[\]\(\)\"\']+$/)){a=a.substr(0,c).match(/[^a-zA-Z0-9_\[\]\(\)\"\']*([a-zA-Z0-9_\[\]\(\)\"\']+)$/);b=c-a[1].length;try{for(elem in e=__scope(a[1],!0),e)0==e[elem].indexOf(a[1])&&d.add(e[elem])}catch(g){}}return b+0}));__readProfile(java.lang.System.getProperty("user.home")+
"/"+CONSOLEPROFILE);noHomeComms||__checkVersion();initThread.stop()});initThread.startNoWait();
for(0<__expr.length&&(cmd=__expr);"exit"!=cmd;){__showResultProcessCmdLine(__processCmdLine(cmd),cmd);""!=__message&&(__outputConsoleComments(__message),__message="");if(watchCommand){var watchresult;try{watchresult=__processCmdLine(watchLine,!0),isUndefined(watchresult)&&(watchresult=""),beautifyCommand&&(watchresult=String(stringify(watchresult)).replace(/\\t/g,"\t").replace(/([^\\])\\n/g,"$1\n").replace(/\\r/g,"\r"))}catch(a){watchresult="ERROR: "+a.message,watchCommand=!1}cmd=con.readLinePrompt("[ "+
watchresult+" ]\n"+__pinprefix+"> ")}else cmd=con.readLinePrompt(__pinprefix+"> ");""==cmd?(__pinflag=!1,__pinprefix=""):__pinflag&&(cmd=__pinprefix+" "+cmd);isDefined(jLineFileHistory)&&jLineFileHistory.flush()}exit(0);
