log("Starting OpenAF GUI");ow.loadServer();ow.loadTemplate();var installed=!1,needupdate=!1,updateversion="",keepRunning=!0;ow.server.checkIn(java.lang.System.getProperty("user.home")+"/.openaf.pid",function(a){log("Killing previous "+ow.server.getPid(a));pidKill(ow.server.getPid(a),!0);return!0},function(){log("OpenAF GUI shutdown")});
function verifyIfInstalled(){var a=!1,c=!1;try{io.readFileString(getOpenAFPath()+"/openaf"),c=!0}catch(b){c=!1}try{io.readFileString(getOpenAFPath()+"/openaf.bat"),a=!0}catch(b){a=!1}installed=a||c;return a||c}function checkRemoteVersions(){if(!noHomeComms){log("Checking for new versions remotely...");var a=checkLatestVersion(),c=getVersion();-1!=a&&a>c&&(updateversion=a,needupdate=!0,log("New version "+a+" (running version is "+c))}}
var port=findRandomOpenPort(),httpServer=ow.server.httpd.start(port,"127.0.0.1",void 0,void 0,function(a,c,b){"DEBUG"!=a.toString()&&"Broken pipe"!=b.getMessage()&&logErr("Type: "+a+" | Message: "+c+b.printStackTrace())});httpServer.add("/wait",function(a){return httpServer.replyOKHTML('<html><meta http-equiv="refresh" content="1; url="/><body>Loading...</body></html>')});httpServer.setDefault("/wait");plugin("Threads");var initThread=new Threads;
initThread.addThread(function(a){checkRemoteVersions();initThread.stop()});initThread.startNoWait();java.awt.Desktop.getDesktop().browse(new java.net.URI("http://127.0.0.1:"+port));
var templates=ow.template.loadHBSs({index:getOpenAFJar()+"::hbs/index.hbs",opacks:getOpenAFJar()+"::hbs/opacks.hbs",odoc:getOpenAFJar()+"::hbs/odoc.hbs"}),defaultPage={title:"OpenAF",logo:{text:"OpenAF",link:"/"},served:{text:"OpenAF (version "+getVersion()+")",link:"http://172.25.1.32/OpenAF"},navbar:[{text:"openaf-Console",link:"/exec/openaf-console"},{text:"Documentation",link:"/odoc"},{text:"oPacks",link:"/opack"}],contents:'<p class="thin">Welcome to OpenAF.<br><br>'+(verifyIfInstalled()?"(version "+
getVersion()+" installed in "+getOpenAFPath()+")<br>"+(needupdate?"<br>There is a new version "+updateversion+'. Do you wish to update this version? &nbsp;&nbsp;<p class="regular"><a class="waves-effect waves-light orange regular btn" href="/exec/update"><i class="material-icons left">play_for_work</i>Update</a>':""):'Do you want to install OpenAF? &nbsp;&nbsp;<p class="regular"><a class="waves-effect waves-light orange regular btn" href="/exec/install"><i class="material-icons left">play_for_work</i>Install</a></p><span class="thin">(install will create scripts in '+
getOpenAFPath()+" to make it easier to use OpenAF).</span>")+'</p><p/><hr/><div class="thin flow-text" style="font-family: monospace; font-size: 8pt">'+String(Packages.wedo.openaf.AFCmdOS.argHelp).replace(/\n/g,"<br>").replace(/ /g,"&nbsp;")+"</div>"},paths=Object.keys(getOPackLocalDB());searchHelp("");for(var i in paths)searchHelp("",paths[i]);
ow.server.httpd.route(httpServer,ow.server.httpd.mapRoutesWithLibs(httpServer,{"/exec":function(a){var c=String((new java.io.File(java.lang.System.getProperty("java.home"))).getAbsolutePath())+"/bin/java",c=c.replace(/\\/g,"/");switch(a.uri){case "/exec/openaf-console":try{0<=java.lang.System.getProperty("os.name").toLowerCase().indexOf("mac")&&(sh('echo "'+c+" -jar "+getOpenAFJar()+' --console" > ~/.openafconsole'),sh("chmod u+x ~/.openafconsole"),sh("open -n ~/.openafconsole","",-1),sleep(500)),
0<=java.lang.System.getProperty("os.name").toLowerCase().indexOf("win")&&(installed?af.sh(["cmd","/c","start",getOpenAFPath()+"/openaf-console-ps.bat"],"",-1):af.sh(["cmd","/c","start",c,"-jar",getOpenAFJar(),"--console"],"",-1))}catch(b){logErr(b)}break;case "/exec/install":try{sh('"'+c+'" -jar '+getOpenAFJar()+" --install",void 0,void 0,!0),restartOpenAF(),exit(0)}catch(b){logErr(b)}break;case "/exec/update":try{sh('"'+c+'" -jar '+getOpenAFJar()+" --update",void 0,void 0,!0),restartOpenAF(),exit(0)}catch(b){logErr(b)}break;
case "/exec/quit":return keepRunning=!1,httpServer.replyOKText("")}return ow.server.httpd.replyRedirect(httpServer,"/")},"/exec/opack/":function(a){try{switch(a.uri){case "/exec/opack/install":isDefined(a.params.opack)&&(log("Installing oPack "+a.params.opack),__expr="install "+a.params.opack,load(getOpenAFJar()+"::js/opack.js"),log("oPack "+a.params.opack+" installed."));break;case "/exec/opack/update":isDefined(a.params.opack)&&(log("Updating oPack "+a.params.opack),__expr="update "+a.params.opack,
load(getOpenAFJar()+"::js/opack.js"),log("oPack "+a.params.opack+" updated."))}}catch(c){logErr(c)}return ow.server.httpd.replyRedirect(httpServer,"/opack")},"/odoc":function(a){try{var c=clone(defaultPage),b=[],d=a.uri.replace(/^\/odoc\/*/g,""),b=0<Object.keys(__odocs.aodocskeys).indexOf(d)?b.concat($stream(searchHelp("",void 0,d).map(function(a){return a.key})).toArray()):b.concat($stream(searchHelp(d,void 0).map(function(a){return a.key})).toArray()),b=b.sort();c.contents=1==b.length?templates("odoc",
{id:d,list:!1,terms:b,res:searchHelp(d)[0]}):templates("odoc",{id:d,list:!0,terms:b});return httpServer.replyOKHTML(templates("index",c))}catch(e){logErr(e)}},"/odocKey":function(a){try{var c=searchHelp(a.params.q)[0];isDefined(c.text)&&(c.text=c.text.replace(/  /g," &nbsp;"));return httpServer.replyOKJSON(stringify(c))}catch(b){logErr(b)}},"/opack":function(a){try{var c=clone(defaultPage),b=getOPackLocalDB(),d=getOPackRemoteDB();c.contents=templates("opacks",{installed:$stream(Object.keys(b)).map(function(a){return{Name:b[a].name,
Path:a,Version:b[a].version,Description:b[a].description,Author:b[a].author,Bugs:b[a].bugs.url}}).sorted("Name").toArray(),all:$stream(Object.keys(d)).map(function(a){return{Name:d[a].name,Path:getOPackPath(d[a].name),Version:isDefined(getOPackPath(d[a].name))?$stream(b).filter({name:d[a].name}).toArray()[0].version:"",RemoteVersion:d[a].version,Description:d[a].description,Author:d[a].author,Bugs:d[a].bugs.url,Local:isDefined(getOPackPath(d[a].name)),Update:isDefined(getOPackPath(d[a].name))?d[a].version!=
$stream(b).filter({name:d[a].name}).toArray()[0].version:""}}).sorted("Name").toArray()});return httpServer.replyOKHTML(templates("index",c))}catch(e){logErr(e)}}}),function(a){return httpServer.replyOKHTML(templates("index",defaultPage))},void 0,function(a){keepRunning=!0});log("Ready on http://127.0.0.1:"+port);log("Hit Ctrl-C on this to exit.");ow.server.daemon(2500,function(){return!keepRunning});
