var self=this,global=self,noHomeComms=!1;function getSerialize(a,b){var d=[],e=[];b=b||function(a,b){a=b;b=d.indexOf(a);var f=[e[b]];for(b--;0<=b;b--)d[b][f[0]]===a&&(a=d[b],f.unshift(e[b]));return"[Circular ~"+f.join(".")+"]"};return function(f,g){var h=g;"object"===typeof g&&g&&(-1!==d.indexOf(g)?h=b(f,g):(d.push(g),e.push(f)));a&&(h=a(f,h));return h}}function print(a){af.p(a)}function sprint(a,b){b=isUndefined(b)?"  ":b;return print(stringify(a,void 0,b))}
function bprint(a){return print(beautifier(a))}function printnl(a){af.pnl(a)}function sprintnl(a,b){b=isUndefined(b)?"  ":b;return printnl(stringify(a,void 0,b))}function bprintnl(a){return printnl(beautifier(a))}function tprintnl(a,b){b=isUndefined(b)?this:b;printnl(templify(a,b))}function tprint(a,b){tprintnl(a+"\n",b)}function printErr(a){af.e(a)}function sprintErr(a,b){b=isUndefined(b)?"  ":b;return printErr(stringify(a,void 0,b))}function bprintErr(a){return printErr(beautifier(a))}
function printErrnl(a){af.enl(a)}function sprintErrnl(a,b){b=isUndefined(b)?"  ":b;return printErrnl(stringify(a,void 0,b))}function bprintErrnl(a){return printErrnl(beautifier(a))}function tprintErrnl(a,b){b=isUndefined(b)?this:b;printErrnl(templify(a,b))}function tprintErr(a,b){tprintErrnl(a+"\n",b)}
function printTable(a,b,d){var e=0,f={},g="";if(!Array.isArray(a))return"";isUndefined(b)&&(b=-1);a.forEach(function(a){Object.keys(a).forEach(function(b){isUndefined(f[b])&&(f[String(b)]=b.length);f[String(b)]<String(a[String(b)]).length&&(f[String(b)]=String(a[String(b)]).length)})});a.forEach(function(a){var d=0,h=!1,k=Object.keys(a);0==e&&(g+="|",d=1,h=!1,k.forEach(function(a){h||(d+=f[String(a)]+1,0<b&&d>b+3?(g+="...",h=!0):g+=String(a)+repeat(f[String(a)]-String(a).length," ")+"|")}),g+="\n",
g+="+",d=1,h=!1,k.forEach(function(a){h||(d+=f[String(a)]+1,0<b&&d>b+3?(g+="...",h=!0):g+=repeat(f[String(a)],"-")+"+")}),g+="\n");g+="|";d=1;h=!1;k.forEach(function(e){h||(d+=f[String(e)]+1,0<b&&d>b+3?(g+="...",h=!0):g+=String(a[String(e)])+repeat(f[String(e)]-String(a[String(e)]).length," ")+"|")});g+="\n";e++});d&&(g+="[#"+e+" "+(1>=e?"row":"rows")+"]");return g}
function ansiColor(a,b,d){plugin("Console");var e=(new Console).getConsoleReader();d=d||e.getTerminal().isAnsiSupported()&&null!=java.lang.System.console();JavaImporter(Packages.org.fusesource.jansi);return d?a=Packages.org.fusesource.jansi.AnsiRenderer.render("@|"+a.toUpperCase()+" "+b+"|@"):b}
function ansiStart(a){plugin("Console");var b=(new Console).getConsoleReader();a=a||b.getTerminal().isAnsiSupported()&&null!=java.lang.System.console();b=JavaImporter(Packages.org.fusesource.jansi);a&&b.AnsiConsole.systemInstall()}function ansiStop(a){plugin("Console");var b=(new Console).getConsoleReader();a=a||b.getTerminal().isAnsiSupported()&&null!=java.lang.System.console();b=JavaImporter(Packages.org.fusesource.jansi);a&&b.AnsiConsole.systemUninstall()}
function wedoDate(a,b,d,e,f,g,h){return"number"==typeof a?{__wedo__type__:"date",content:[a+"-"+b+"-"+d+"T"+e+":"+f+":"+g+"."+h+"Z"]}:"[object Date]"==Object.prototype.toString.call(a)?{__wedo__type__:"date",content:[a]}:{}}function beautifier(a){a instanceof java.lang.Object&&(a=String(a));return af.js2s(a)}function stringify(a,b,d){a instanceof java.lang.Object&&(a=String(a));isUndefined(d)&&(d="  ");try{return JSON.stringify(a,b,d)}catch(e){try{return beautifier(a)}catch(f){throw e;}}}
function jsonParse(a){if(isDefined(a)&&0<String(a).length)try{return JSON.parse(a)}catch(b){return a}else return{}}function templify(a,b){b=isUndefined(b)?this:b;var d="";sync(function(){d=ow.loadTemplate().parse(a,b)},ow.loadTemplate());return d}function sleep(a){af.sleep(a)}function genUUID(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}function toCSV(a){var b=new CSV;b.toCsv(a);return b}var __logStatus;
isUndefined(__logStatus)&&(__logStatus=!1);function startLog(){$ch("__log").create();__logStatus=!0}function dumpLog(){return $ch("__log").getAll()}function stopLog(){__logStatus=!1;$ch("__log").destroy()}function log(a){var b=new Date;__logStatus&&$ch("__log").set({d:b,t:"INFO"},{d:b,t:"INFO",m:a});print(""+b+" | INFO | "+a)}function tlog(a,b){log(templify(a,b))}function lognl(a){var b=new Date;__logStatus&&$ch("__log").set({d:b,t:"INFO"},{d:b,t:"INFO",m:a});printnl(b+" | INFO | "+a+"\r")}
function tlognl(a,b){lognl(templify(a,b))}function logErr(a){var b=new Date;__logStatus&&$ch("__log").set({d:b,t:"ERROR"},{d:b,t:"ERROR",m:a});ansiStart();printErr(""+b+" | "+ansiColor("red","ERROR")+" | "+a);ansiStop()}function logWarn(a){var b=new Date;__logStatus&&$ch("__log").set({d:b,t:"WARN"},{d:b,t:"WARN",m:a});ansiStart();print(""+b+" | "+ansiColor("yellow","WARN")+" | "+a);ansiStop()}function tlogErr(a,b){logErr(templify(a,b))}function tlogWarn(a,b){logWarn(templify(a,b))}
function repeat(a,b){return b.repeat(a)}function now(){return Number(java.lang.System.currentTimeMillis())}function nowUTC(){return Number(java.util.Calendar.getInstance(java.util.TimeZone.getTimeZone("UTC")).getTimeInMillis())}function nowNano(){return Number(java.lang.System.nanoTime())}function md5(a){return org.apache.commons.codec.digest.DigestUtils.md5Hex(a)+""}function sha1(a){return org.apache.commons.codec.digest.DigestUtils.sha1Hex(a)+""}
function sha256(a){return org.apache.commons.codec.digest.DigestUtils.sha256Hex(a)+""}function sha512(a){return org.apache.commons.codec.digest.DigestUtils.sha512Hex(a)+""}function splitBySeparator(a,b){return a.replace(new RegExp(b,"g"),"\\"+b).replace(new RegExp("\\\\\\\\(?="+b+")","g"),"").split("\\"+b+"")}
function processExpr(a,b){isUndefined(a)&&(a=";");a=splitBySeparator(__expr,a);var d={};for(argIdx in a){var e=splitBySeparator(a[argIdx],"=");b?d[e[0].toLowerCase()]=isUndefined(e[1])?"":e[1]:d[e[0]]=isUndefined(e[1])?"":e[1]}for(var f in __pmIn)b?d[f.toLowerCase()]=__pmIn[f]:d[f]=__pmIn[f];return d}function getVersion(){return af.getVersion()}
function getOpenAFPath(){if(isDef(__forcedOpenAFJar))return String((new java.io.File(__forcedOpenAFJar)).getParent());var a=(new java.io.File(java.lang.System.getProperty("java.class.path"))).getAbsolutePath()+"",a=a.replace(/openaf\.jar$/,"").replace(/\\/g,"/");return a.replace(/[/\\][^/\\]+$/,"")}var __forcedOpenAFJar;function getOpenAFJar(){return isDefined(__forcedOpenAFJar)?__forcedOpenAFJar:String(af.getOpenAFJar()).replace(/\\/g,"/")}
var PACKAGEJSON=".package.json",PACKAGEYAML=".package.yaml",PACKAGESJSON="packages.json",PACKAGESJSON_DB=".opack.db",OPACKCENTRALDB="http://192.168.40.110/d/opack/opack.central.db",OPACKCENTRALDBBAK="http://172.25.1.32/d/opack/opack.central.db",OPACKCENTRALJSON="packages.json";
function getOPackRemoteDB(){var a={};if(noHomeComms)return a;plugin("ZIP");plugin("HTTP");var b,d;try{b=new HTTP(OPACKCENTRALDB,"GET","",{},!0,1500),d=new ZIP(b.responseBytes())}catch(e){try{b=new HTTP(OPACKCENTRALDBBAK,"GET","",{},!0,1500),d=new ZIP(b.responseBytes())}catch(f){return a}}a=af.fromJson(af.fromBytes2String(d.getFile(OPACKCENTRALJSON)));isUndefined(d)||d.close();return a}
function getOPackLocalDB(){var a=getOpenAFPath()+"/"+PACKAGESJSON_DB,b={};try{plugin("ZIP");var d=new ZIP(io.readFileBytes(a)),b=af.fromJson(af.fromBytes2String(d.getFile(PACKAGESJSON)));d.close();for(var e in b)"OpenAF"==b[e].name&&(b[e].version=getVersion())}catch(f){}return b}function getOPackPaths(){var a=getOPackLocalDB(),b={},d;for(d in a)b[a[d].name]=d;return b}function getOPackPath(a){return getOPackPaths()[a]}
function opackExec(a){__expr="exec "+a+" "+__expr;load(getOpenAFJar()+"::js/opack.js")}
function load(a){var b;try{return af.load(a),a}catch(e){if(e.message.match(/FileNotFoundException/)){b=e;try{af.load(a+".js")}catch(f){if(e.message.match(/FileNotFoundException/)){b=e;var d=getOPackPaths();d.__default=java.lang.System.getProperty("java.class.path")+"::js";for(i in d)try{return d[i]=d[i].replace(/\\+/g,"/"),d[i]=d[i].replace(/\/+/g,"/"),af.load(d[i]+"/"+a),a}catch(g){b=g}if("undefined"!==typeof __loadedfrom)return af.load(__loadedfrom.replace(/[^\/]+$/,"")+a),a}}}else throw e;}throw"Couldn't find "+
a+"; "+b;}function plugin(a){try{if(!a.match(/\./)){af.plugin("wedo.openaf.plugins."+a);return}}catch(b){}af.plugin(a)}function isUndefined(a){return"undefined"==typeof a?!0:!1}function isDefined(a){return!isUndefined(a)}function isDef(a){return"undefined"!=typeof a?!0:!1}function isUnDef(a){return"undefined"==typeof a?!0:!1}
function listFilesRecursive(a){if(isUndefined(a))return[];a=io.listFiles(a);if(isUndefined(a))return[];var b=[];a=a.files;if(isUndefined(a))return[];b=a.concat(b);for(i in a)a[i].isDirectory&&(b=b.concat(listFilesRecursive(a[i].filepath)));return b}
function cls(){plugin("Console");var a=JavaImporter(Packages.org.fusesource.jansi);con=new Console;con.getConsoleReader().getTerminal().isAnsiSupported()&&(a.AnsiConsole.systemInstall(),printnl(a.Ansi.ansi().eraseScreen().cursor(0,0).reset()),a.AnsiConsole.systemUninstall())}
function watch(a,b,d){var e=-2;plugin("Threads");plugin("Console");var f=new Console,g=new Threads;g.addThread(function(){var a="";try{a=af.eval(b)}catch(n){a=n.message}d&&(a=beautifier(a));cls();print(a);print("Press 'q' to quit. (refreshed at "+new Date+")")});try{for(g.startWithFixedRate(a);3!=e&&113!=e;){var h=Number(f.readCharNB());0<h&&(e=h)}print("");g.stop()}catch(l){printErr(l.message),g.stop()}}
function quickSort(a,b){function d(a,b,g,h){var e;if(1<a.length){e=a[Math.floor((h+g)/2)];for(var f=g,k=h;f<=k;){for(;0>b(a[f],e);)f++;for(;0<b(a[k],e);)k--;if(f<=k){var m=a,p=k,q=m[f];m[f]=m[p];m[p]=q;f++;k--}}e=f;g<e-1&&d(a,b,g,e-1);e<h&&d(a,b,e,h)}return a}isUndefined(b)&&(b=function(a,b){return a-b});return d(a,b,0,a.length-1)}
function extend(){var a={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object","[object Error]":"error"},b=a.toString,d=a.hasOwnProperty,e={isFunction:function(a){return"function"===e.type(a)}};e.isArray=Array.isArray;e.type=function(d){return null==d?String(d):"object"===typeof d||"function"===typeof d?a[b.call(d)]||"object":typeof d};e.isPlainObject=
function(a){if("object"!==e.type(a)||a.nodeType)return!1;try{if(a.constructor&&!d.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(t){return!1}return!0};var f,g,h,l,n,k=arguments[0]||{},m=1,p=arguments.length,q=!1;"boolean"===typeof k&&(q=k,k=arguments[1]||{},m=2);"object"===typeof k||e.isFunction(k)||(k={});p===m&&(k=this,--m);for(;m<p;m++)if(null!=(f=arguments[m]))for(g in f)h=k[g],l=f[g],k!==l&&(q&&l&&(e.isPlainObject(l)||(n=e.isArray(l)))?(n?(n=!1,h=h&&e.isArray(h)?h:[]):h=h&&e.isPlainObject(h)?
h:{},k[g]=extend(q,h,l)):void 0!==l&&(k[g]=l));return k}function exit(a){isUndefined(a)&&(a=0);java.lang.System.exit(a)}function clone(a){return Array.isArray(a)?a.slice(0):extend(!0,{},a)}function merge(a,b){if(isObject(a)&&isArray(b)){for(var d in b)b[d]=merge(b[d],clone(a));return b}if(isObject(b)&&isArray(a)){for(d in a)a[d]=merge(a[d],clone(b));return a}return extend(!0,clone(a),b)}
function restartOpenAF(a){var b=java.lang.System.getProperty("java.home")+java.io.File.separator+"bin"+java.io.File.separator+"java",d;try{d=new java.io.File(af.getClass("wedo.openaf.AFCmd").getProtectionDomain().getCodeSource().getLocation().toURI())}catch(f){d=new java.io.File(java.lang.System.getProperties().getProperty("java.class.path"))}if(d.getName().endsWith(".jar")){var e=new java.util.ArrayList;e.add(b);e.add("-jar");e.add(d.getPath());if(isUndefined(a))for(c in __args)e.add(__args[c]);
else for(c in a)e.add(a[c]);a=new java.lang.ProcessBuilder(e);a.inheritIO();a.start();java.lang.System.exit(0)}}
function compare(a,b){if(null===a||void 0===a||null===b||void 0===b)return a===b;if(a.constructor!==b.constructor)return!1;if(a instanceof Function||a instanceof RegExp)return a===b;if(a===b||a.valueOf()===b.valueOf())return!0;if(Array.isArray(a)&&a.length!==b.length||a instanceof Date||!(a instanceof Object)||!(b instanceof Object))return!1;var d=Object.keys(a);return Object.keys(b).every(function(a){return-1!==d.indexOf(a)})&&d.every(function(d){return compare(a[d],b[d])})}
function inherit(a,b){a.prototype=Object.create(b.prototype);a.prototype.constructor=a}$from=function(a){loadLib(getOpenAFJar()+"::js/jlinq.js");return"[object Array]"==Object.prototype.toString.call(a)?jl.from(a):jl.from(Object.keys(a).map(function(b){var d={};d[b]=a[b];return d}))};$stream=function(a){loadLib(getOpenAFJar()+"::js/stream.js");return isUndefined(a)?Stream:Stream(a)};var __cpucores;
function getNumberOfCores(){plugin("Threads");var a=new Threads;return __cpucores=Number(a.getNumberOfCores())}function getCPULoad(a){if(a)return Number(java.lang.management.ManagementFactory.getOperatingSystemMXBean().getSystemCpuLoad()*getNumberOfCores());a=Number(java.lang.management.ManagementFactory.getOperatingSystemMXBean().getSystemLoadAverage());0>a&&(a=Number(java.lang.management.ManagementFactory.getOperatingSystemMXBean().getSystemCpuLoad()*getNumberOfCores()));return a}
function getPid(){return(Packages.java.lang.management.ManagementFactory.getRuntimeMXBean().getName()+"").replace(/(\d+).+/,"$1")}function addOnOpenAFShutdown(a){plugin("Threads");(new Threads).addOpenAFShutdownHook(a)}function pidCheck(a){try{if(java.lang.System.getProperty("os.name").match(/Windows/)){if(af.sh('cmd /c tasklist /NH /FI "PID eq '+a+'"').match(a))return!0}else if(af.sh("kill -0 "+a),0==__exitcode)return!0}catch(b){}return!1}
function pidCheckIn(a){var b;try{if(b=io.readFileString(a),pidCheck(b))return!1}catch(d){}io.writeFileString(a,getPid());plugin("Threads");(new Threads).addOpenAFShutdownHook(function(){pidCheckOut(a)});return!0}function pidKill(a,b){try{var d="";if(java.lang.System.getProperty("os.name").match(/Windows/)){if(b&&(d="/F"),af.sh("cmd /c taskkill "+d+" /PID "+a))return!0}else if(af.sh("kill "+(b?"-9":"-2")+" "+a),0==__exitcode)return!0}catch(e){}return!1}
function pidCheckOut(a){try{if(io.writeFileString(a,""),af.rm(a))return!0}catch(b){}return!1}function splitArray(a,b){var d=[];isUndefined(b)&&(b=getNumberOfCores());if(b>=a.length)for(var e in a)d.push([a[e]]);else for(e=0;e<b;e++)d.push(a.slice(Math.round(a.length/b*e),Math.round(a.length/b*(e+1))));return d}
function parallel(a,b,d,e){function f(){var a=getCPULoad();if(a>b){for(sync(function(){cooldown++});a>b&&0<b;)sleep(2E3*(a-b)),a=getCPULoad();sync(function(){cooldown--})}}plugin("Threads");var g=new Threads;isUndefined(__cpucores)&&(__cpucores=g.getNumberOfCores());isUndefined(b)&&(b=__cpucores+1,h=!0);isDefined(e)&&(e.__threads=g,e.__numThreads=b,e.uuids=[]);for(var h=!1,l=[],n=0;n<b;n++){var k=g.addThread(function(b){l.push(a(b,g));h&&f()});isDefined(e)&&e.uuids.push(k)}g.start();g.stop();return isUndefined(d)?
l:d(l)}
function parallelArray(a,b,d,e,f,g){function h(){var a=getCPULoad();if(a>f){for(sync(function(){cooldown++});a>f&&0<f;)sleep(2E3*(a-f)),a=getCPULoad();sync(function(){cooldown--})}}plugin("Threads");if(isUndefined(a)||isUndefined(b))throw"Need an array and a function.";if(!isArray(a)&&(a=Object.keys(a),!isArray(a)))throw"The object provided is not an array.";var l=!1,n=[],k=new Threads;isUndefined(__cpucores)&&(__cpucores=k.getNumberOfCores());isUndefined(f)&&(f=__cpucores+1,l=!0);var m=[];if(f>=
a.length)for(var p in a)m.push([a[p]]);else for(p=0;p<f;p++)m.push(a.slice(Math.round(a.length/f*p),Math.round(a.length/f*(p+1))));isDefined(g)&&(g.__threads=k,g.__numThreads=f,g.uuids=[],g.uuidsArrayLength={});var q={},r;for(r in m)a=k.addThread(function(a){var e=q[a].reduce(b,d);k.sync(function(){n.push(e)});l&&h()}),q[a]=m[r],isDefined(g)&&(g.uuids.push(a),g.uuidsArrayLength[a]=m[r].length);k.start();k.stop();return isUndefined(e)?n:e(n,this)}
function parallel4Array(a,b,d,e){return parallelArray(a,function(a,d,e,l){return[b(d)].concat(a)},[],function(a){var b=[],d;for(d in a)b=b.concat(a[d]);return b},d,e)}function compress(a){return io.gzip(af.fromString2Bytes(stringify(a)))}function uncompress(a){return JSON.parse(af.fromBytes2String(io.gunzip(a)))}var isArray=Array.isArray;function isObject(a){var b=typeof a;return"function"===b||"object"===b&&!!a}function isFunction(a){return"function"==typeof a||!1}
function isString(a){return"string"==typeof a||!1}var __loadedLibs;isUndefined(__loadedLibs)&&(__loadedLibs={});function loadLib(a,b,d){return b||isUndefined(__loadedLibs[a.toLowerCase()])||0==__loadedLibs[a.toLowerCase()]?(load(a),__loadedLibs[a.toLowerCase()]=!0,isDefined(d)&&d(),!0):!1}function sync(a,b){var d=!1,e;af.sync(function(){try{a()}catch(f){d=!0,e=f}},b)();if(d)throw e;}function Pod(a){this.name=a;this._m={}}Pod._m={};
Pod.define=function(a,b,d){b instanceof Array||(d=b,b=[]);if(!a||!d)throw"invalid definition";if("function"!=typeof d){var e=d;d=function(){return e}}this._m[a]={d:b,f:d};return this};Pod.declare=function(a,b){function d(a){return function(){return a}}var e=a;"string"==typeof a&&(e={},e[a]=b);for(a in e)e.hasOwnProperty(a)&&this.define(a,d(e[a]));return this};
Pod.require=function(a,b){var d=!(a instanceof Array);a=d?[a]:a.slice();for(var e=0;e<a.length;e++){var f=a[e];if(this._m.hasOwnProperty(f)){var g=this._m[f];if(!g.e){if(g._)throw"circular reference to "+f;g._=1;g.e=g.f.apply(null,this.require(g.d));g._=0}a[e]=g.e}else if(f===this.name||"pod"===f)a[e]=this;else throw f+" is undefined";}"function"==typeof b&&b.apply(null,a);return d?a[0]:a};Pod.prototype={define:Pod.define,declare:Pod.declare,require:Pod.require};var pods;
isUndefined(pods)&&(pods=new Pod);function loadRequire(a,b){function d(a){return String((new java.io.File(a)).toURI().toURL().toExternalForm())}if(isUndefined(a)){a=[];var e=getOPackPaths(),f;for(f in e)a.push(d(e[f]));a.push(d(java.lang.System.getProperty("user.dir")))}af.loadRequire(a,b)}loadRequire();var OpenWrap;isUndefined(OpenWrap)&&(OpenWrap=function(){});var ow;isUndefined(ow)&&(ow=new OpenWrap);
OpenWrap.prototype.loadFormat=function(){loadLib(getOpenAFJar()+"::js/owrap.format.js");ow.format=new OpenWrap.format;pods.declare("ow.format",ow.format);return ow.format};OpenWrap.prototype.loadTest=function(){loadLib(getOpenAFJar()+"::js/owrap.test.js");ow.test=new OpenWrap.test;pods.declare("ow.test",ow.test);return ow.test};OpenWrap.prototype.loadServer=function(){loadLib(getOpenAFJar()+"::js/owrap.server.js");ow.server=new OpenWrap.server;pods.declare("ow.server",ow.server);return ow.server};
OpenWrap.prototype.loadTemplate=function(){loadLib(getOpenAFJar()+"::js/owrap.template.js");ow.template=new OpenWrap.template;pods.declare("ow.template",ow.template);return ow.template};OpenWrap.prototype.loadObj=function(){loadLib(getOpenAFJar()+"::js/owrap.obj.js");ow.obj=new OpenWrap.obj;pods.declare("ow.obj",ow.obj);return ow.obj};OpenWrap.prototype.loadCh=function(){loadLib(getOpenAFJar()+"::js/owrap.ch.js");ow.ch=new OpenWrap.ch;pods.declare("ow.ch",ow.ch);return ow.ch};
OpenWrap.prototype.loadPortal=function(){loadLib(getOpenAFJar()+"::js/owrap.portal.js");ow.portal=new OpenWrap.portal;pods.declare("ow.portal",ow.portal);return ow.portal};OpenWrap.prototype.loadOJob=function(){loadLib(getOpenAFJar()+"::js/owrap.oJob.js");ow.oJob=new OpenWrap.oJob;pods.declare("ow.oJob",ow.oJob);return ow.oJob};function loadHandlebars(){loadLib(getOpenAFJar()+"::js/handlebars.js")&&pods.declare("Handlebars",loadHandlebars())}
function loadUnderscore(){loadLib(getOpenAFJar()+"::js/underscore.js")&&pods.declare("Underscore",loadUnderscore())}function loadHelp(){loadLib(getOpenAFJar()+"::js/odoc.js")&&pods.declare("Help",loadHelp())}var __odocsurl;isUndefined(__odocsurl)&&(__odocsurl=["http://192.168.40.110/d/openaf/odoc","http://172.25.1.32/d/openaf/odoc"]);var __odocs,__offlineHelp;isUndefined(__offlineHelp)&&(__offlineHelp=noHomeComms?!0:!1);
function setOfflineHelp(a){__offlineHelp=a;isDefined(__odocs)&&(__odocs=void 0)}
function searchHelp(a,b,d){loadHelp();if(isUndefined(b)){var e,f=[getOpenAFJar()],f=f.concat(Object.keys(getOPackLocalDB())),g;for(g in f)if(e=f[g],e.match(/\.(jar|db|zip)/)||(e+="/"),e=searchHelp(a,e,d),0<e.length)return e}__odocs=new ODocs(b,void 0,__odocsurl,__offlineHelp);a=__odocs.search(a,d);return 1==a.length?(b=__odocs.get(a[0].id,a[0].key),[{id:a[0].id,key:a[0].key,fullkey:b.k,text:b.t}]):a=a.sort(function(a,b){return a.key>b.key?1:-1})}
function saveHelp(a,b){loadHelp();b=new ODocsGen(b);(new ODocs(a+"/",b.getODoc())).save()}function saveHelpWeb(a,b){loadHelp();b=new ODocsGen(b);(new ODocs(a,b.getODoc())).saveWeb()}function createDBInMem(a,b,d,e,f,g,h){b=isUndefined(d)?"sa":d;e=isUndefined(e)?"sa":e;d="mem";f&&(d="memFS");g&&(d="memLZF");(f||g)&&h&&(d="nio"+d.replace(/mem/,"Mem"));return new DB("org.h2.Driver","jdbc:h2:"+d+":"+a,b,e)}function persistDBInMem(a,b){return a.q("script to '"+b+"'")}
function loadDBInMem(a,b){return a.u("runscript from '"+b+"'")}function traverse(a,b,d){var e=Object.keys(a);d=isUndefined(d)?"":d;for(var f in e)if(b(e[f],a[e[f]],d),"object"==typeof a[e[f]]){var g=d+(isNaN(Number(e[f]))?"."+e[f]:'["'+e[f]+'"]');traverse(a[e[f]],b,g)}}function searchKeys(a,b,d){var e={},f=d?"":"i";traverse(a,function(a,d,l){a.match(new RegExp(b,f))&&(e[l+(isNaN(Number(a))?"."+a:'["'+a+'"]')]="object"==typeof d?clone(d):d)});return e}
function searchValues(a,b,d){var e={},f=d?"":"i";traverse(a,function(a,d,l){(d+"").match(new RegExp(b,f))&&(e[l+(isNaN(Number(a))?"."+a:'["'+a+'"]')]="object"==typeof d?clone(d):d)});return e}function searchArray(a,b,d,e,f){return ow.loadObj.searhArray(a,b,d,e,f)}function flatten(a,b){var d=[];traverse(a,function(a,f,g){var e={};b?e[g+(0<g.length?".":"")+a]="object"==typeof f?clone(f):f:e={key:g+(0<g.length?".":"")+a,val:"object"==typeof f?clone(f):f};d.push(e)});return d}
function showDebugger(a){print("Trying to create a debugger instance...");af.showDebugger(a);print("Please use File|Run to select the script you wish to debug.")}function checkLatestVersion(){plugin("HTTP");var a=-1;if(noHomeComms)return a;["http://192.168.40.110/d/openaf/release","http://172.25.1.32/d/openaf/release"].forEach(function(b){try{a=(new HTTP(b,void 0,void 0,void 0,!1,2500)).response().trim()}catch(d){}});return a}
function sh(a,b,d,e,f){return"string"==typeof a?java.lang.System.getProperty("os.name").match(/Windows/)?af.sh(["cmd","/c",a],b,d,e,f):af.sh(["/bin/sh","-c",a],b,d,e,f):af.sh(a,b,d,e,f)}function findRandomOpenPort(){try{var a=new java.net.ServerSocket(0),b=a.getLocalPort();a.close();return b}catch(d){return-1}}
function ioStreamWrite(a,b,d,e){if(e){d=isUndefined(d)?1024:d;var f;try{f=a.getChannel()}catch(g){f=java.nio.channels.Channels.newChannel(a)}a=java.nio.ByteBuffer.allocate(d);a.clear();a.put(af.fromString2Bytes(b));for(a.flip();a.hasRemaining();)f.write(a)}else a.write(af.fromString2Bytes(b))}
function ioStreamWriteBytes(a,b,d,e){if(e){d=isUndefined(d)?1024:d;var f;try{f=a.getChannel()}catch(g){f=java.nio.channels.Channels.newChannel(a)}a=java.nio.ByteBuffer.allocate(d);a.clear();a.put(b);for(a.flip();a.hasRemaining();)f.write(a)}else a.write(b)}
function ioStreamRead(a,b,d,e){d=isUndefined(d)?1024:d;if(e){var f;try{f=a.getChannel()}catch(g){f=java.nio.channels.Channels.newChannel(a)}e=java.nio.ByteBuffer.allocate(d);for(d=f.read(e);-1!=d;){e.flip();for(d=[];e.hasRemaining();)d.push(Number(e.get()));b(af.fromBytes2String(af.fromArray2Bytes(d)));e.clear();d=f.read(e)}f.close();a.close()}else for(e=af.fromString2Bytes(repeat(d," "));0<a.available();)f=a.read(e,0,d),0<f&&b(af.fromBytes2String(af.fromArray2Bytes(af.fromBytes2Array(e).slice(0,
f))))}function ioStreamCopy(a,b){Packages.org.apache.commons.io.IOUtils.copyLarge(b,a);Packages.org.apache.commons.io.IOUtils.closeQuietly(b);Packages.org.apache.commons.io.IOUtils.closeQuietly(a)}
function ioStreamReadBytes(a,b,d,e){d=isUndefined(d)?1024:d;if(e){e=af.fromString2Bytes(repeat(d," "));for(var f;0<a.available();)f=a.read(e,0,d),0<f&&b(af.fromArray2Bytes(af.fromBytes2Array(e).slice(0,f)))}else{try{f=a.getChannel()}catch(g){f=java.nio.channels.Channels.newChannel(a)}e=java.nio.ByteBuffer.allocate(d);for(d=f.read(e);-1!=d;){e.flip();for(d=[];e.hasRemaining();)d.push(Number(e.get()));b(af.fromArray2Bytes(d));e.clear();d=f.read(e)}f.close()}a.close()}
function toEncoding(a,b){isUndefined(b)&&(b="UTF-8");return String(new java.lang.String(af.fromString2Bytes(a),b))}function utf8(a){return toEncoding(a,"UTF-8")}function getFromZip(a,b,d,e){plugin("ZIP");if(isDefined(b)){var f=new ZIP;f.loadFile(a);a=f.getFile(b);f.close();d||(a=af.fromBytes2String(a),isDefined(e)&&(a=toEncoding(a,e)));return a}return null}
Array.from||(Array.from=function(){var a=Object.prototype.toString,b=function(b){return"function"===typeof b||"[object Function]"===a.call(b)},d=Math.pow(2,53)-1;return function(a){var e=Object(a);if(null==a)throw new TypeError("Array.from requires an array-like object - not null or undefined");var g=1<arguments.length?arguments[1]:void 0,h;if("undefined"!==typeof g){if(!b(g))throw new TypeError("Array.from: when provided, the second argument must be a function");2<arguments.length&&(h=arguments[2])}var l;
l=Number(e.length);l=isNaN(l)?0:0!==l&&isFinite(l)?(0<l?1:-1)*Math.floor(Math.abs(l)):l;l=Math.min(Math.max(l,0),d);for(var n=b(this)?Object(new this(l)):Array(l),k=0,m;k<l;)m=e[k],n[k]=g?"undefined"===typeof h?g(m,k):g.call(h,m,k):m,k+=1;n.length=l;return n}}());function newJavaArray(a,b){return java.lang.reflect.Array.newInstance(a,b)}var alert;isUndefined(alert)&&(alert=function(a){printErr(String(a))});__timeout={};
function setTimeout(a,b){sleep(b);for(var d=[],e=2;e<=arguments.length;e++)d.push(arguments[e]);a.apply(this,d)}function setInterval(a,b){plugin("Threads");for(var d=new Threads,e=[],f=2;f<=arguments.length;f++)e.push(arguments[f]);var g=this,f=d.addThread(function(b){a.apply(g,e)});__timeout[f]=d;d.startAtFixedRate(b);return f}function clearInterval(a){__timeout[a].stop();delete __timeout[a]}function deleteFromArray(a,b){a.splice(b,1);return a}
function oJobRunFile(a,b,d){ow.loadOJob().runFile(a,b,d)}function oJobRun(a,b,d){a=ow.loadOJob().loadJSON(a);ow.oJob.load(a.jobs,a.todo,a.ojob,b,d);ow.oJob.start(b,!0,d)}function oJobRunJob(a,b,d){ow.loadOJob();ow.oJob.runJob(a,b,d)}var OPENAFPROFILE;isUndefined(OPENAFPROFILE)&&(OPENAFPROFILE=".openaf_profile");
(function(){var a="";try{a=io.readFileString(java.lang.System.getProperty("user.home")+"/"+OPENAFPROFILE),af.compile(a)}catch(b){if(!b.message.match(/java\.io\.FileNotFoundException/))throw b;}a="";try{a=io.readFileString(getOpenAFJar()+"::"+OPENAFPROFILE),af.compile(a)}catch(b){if(!b.message.match(/java\.io\.FileNotFoundException/)&&!b.message.match(/java\.lang\.NullPointerException: entry/))throw b;}})();function loadJSYAML(){loadLib(getOpenAFJar()+"::js/js-yaml.js")}
AF.prototype.toYAML=function(a){loadJSYAML();return jsyaml.dump(a)};AF.prototype.fromYAML=function(a){loadJSYAML();return jsyaml.load(a)};IO.prototype.readFileYAML=function(a){return af.fromYAML(io.readFileString(a))};IO.prototype.writeFileYAML=function(a,b){return io.writeFileString(a,af.toYAML(b))};
$ch=$channels=function(a){ow.loadCh();return{create:function(b,d,e){ow.ch.create(a,b,d,e);return $channels(a)},list:function(){return ow.ch.list()},destroy:function(){ow.ch.destroy(a);return $channels(a)},size:function(){return ow.ch.size(a)},subscribe:function(b,d,e){return ow.ch.subscribe(a,b,d,e)},unsubscribe:function(b){ow.ch.unsubscribe(a,b);return $channels(a)},forEach:function(b,d){ow.ch.forEach(a,b,d);return $channels(a)},getAll:function(b){return ow.ch.getAll(a,b)},getKeys:function(b,d){return ow.ch.getKeys(a,
b,d)},getSortedKeys:function(b,d){return ow.ch.getSortedKeys(a,b,d)},set:function(b,d,e,f,g){return ow.ch.set(a,b,d,e,f,g)},setAll:function(b,d,e,f,g){return ow.ch.setAll(a,b,d,e,f,g)},get:function(b,d){return ow.ch.get(a,b,d)},getSet:function(b,d,e,f,g,h){return ow.ch.getSet(a,b,d,e,f,g,h)},unset:function(b,d,e,f){ow.ch.unset(a,b,d,e,f);return $channels(a)},push:function(b,d){ow.ch.push(a,b,d);return $channels(a)},pop:function(b){return ow.ch.pop(a,b)},shift:function(b){return ow.ch.shift(a,b)},
getVersion:function(){return ow.ch.getVersion(a)},storeAdd:function(b,d,e){ow.ch.persistence.create(a,b,d,e);return $channels(a)},storeRestore:function(b,d){ow.ch.persistence.restore(a,b,d);return $channels(a)},expose:function(b,d,e,f){return ow.ch.server.expose(a,b,d,e,f)},peer:function(b,d,e,f,g){ow.ch.server.peer(a,b,d,e,f,g);return $channels(a)},createRemote:function(b,d){b=new java.net.URL(b);d=b.getPort();0>d&&"https"==b.getProtocol()&&(d=443);0>d&&(d=80);b={login:null!=b.getUserInfo()?String(java.net.URLDecoder.decode(b.getUserInfo().substring(0,
b.getUserInfo().indexOf(":")),"UTF-8")):void 0,password:null!=b.getUserInfo()?String(java.net.URLDecoder.decode(b.getUserInfo().substring(b.getUserInfo().indexOf(":")+1),"UTF-8")):void 0,url:String(b.getProtocol()+"://"+b.getHost()+":"+d+b.getPath())};ow.ch.create(a,!0,"remote",b);return $channels(a)},stopJobs:function(){ow.ch.stopAllJobs(a);return $channels(a)},waitForJobs:function(b){ow.ch.waitForJobs(a,b);return $channels(a)}}};for(var i=Packages.org.slf4j.LoggerFactory.getLogger(Packages.ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME).getLoggerContext().getLoggerList().iterator();i.hasNext();)Packages.org.slf4j.LoggerFactory.getLogger(i.next().getName()).setLevel(Packages.ch.qos.logback.classic.Level.ERROR);
