OpenWrap.test=function(){this.reset();return ow.test};OpenWrap.test.prototype.getCountTest=function(){return this.__countTest};OpenWrap.test.prototype.getCountPass=function(){return this.__countPass};OpenWrap.test.prototype.getCountFail=function(){return this.__countFail};OpenWrap.test.prototype.getProfileHits=function(a){return this.__profile[a].hits};OpenWrap.test.prototype.getProfileAvg=function(a){return this.__profile[a].sum/this.__profile[a].hits};OpenWrap.test.prototype.getProfileLast=function(a){return this.__profile[a].last};
OpenWrap.test.prototype.profileReset=function(a){this.__profile[a]={hits:0,sum:0,last:0,start:0}};OpenWrap.test.prototype.getProfile=function(){return this.__profile};OpenWrap.test.prototype.getAllProfileHits=function(){var a={},b;for(b in this.__profile)a[b]=ow.test.getProfileHits(b);return a};OpenWrap.test.prototype.getAllProfileAvg=function(){var a={},b;for(b in this.__profile)a[b]=ow.test.getProfileAvg(b);return a};
OpenWrap.test.prototype.getAllProfileLast=function(){var a={},b;for(b in this.__profile)a[b]=ow.test.getProfileLast(b);return a};OpenWrap.test.prototype.setShowStackTrace=function(a){this.__showStackTrace=a};OpenWrap.test.prototype.setMemoryProfile=function(a){this.__memoryprofile=a};OpenWrap.test.prototype.reset=function(){this.getChannel().destroy();this.getChannel().create();this.__countFail=this.__countPass=this.__countTest=0;this.__profile={};this.__showStackTrace=!0;this.__memoryprofile=!1};
OpenWrap.test.prototype.assert=function(a,b,e,c){if(!compare(a,b))throw e+(c?"":" (got "+stringify(a)+" but expected "+stringify(b)+")");};
OpenWrap.test.prototype.start=function(a){isUndefined(this.__profile[a])&&(this.__profile[a]={hits:0,sum:0,last:0,start:0});this.__profile[a].start=now();this.__memoryprofile&&(java.lang.Runtime.getRuntime().gc(),this.__profile[a].startTotalMem=Number(java.lang.Runtime.getRuntime().totalMemory()),this.__profile[a].startFreeMem=Number(java.lang.Runtime.getRuntime().freeMemory()));return a};
OpenWrap.test.prototype.stop=function(a){var b=now()-this.__profile[a].start;this.__memoryprofile&&(java.lang.Runtime.getRuntime().gc(),this.__profile[a].stopTotalMem=Number(java.lang.Runtime.getRuntime().totalMemory()),this.__profile[a].stopFreeMem=Number(java.lang.Runtime.getRuntime().freeMemory()));this.__profile[a].last=b;this.__profile[a].hits++;this.__profile[a].sum+=b;return b};
OpenWrap.test.prototype.testExternally=function(a,b,e){var c=this.getChannel().get(a);isUndefined(c)&&(c={test:a.replace(/.+::/,""),suite:0<a.indexOf("::")?a.replace(/::.+/,""):"Test suite",hits:0,pass:0,fail:0,executions:[]});log("TEST | "+a);this.__countTest++;var d={};this.start(a);this.__memoryprofile&&(d.startTotalMem=this.__profile[a].startTotalMem,d.startFreeMem=this.__profile[a].startFreeMem);d.start=this.__profile[a].start;try{c.hits++;log("Running "+b);var f=sh(b,"",e);d.elapsedTime=this.stop(a);
this.__memoryprofile&&(d.stopFreeMem=this.__profile[a].stopFreeMem,d.stopTotalMem=this.__profile[a].stopTotalMem,d.diffMem=d.stopTotalMem-d.stopFreeMem-(d.startTotalMem-d.startFreeMem));c.exitCode=__exitcode;if(0!=__exitcode)throw"exit code "+__exitcode;log("PASS | "+a);this.__countPass++;d.status="PASS";c.pass++;c.executions.push(d);this.getChannel().set(a,c);return f}catch(k){d.elapsedTime=this.stop(a),this.__memoryprofile&&(d.stopFreeMem=this.__profile[a].stopFreeMem,d.stopTotalMem=this.__profile[a].stopTotalMem,
d.diffMem=d.stopTotalMem-d.stopFreeMem-(d.startTotalMem-d.startFreeMem)),logErr("FAIL | "+a),d.status="FAIL",d.exception=String(k),c.fail++,this.__countFail++,c.executions.push(d),this.getChannel().set(a,c)}};
OpenWrap.test.prototype.test=function(a,b){var e=this.getChannel().get(a);isUndefined(e)&&(e={test:a.replace(/.+::/,""),suite:0<a.indexOf("::")?a.replace(/::.+/,""):"Test suite",hits:0,pass:0,fail:0,start:now(),executions:[]});log("TEST | "+a);this.__countTest++;var c={};this.start(a);this.__memoryprofile&&(c.startTotalMem=this.__profile[a].startTotalMem,c.startFreeMem=this.__profile[a].startFreeMem);c.start=this.__profile[a].start;try{e.hits++;var d=b();c.elapsedTime=this.stop(a);this.__memoryprofile&&
(c.stopFreeMem=this.__profile[a].stopFreeMem,c.stopTotalMem=this.__profile[a].stopTotalMem,c.diffMem=c.stopTotalMem-c.stopFreeMem-(c.startTotalMem-c.startFreeMem));c.status="PASS";e.pass++;log("PASS | "+a);this.__countPass++;e.executions.push(c);this.getChannel().set(a,e);return d}catch(f){c.elapsedTime=this.stop(a);this.__memoryprofile&&(c.stopFreeMem=this.__profile[a].stopFreeMem,c.stopTotalMem=this.__profile[a].stopTotalMem,c.diffMem=c.stopTotalMem-c.stopFreeMem-(c.startTotalMem-c.startFreeMem));
log("FAIL | "+a+" | "+f);c.status="FAIL";c.exception=String(f);e.fail++;this.__countFail++;if(this.__showStackTrace)try{f.javaException.printStackTrace()}catch(k){}e.executions.push(c);this.getChannel().set(a,e)}};OpenWrap.test.prototype.getChannel=function(){return $ch("__owTest::tests")};
OpenWrap.test.prototype.toJUnitXML=function(a,b){var e=0,c=0,d=0,f=[];this.getChannel().forEach(function(a,b){a={id:isDefined(b.suite)?b.suite:b.test,name:isDefined(b.suite)?b.suite:b.test,tests:b.hits,pass:b.pass,fail:b.fail,start:$from(b.executions).min("start").start,time:$from(b.executions).sum("elapsedTime"),testSuite:$from(b.executions).select(function(a){"FAIL"==a.status&&c++;d+=a.elapsedTime;return{id:a.start,start:a.start,name:b.test,time:a.elapsedTime,failMessage:a.exception,failed:isDefined(a.exception)}})};
var g=$from(f).equals("name",isDefined(b.suite)?b.suite:b.test).at(0);isUndefined(g)?(e++,f.push(a)):(g.tests+=a.tests,g.pass+=a.pass,g.fail+=a.fail,g.time+=a.time,g.testSuite=g.testSuite.concat(a.testSuite))});$from(f).min("start");plugin("XML");var k=new XML;a=k.x("testsuites").a("id",a).a("name",b).a("tests",e).a("failures",c).a("time",d/1E3);for(var l in f){b=f[l];a=a.e("testsuite").a("id",b.id).a("name",b.name).a("tests",b.testSuite.length).a("failures",b.fail).a("time",b.time/1E3).a("timestamp",
(new Date(b.start)).toISOString());for(var m in b.testSuite){var h=b.testSuite[m];a=a.e("testcase").a("id",h.id).a("name",h.name).a("time",h.time/1E3);h.failed&&(a=a.e("failure").a("message",h.failMessage).a("type","ERROR").t(h.failMessage).up());a=a.up()}a=a.up()}return k.w()};
