OpenWrap.obj=function(){return ow.obj};
OpenWrap.obj.prototype.fromDBRS2Obj=function(a,b){for(var d={},c=1;c<=a.getMetaData().getColumnCount();c++)if(null!=a.getObject(c))switch(a.getMetaData().getColumnType(c)){case java.sql.Types.NUMERIC:case java.sql.Types.DOUBLE:case java.sql.Types.FLOAT:case java.sql.Types.DECIMAL:d[a.getMetaData().getColumnName(c)]=Number(a.getDouble(c));break;case java.sql.Types.CLOB:d[a.getMetaData().getColumnName(c)]=Packages.org.apache.commons.io.IOUtils.copy(a.getClob(c).getAsciiStream());break;case java.sql.Types.BINARY:case java.sql.Types.BLOB:d[a.getMetaData().getColumnName(c)]=
Packages.org.apache.commons.io.IOUtils.toByteArray(a.getBlob(c).getBinaryStream());break;case java.sql.Types.TIMESTAMP:if(b){d[a.getMetaData().getColumnName(c)]=new Date(a.getTimestamp(c).getTime());break}case java.sql.Types.DATE:if(b){d[a.getMetaData().getColumnName(c)]=new Date(a.getDate(c).getTime());break}default:d[a.getMetaData().getColumnName(c)]=String(a.getString(c))}else d[a.getMetaData().getColumnName(c)]=null;return d};
OpenWrap.obj.prototype.fromArray2DB=function(a,b,d,c){isUndefined(c)&&(c=getNumberOfCores());if(isUndefined(a)||1>a.length)return 0;1>c&&(c=1);var e=Object.keys(a[0]).join(",").toUpperCase();return parallel4Array(a,function(a){var c=[],f=e.split(","),k;for(k in f)c.push(a[k]);return b.us("insert into "+d+"("+e+") values (?, ?)",c)},c,{}).length};OpenWrap.obj.prototype.fromArray2OrderedObj=function(a){if(isUndefined(a)||1>a.length)return{};var b={},d;for(d in a)b[d]=a[d];return b};
OpenWrap.obj.prototype.fromOrderedObj2Array=function(a,b){if(isUndefined(a)||1>Object.keys(a).length)return[];isUndefined(b)&&(b=function(b,a){return b-a});b=quickSort(Object.keys(a),b);var d=[],c;for(c in b)d.push(a[b[c]]);return d};OpenWrap.obj.prototype.__getObj4Path=function(a,b){b=String(b).split(/\./g);for(var d=0;null!=a&&d<b.length;)a=a[b[d++]];return a};
OpenWrap.obj.prototype.searchArray=function(a,b,d,c,e){isUndefined(e)&&(e=getNumberOfCores());1>e&&(e=1);a=parallel4Array(a,function(a){var e=Object.keys(b),f;for(f in e){var g=e[f],m=ow.obj.__getObj4Path(a,g);if(d&&"string"==typeof b[g])if(b[g].match(/^([<>]=*)(\d+)/)){if(g=b[g].match(/^([<>]=*)(\d+)/),!((">="!=g[1]||g[2]<=m)&&(">"!=g[1]||g[2]<m)&&("<="!=g[1]||g[2]>=m)&&("<"!=g[1]||g[2]>m)))return}else{if(!String(m).match(new RegExp(b[g],c?"i":"")))return}else if(m!=b[g])return}return a},e,{});e=
[];for(var f in a)a[f]&&e.push(a[f]);return e};OpenWrap.obj.prototype.fromObj2Array=function(a,b){var d=[],c;for(c in a){var e=clone(a[c]);isDefined(b)&&(e[b]=c);d.push(e)}return d};OpenWrap.obj.prototype.filterKeys=function(a,b){var d={},c;for(c in a)d[a[c]]=b[a[c]];return d};OpenWrap.obj.prototype.fromArray2Obj=function(a,b,d){var c={},e;for(e in a){var f=clone(a[e]);isDefined(b)&&isDefined(f[b])?(c[f[b]]=f,d||delete f[b]):c["row"+e]=f}return c};
OpenWrap.obj.prototype.pool={create:function(){return{__pool:[],__factory:void 0,__close:void 0,__keepalive:void 0,__min:0,__max:0,__inc:1,__timeout:2E3,__keepaliveTime:0,__keepaliveThread:void 0,__retry:10,__currentFree:0,__currentSize:0,setRetry:function(a){this.__retry=a;return this},setTimeout:function(a){this.__timeout=a;return this},setMin:function(a){this.__min=a;return this},setMax:function(a){this.__max=a;return this},setIncrementsOf:function(a){this.__inc=a;return this},__checkFree:function(){var a=
!1,b=this,d=!1;sync(function(){d=0<b.__max&&b.__max<=b.__currentSize&&1>b.__currentFree?!1:!0},this.__currentSize);if(!d){if(1<=this.__retry){for(var c=0;c<this.__retry&&0==a;c++)sleep(this.__timeout),sync(function(){if(0<b.__currentFree||0<b.__max&&b.__max>b.__currentSize)a=!0},this.__currentSize);if(a)return!0}throw"Pool is full with "+this.__currentSize+" objects";}return!0},__checkLimits:function(){if(0>=this.__max)return!0;var a=!1,b=!1;this.__max>this.__currentSize&&(b=!0);b&&(a=!0);return a},
add:function(a,b){var d=this,c=!1;sync(function(){d.__checkLimits()&&(d.__currentSize++,d.__pool.push({inUse:b,obj:a}),b||d.__currentFree++,c=!0)},this.__currentSize);return c},setFactory:function(a,b,d){this.__factory=a;this.__close=b;this.__keepalive=d;var c=this;addOnOpenAFShutdown(function(){c.stop()});return this},setKeepalive:function(a){this.__keepaliveTime=a;var b=this;0<a?(plugin("Threads"),isDefined(this.__keepaliveThread)&&this.__keepaliveThread.stop(!0),this.__keepaliveThread=new Threads,
this.__keepaliveThread.addThread(function(){try{for(var a in b.__pool)b.__pool[a].inUse||b.__keepalive(b.__pool[a].obj)}catch(c){}}),this.__keepaliveThread.startWithFixedRate(1E3*a)):isDefined(this.__keepaliveThread)&&this.__keepaliveThread.stop(!0);return this},__createObj:function(a){var b;a=isUndefined(a)?!1:a;if(isDefined(this.__factory)){b=this.__factory();if(1<this.__inc)for(var d=0;d<this.__inc-1;d++)this.add(this.__factory());if(!this.add(b,a))return}return b},__getUnused:function(){var a=
void 0,b=0,d=this;sync(function(){for(;isUndefined(a)&&b<d.__currentSize;)0==d.__pool[b].inUse?(a=d.__pool[b].obj,d.__pool[b].inUse=!0,d.__currentFree--):b++},this.__currentSize);b>=d.__currentSize&&d.__checkFree()&&(a=d.__createObj(!0),isDefined(a)||(a=d.__getUnused()));return a},start:function(){for(var a=0;a<this.__min;a++)this.__createObj();return this},stop:function(){isDefined(this.__keepaliveThread)&&this.__keepaliveThread.stop(!0);if(isDefined(this.__close)){for(var a in this.__pool){try{this.__close(this.__pool[a].obj)}catch(b){}delete this.__pool[a];
this.__currentSize--}this.__currentFree=0;this.__pool=[]}},checkOut:function(){var a;a=this.__getUnused();if(isDefined(a))return a;throw"No available objects in pool.";},checkIn:function(a,b){var d=this;sync(function(){var c;for(c=0;c<d.__currentSize&&d.__pool[c].obj!=a;c++);if(0==b){try{d.__close(d.__pool[c].obj)}catch(e){}delete d.__pool[c];d.__currentSize--;loadUnderscore();d.__pool=_.compact(d.__pool);for(c=d.__currentSize;c<d.__min;c++)d.__createObj()}else d.__pool[c].inUse=!1,d.__currentFree++},
this.__currentSize);return this},use:function(a){var b;b=this.checkOut();if(isDefined(b)){var d;try{d=a(b)}catch(c){throw this.checkIn(b,!1),c;}this.checkIn(b,d)}else throw"No available objects in pool.";},setFactoryAF:function(a){this.setFactory(function(){var b=new AF(a);b.exec("Ping",{});return b},function(b){b.close()},function(b){b.exec("Ping",{})})},setFactoryRAIDDB:function(a,b){this.setFactory(function(){return getRAIDDB(a,b)},function(b){b.close()},function(b){b.q("select 1 from dual")})},
setFactoryDB:function(a,b,d,c){this.setFactory(function(){return new DB(a,b,d,c)},function(b){b.close()},function(b){b.q("select 1 from dual")})},setFactorySSH:function(a,b,d,c,e,f){this.setFactory(function(){plugin("SSH");return new SSH(a,b,d,c,e,f)},function(b){b.close()},function(b){b.exec("true")})}}},AF:function(a){var b=this.create();b.setFactoryAF(a);return b},RAIDDB:function(a,b){var d=this.create();d.setFactoryRAIDDB(a,b);return d},DB:function(a,b,d,c){var e=this.create();e.setFactoryDB(a,
b,d,c);return e},SSH:function(a,b,d,c,e,f){var g=this.create();g.setFactorySSH(a,b,d,c,e,f);return g}};
OpenWrap.obj.prototype.big={create:function(a){return{internalData:{},internalIndex:{},compressKeys:a,set:function(b,a,c){var d=this.getID(b),f=isUndefined(c)?nowUTC():c;if(!(0>=Object.keys(b))){c=this.__genHash(b);d=isDefined(d)?d:genUUID();this.internalData[d]=compress(a);isUndefined(this.internalIndex[c])&&(this.internalIndex[c]=[]);b=this.compressKeys?compress(b):b;a=!0;for(var g in this.internalIndex[c]){var h=this.internalIndex[c][g];h.u==d&&(a=!1,h.t=f,h.n=nowNano())}a&&this.internalIndex[c].push({u:d,
k:b,t:f,n:nowNano()});return d}},remove:function(b){var a=this.getID(b);b=this.__genHash(b);isDefined(a)&&(delete this.internalData[a],delete this.internalIndex[b])},setAll:function(b,a,c){var d=this;parallel4Array(a,function(a){d.set(ow.obj.filterKeys(b,a),a,c);return a})},__genHash:function(a){var b="",c=Object.keys(a).sort(),e;for(e in c)b+=a[c[e]];b+=b.length;return sha1(b)},__getIndex:function(){return this.internalIndex},__getData:function(){return this.internalData},getIndex:function(){return this.__getIndex()},
getSize:function(){return Object.keys(this.__getIndex()).length},getByID:function(a){return this.__getIndex()[a]},getID:function(a){var b=this.__getIndex()[this.__genHash(a)],c;for(c in b)if(this.compressKeys){if(compare(uncompress(b[c].k),a))return b[c].u}else if(compare(b[c].k,a))return b[c].u},getColsByID:function(a){if(!isUndefined(a))return uncompress(this.__getData()[a])},getAllByIDs:function(a){var b=[],c=this;parallel4Array(a,function(a){b.push(c.getColsByID(a));return a});return b},__getCols:function(a){return this.getColsByID(this.getID(a))},
get:function(a){return this.__getCols(a)},findIDs:function(a){var b=[],c=this;parallel4Array(a,function(a){b.push(c.getID(a))});return b},findByIDs:function(a){var b=[],c=this;parallel4Array(Object.keys(this.__getIndex()),function(d){var e=c.__getIndex()[d],g;for(g in e){var h;h=c.compressKeys?uncompress(e[g].k):e[g].k;a(h)&&b.push(e[g].u)}return d});return b},find:function(a){var b=[],c=this;parallel4Array(Object.keys(this.__getIndex()),function(d){var e=c.__getIndex()[d],g;for(g in e){var h;h=c.compressKeys?
uncompress(e[g].k):e[g].k;a(h)&&b.push(c.getColsByID(e[g].u))}return d});return b}}}};
OpenWrap.obj.prototype.fromJson=function(a){return{data:{},create:function(a){a instanceof Object||(a=jsonParse(a));this.data=a||{};return this},withObject:function(a,d){this.emptyPath(d)?this.data=this.mix(a,this.data):this.data=this.mixRecursive(a,this.data,d.split("."));return this},build:function(){return this.data},mixRecursive:function(a,d,c){var b=Array.from(c),f=b.shift();if(0===c.length)return this.mix(a,d);if(isObject(d[f])||"*"===f)if(isArray(d[f])||"*"===f)if("*"===f)for(var g in d)d.hasOwnProperty(g)&&
(d[g]=this.mixRecursive(a,d[g],b));else{"*"===b[0]&&b.shift();var h=this;d[f].forEach(function(c,e){d[f][e]=h.mixRecursive(a,d[f][e],b)})}else d[f]=this.mixRecursive(a,d[f],b);return d},mix:function(a,d){a=Object.create(a);for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b]);return a},emptyPath:function(a){return void 0===a||""===a?!0:!1}}.create(a)};
OpenWrap.obj.prototype.rest={get:function(a,b,d,c,e,f){plugin("HTTP");var g=new HTTP;if(isUndefined(d)&&isUndefined(c)){var h=new java.net.URL(a);null!=h.getUserInfo()&&(d=String(java.net.URLDecoder.decode(h.getUserInfo().substring(0,h.getUserInfo().indexOf(":")),"UTF-8")),c=String(java.net.URLDecoder.decode(h.getUserInfo().substring(h.getUserInfo().indexOf(":")+1),"UTF-8")))}isDefined(d)&&isDefined(c)&&g.login(d,c);try{return g.exec(a+ow.obj.rest.writeIndexes(b),"GET",void 0,f,void 0,e)}catch(k){throw k.message=
"Exception "+k.message+"; error = "+g.getErrorResponse(),k;}},jsonGet:function(a,b,d,c,e,f){return jsonParse(this.get(a,b,d,c,e,f).response)},create:function(a,b,d,c,e,f,g){plugin("HTTP");var h=new HTTP;if(isUndefined(c)&&isUndefined(e)){var k=new java.net.URL(a);null!=k.getUserInfo()&&(c=String(java.net.URLDecoder.decode(k.getUserInfo().substring(0,k.getUserInfo().indexOf(":")),"UTF-8")),e=String(java.net.URLDecoder.decode(k.getUserInfo().substring(k.getUserInfo().indexOf(":")+1),"UTF-8")))}isDefined(c)&&
isDefined(e)&&h.login(c,e);c=merge({"Content-Type":"application/json","content-type":"application/json"},g);try{return h.exec(a+ow.obj.rest.writeIndexes(b),"POST",stringify(d),c,void 0,f)}catch(l){throw l.message="Exception "+l.message+"; error = "+h.getErrorResponse(),l;}},jsonCreate:function(a,b,d,c,e,f,g){return jsonParse(this.create(a,b,d,c,e,f,g).response)},set:function(a,b,d,c,e,f,g){plugin("HTTP");var h=new HTTP;if(isUndefined(c)&&isUndefined(e)){var k=new java.net.URL(a);null!=k.getUserInfo()&&
(c=String(java.net.URLDecoder.decode(k.getUserInfo().substring(0,k.getUserInfo().indexOf(":")),"UTF-8")),e=String(java.net.URLDecoder.decode(k.getUserInfo().substring(k.getUserInfo().indexOf(":")+1),"UTF-8")))}isDefined(c)&&isDefined(e)&&h.login(c,e);c=merge({"Content-Type":"application/json","content-type":"application/json"},g);try{return h.exec(a+ow.obj.rest.writeIndexes(b),"PUT",stringify(d),c,void 0,f)}catch(l){throw l.message="Exception "+l.message+"; error = "+h.getErrorResponse(),l;}},jsonSet:function(a,
b,d,c,e,f){return jsonParse(this.set(a,b,d,c,e,f).response)},remove:function(a,b,d,c,e,f){plugin("HTTP");var g=new HTTP;if(isUndefined(d)&&isUndefined(c)){var h=new java.net.URL(a);null!=h.getUserInfo()&&(d=String(java.net.URLDecoder.decode(h.getUserInfo().substring(0,h.getUserInfo().indexOf(":")),"UTF-8")),c=String(java.net.URLDecoder.decode(h.getUserInfo().substring(h.getUserInfo().indexOf(":")+1),"UTF-8")))}isDefined(d)&&isDefined(c)&&g.login(d,c);try{return g.exec(a+ow.obj.rest.writeIndexes(b),
"DELETE",f,void 0,void 0,e)}catch(k){throw k.message="Exception "+k.message+"; error = "+g.getErrorResponse(),k;}},jsonRemove:function(a,b,d,c,e,f){return jsonParse(this.remove(a,b,d,c,e,f).response)},writeIndexes:function(a){var b="",d;for(d in a){var c=a[d];isObject(c)&&(c=JSON.stringify(c));b+="/"+encodeURIComponent(d)+"/"+encodeURIComponent(c)}return encodeURIComponent(b)}};
OpenWrap.obj.prototype.pmSchema={makeKey:function(a){"[object JavaObject]"!=Object.prototype.toString.call(a)&&(a=af.toJavaParameterMap(a));a=a.getParameterNames();for(var b=[];a.hasNext();){var d=a.next();b.push(d)}return b.sort().join(">-<")},sortMapKeys:function(a){for(var b in a)b.match(/\>\-\</)&&(a[b]=b.split(/\>\-\</).sort().join(">-<"));return a},__buildSchemaFromJavaArrayList:function(a){var b={};for(a=a.iterator();a.hasNext();){var d=a.next();switch(null!=d?String(d.getClass()).replace(/.+\.([^\.]+)/,
"$1"):"Null"){case "ArrayList":b=merge(b,ow.obj.pmSchema.__buildSchemaFromJavaArrayList(d));break;case "ParameterMap":b[ow.obj.pmSchema.makeKey(d)]=ow.obj.pmSchema.__buildSchemaFromJavaParameterMap(d)}}return b},__applySchemaToJavaArrayList:function(a,b){ow.loadFormat();for(var d=0;d<a.size();d++){var c=a.get(d),e;switch(null!=c?String(c.getClass()).replace(/.+\.([^\.]+)/,"$1"):"Null"){case "ArrayList":a.set(d,ow.obj.pmSchema.__applySchemaToJavaArrayList(c,b));break;case "ParameterMap":isUndefined(e)&&
(e=ow.obj.pmSchema.sortMapKeys(Object.keys(b))),a.set(d,ow.obj.pmSchema.__applySchemaToJavaParameterMap(c,b[ow.format.string.closest(ow.obj.pmSchema.makeKey(c),e)]))}}return a},__buildSchemaFromJavaParameterMap:function(a){for(var b={},d=a.getParameterNames();d.hasNext();){var c=d.next(),e=a.get(c),f;f=null!=e?String(e.getClass()).replace(/.+\.([^\.]+)/,"$1"):"Null";switch(f){case "ParameterMap":b[c]=ow.obj.pmSchema.__buildSchemaFromJavaParameterMap(e);break;case "ArrayList":b[c]=ow.obj.pmSchema.__buildSchemaFromJavaArrayList(e);
break;default:b[c]=f}}return b},__applySchemaToJavaParameterMap:function(a,b){for(var d=a.getParameterNames();d.hasNext();){var c=d.next(),e=a.get(c),f;f=null!=e?String(e.getClass()).replace(/.+\.([^\.]+)/,"$1"):"Null";switch(f){case "ParameterMap":isDefined(b[c])&&a.setParameter(c,ow.obj.pmSchema.__applySchemaToJavaParameterMap(a.getParameter(c),b[c]));break;case "ArrayList":isDefined(b[c])&&a.setArray(c,ow.obj.pmSchema.__applySchemaToJavaArrayList(a.getArray(c),b[c]));break;default:if(f!=b[c])switch(b[c]){case "String":a.setString(c,
e);break;case "Boolean":a.setBoolean(c,e);break;case "Double":a.setDouble(c,e);break;case "Long":a.setLong(c,e);break;case "Integer":a.setInt(c,e);break;case "DocumentFragmentImpl":a.setXml(c,e);break;case "Date":a.setDate(c,e);break;case "Null":a.setNull(c);break;case "Float":a.setFloat(c,e)}}}return a},getSchema:function(a){"[object JavaObject]"!=Object.prototype.toString.call(a)&&(a=af.toJavaParameterMap(a));return ow.obj.pmSchema.__buildSchemaFromJavaParameterMap(a)},applySchema:function(a,b){var d=
!0;"[object JavaObject]"!=Object.prototype.toString.call(a)&&(a=af.toJavaParameterMap(a),d=!1);"[object JavaObject]"==Object.prototype.toString.call(b)&&(b=af.fromJavaParameterMap(b));a=ow.obj.pmSchema.__applySchemaToJavaParameterMap(a,b);d||(a=af.fromJavaParameterMap(a));return a}};
