OpenWrap.server=function(){return ow.server};OpenWrap.server.prototype.checkIn=function(a,b,c,d){var f;isUndefined(d)&&(d=-1);isUndefined(a)&&(a="server.pid");(f=pidCheckIn(a))&&isDefined(c)&&addOnOpenAFShutdown(c);f||((f=b(a))?(pidCheckIn(a),isDefined(c)&&addOnOpenAFShutdown(c)):exit(d));return f};OpenWrap.server.prototype.processArguments=function(a,b,c){b=isDefined(b)?b:" ";c=isDefined(c)?c:"=";b=splitBySeparator(__expr,b);for(var d in b)a(b[d].match(c)?splitBySeparator(b[d],c):[b[d]])};
OpenWrap.server.prototype.daemon=function(a,b){isUndefined(a)&&(a=5E3);for(var c=!1;!c;)isDefined(b)&&(c=b()),c||sleep(a)};
OpenWrap.server.prototype.simpleCheckIn=function(a){if(!isUnDef(a)){var b=processExpr(),c=ow.server.checkIn(a+".pid",function(c){if(isDef(b.restart)||isDef(b.stop)||isDef(b.forcestop)){!isDef(b.forcestop)&&pidKill(ow.server.getPid(c),!1)||pidKill(ow.server.getPid(c),!0);var d=!pidCheck(c);if(isDef(b.restart)&&d)return log("Restarting "+a),!0;if(isDef(b.stop)||isDef(b.forcestop))d?(log("Stopped "+a),exit(0)):(log("Failed to stop "+a+" ("+c+")"),exit(-1))}isDef(b.status)&&(c=ow.server.getPid(c),d=pidCheck(c)?
"Running on":"Not running but registered with",isDef(c)&&log(d+" pid = "+c));return!1});isDef(b.status)&&c&&(log("Not running"),exit(0));__expr=__expr.replace(/( *)(start|stop|restart|status)( *)/i,"$1$3")}};OpenWrap.server.prototype.getPid=function(a){return io.readFileString(a)};
OpenWrap.server.prototype.jmx={localConnect:function(a){plugin("JMX");isUndefined(a)&&(a=getPid());return new JMX((new JMX).attach2Local(a).URL)},serverExec:function(a,b){a=b.apply(this,a);return stringify(a)},call:function(a,b,c){var d=a.getObject(b).exec(c,Array.prototype.slice.call(arguments).slice(3),[]);return jsonParse(d)},get:function(a,b,c){return a.getObject(b).get(c)},set:function(a,b,c,d){a.getObject(b).set(c,d)}};
OpenWrap.server.prototype.auth={aListOfAuths:{},initialize:function(a){this.aListOfAuths=a},dump:function(){return this.aListOfAuths},add:function(a,b){this.aListOfAuths[a]=sha1(b)},del:function(a){delete this.aListOfAuths[a]},check:function(a,b){return this.aListOfAuths[a]==sha1(b)}};
OpenWrap.server.prototype.ldap=function(a,b,c){var d=new java.util.Hashtable(5);isUnDef(b)&&isUnDef(c)&&d.put(javax.naming.Context.SECURITY_AUTHENTICATION,"none");d.put(javax.naming.Context.SECURITY_PRINCIPAL,b);d.put(javax.naming.Context.SECURITY_CREDENTIALS,Packages.wedo.openaf.AFCmdBase.afc.dIP(c));d.put(javax.naming.Context.INITIAL_CONTEXT_FACTORY,"com.sun.jndi.ldap.LdapCtxFactory");d.put(javax.naming.Context.PROVIDER_URL,a);this.ctx=new Packages.javax.naming.ldap.InitialLdapContext(d,null);this.ldap=
javax.naming.ldap.InitialLdapContext()};OpenWrap.server.prototype.ldap.prototype.search=function(a,b){var c=new javax.naming.directory.SearchControls;c.setSearchScope(javax.naming.directory.SearchControls.SUBTREE_SCOPE);a=this.ctx.search(a,b,c);for(b=[];a.hasMore();){for(var c={},d=a.next().getAttributes().getAll();d.hasMore();){for(var f=d.next(),g=[],e=f.getAll();e.hasMore();)g.push(e.next());c[f.getID()]=1==g.length?g[0]:g}b.push(c)}return b};
OpenWrap.server.prototype.ldap.prototype.searchStrings=function(a,b){var c=new javax.naming.directory.SearchControls;c.setSearchScope(javax.naming.directory.SearchControls.SUBTREE_SCOPE);c.setReturningAttributes(["*","+"]);a=this.ctx.search(a,b,c);for(b=[];a.hasMore();){for(var c={},d=a.next().getAttributes().getAll();d.hasMore();){for(var f=d.next(),g=[],e=f.getAll();e.hasMore();)g.push(String(e.next()));c[f.getID()]=1==g.length?g[0]:g}b.push(c)}return b};
OpenWrap.server.prototype.rest={reply:function(a,b,c,d,f,g){a=ow.server.rest.parseIndexes(a,b);var e={headers:{}};switch(b.method){case "GET":e.data=stringify(d(a),void 0,"");break;case "POST":e.data=stringify(c(a,jsonParse(b.files.postData)),void 0,"");e.headers.Location=ow.server.rest.writeIndexes(e.data);break;case "PUT":e.data=stringify(f(a,io.readFile(b.files.content)),void 0,"");break;case "DELETE":e.data=stringify(g(a),void 0,"")}e.mimetype=ow.server.httpd.mimes.JSON;return e},replyData:function(a,
b,c){return ow.server.rest.reply(a,b,function(a,b){return 0>=$stream(clone(c)).filter(a).count()?(a=merge(a,b),c.push(a),a):{}},function(a){return 0<$stream(clone(c)).filter(a).count()?$stream(clone(c)).filter(a).toArray()[0]:{}},function(a,b){0<$stream(clone(c)).filter(a).count()?c[c.indexOf($stream(clone(c)).filter(a).toArray()[0])]=b:c.push(b);return{}},function(a){return 0<$stream(clone(c)).filter(a).count()?(deleteFromArray(c,c.indexOf($stream(clone(c)).filter(a).toArray()[0])),a):{}})},parseIndexes:function(a,
b){var c=b.uri.replace(new RegExp("^"+a+"/*#*"),"").split("/");a={};for(var d=0;d<c.length;d+=2)0<c[d].length&&(a[decodeURIComponent(c[d])]=jsonParse(decodeURIComponent(c[d+1])));for(var f in b.params)!f.match(/^NanoHttpd\./)&&0<f.length&&(a[decodeURIComponent(f)]=jsonParse(decodeURIComponent(b.params[f])));isDefined(b.files)&&isDefined(b.files.postData)&&isDefined(b.header["content-type"])&&b.header["content-type"].match(/application\/json/i)&&(b=jsonParse(b.files.postData),a=merge(a,b));return a},
writeIndexes:function(a){return ow.loadObj().rest.writeIndexes(a)}};
OpenWrap.server.prototype.httpd={__routes:{},__defaultRoutes:{},__preRoutes:{},start:function(a,b,c,d,f){plugin("HTTPServer");isUndefined(a)&&(a=findRandomOpenPort());a=new HTTPd(a,b,c,d,f);this.__routes[a.getPort()]={};this.__defaultRoutes[a.getPort()]={};this.__preRoutes[a.getPort()]={};return a},getFromOpenAF:function(a,b,c){return this.getFromZip(getOpenAFJar(),a,b,c)},getFromZip:function(a,b,c,d){return getFromZip(a,b,c,d)},route:function(a,b,c,d,f){isUndefined(d)&&(d="/r/");isUndefined(b)&&
(b={});ow.loadFormat();var g=this,e=a.getPort()+0,h=String(d);this.__routes[e]=b;isDef(c)&&(this.__defaultRoutes[e]=c);isDef(f)&&(this.__preRoutes[e]=f);a.add(d,function(a){var b=a.uri.replace(new RegExp("^"+h),"");if(isFunction(g.__preRoutes[e]))g.__preRoutes[e](a);if(isFunction(g.__routes[e][b]))return g.__routes[e][b](a);b=ow.format.string.bestPrefix(b,Object.keys(g.__routes[e]));return isDef(b)?g.__routes[e][b](a):g.__defaultRoutes[e](a)});a.setDefault(d)},mapWithExistingRoutes:function(a,b){isUndefined(b)&&
(b={});var c={},d;for(d in b)c[d]=b[d];for(d in this.__routes[a.getPort()])c[d]=this.__routes[a.getPort()][d];return c},getDefaultRoute:function(a){if(!isUndefined(this.__defaultRoutes[a.getPort()]))return this.__defaultRoutes[a.getPort()]},stop:function(a){a.stop();delete this.__routes[a.getPort()];delete this.__defaultRoutes[a.getPort()];delete this.__preRoutes[a.getPort()]},mapRoutesWithLibs:function(a,b){isUndefined(b)&&(b={});b["/js/jquery.js"]=function(){return ow.server.httpd.replyJQuery(a)};
b["/js/backbone.js"]=function(){return ow.server.httpd.replyBackbone(a)};b["/js/handlebars.js"]=function(){return ow.server.httpd.replyHandlebars(a)};b["/js/stream.js"]=function(){return ow.server.httpd.replyStream(a)};b["/js/jlinq.js"]=function(){return ow.server.httpd.replyJLinq(a)};b["/js/underscore.js"]=function(){return ow.server.httpd.replyUnderscore(a)};b["/js/materialize.js"]=function(){return a.reply(ow.server.httpd.getFromOpenAF("js/materialize.js"),ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)};
b["/css/materialize.css"]=function(){return a.reply(ow.server.httpd.getFromOpenAF("css/materialize.css"),ow.server.httpd.mimes.CSS,ow.server.httpd.codes.OK)};b["/css/materialize-icon.css"]=function(){return a.reply(ow.server.httpd.getFromOpenAF("css/materialize-icon.css"),ow.server.httpd.mimes.CSS,ow.server.httpd.codes.OK)};b["/fonts/material-design-icons/Material-Design-Icons.eot"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/material-design-icons/Material-Design-Icons.eot",
!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/material-design-icons/Material-Design-Icons.svg"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/material-design-icons/Material-Design-Icons.svg",!0),ow.server.httpd.mimes.SVG,ow.server.httpd.codes.OK)};b["/fonts/material-design-icons/Material-Design-Icons.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/material-design-icons/Material-Design-Icons.ttf",!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};
b["/fonts/material-design-icons/Material-Design-Icons.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/material-design-icons/Material-Design-Icons.woff",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/material-design-icons/Material-Design-Icons.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/material-design-icons/Material-Design-Icons.woff2",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Bold.eot"]=
function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Bold.eot",!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Bold.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Bold.ttf",!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Bold.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Bold.woff",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};
b["/fonts/roboto/Roboto-Bold.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Bold.woff2",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Light.eot"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Light.eot",!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Light.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Light.ttf",
!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Light.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Light.woff",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Light.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Light.woff2",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Medium.eot"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Medium.eot",
!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Medium.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Medium.ttf",!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Medium.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Medium.woff",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Medium.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Medium.woff2",
!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Regular.eot"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Regular.eot",!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Regular.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Regular.ttf",!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Regular.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Regular.woff",
!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Regular.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Regular.woff2",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Thin.eot"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Thin.eot",!0),ow.server.httpd.mimes.EOT,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Thin.ttf"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Thin.ttf",
!0),ow.server.httpd.mimes.TTF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Thin.woff"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Thin.woff",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};b["/fonts/roboto/Roboto-Thin.woff2"]=function(){return a.replyBytes(ow.server.httpd.getFromOpenAF("fonts/roboto/Roboto-Thin.woff2",!0),ow.server.httpd.mimes.WOFF,ow.server.httpd.codes.OK)};return b},replyJQuery:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/jquery.js"),
ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyBackbone:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/backbone.js"),ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyHandlebars:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/handlebars.js"),ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyStream:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/stream.js"),ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyJLinq:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/jlinq.js"),
ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyUnderscore:function(a){return a.reply(ow.server.httpd.getFromOpenAF("js/underscore.js"),ow.server.httpd.mimes.JS,ow.server.httpd.codes.OK)},replyFile:function(a,b,c,d,f){isUndefined(f)&&(f=function(){return a.reply("Not found!",ow.server.httpd.mimes.TXT,ow.server.httpd.codes.NOTFOUND)});try{var g=String((new java.io.File(new java.io.File(b),(new java.net.URI(d.replace(new RegExp("^"+c),""))).getPath())).getCanonicalPath());return g.match(new RegExp("^"+
b))?a.replyBytes(io.readFileBytes(g),ow.server.httpd.getMimeType(g)):f(a,b,c,d)}catch(e){return f(a,b,c,d,e)}},replyRedirect:function(a,b){return a.reply("","text/plain",303,{Location:b})},getMimeType:function(a){a=String(Packages.org.apache.commons.io.FilenameUtils.getExtension(a)).toUpperCase();return isDefined(ow.server.httpd.mimes[a])?ow.server.httpd.mimes[a]:"application/octet-stream"},authBasic:function(a,b,c,d,f,g){isUndefined(g)&&(g=function(a,b){return a.reply("Not authorized.","text/plain",
ow.server.httpd.codes.UNAUTHORIZED)});if(isDefined(c.header.authorization)){var e=af.fromBytes2String(af.fromBase64(c.header.authorization.replace(/^Basic /,""))).split(":");if(d(e[0],e[1],b,c))return f(b,c)}c=g(b,c);isUndefined(c.header)&&(c.header={});c.header["WWW-Authenticate"]='Basic realm="'+a+'"';return b.reply(c.data,c.mimetype,ow.server.httpd.codes.UNAUTHORIZED,c.header)},addMimeType:function(a,b){mimes(a.toUpperCase(),b)},addHTTPCode:function(a,b){codes(a.toUpperCase(),b)},codes:{OK:200,
BAD:400,UNAUTHORIZED:401,FORBIDDEN:403,NOTFOUND:404,INTERNAL:500},mimes:{HTML:"text/html",CSS:"text/css",JS:"application/javascript",JSON:"application/json",JAR:"application/java-archive",ZIP:"application/zip",XML:"application/xml",TXT:"text/plain",RTF:"text/richtext",JPG:"image/jpeg",PNG:"image/png",GIF:"image/gif",TTF:"font/truetype",WOFF:"application/x-font-woff",SVG:"image/svg+xml",EOT:"application/vnd.ms-fontobject",BIN:"application/octet-stream"}};
