OpenWrap.oJob=function(){startLog();this.__host="local";this.__ip="127.0.0.1";try{this.__host=String(java.net.InetAddress.getLocalHost().getHostName()),this.__ip=String(java.net.InetAddress.getLocalHost().getHostAddress())}catch(a){logErr(a)}this.__id=sha256(this.__host+this.__ip);this.__threads={};this.__ojob={log:!0,logArgs:!1,numThreads:void 0};this.__expr=processExpr(" ");plugin("Threads");ow.loadFormat();this.getTodoCh().create();this.getJobsCh().create();this.getLogCh().create();this.getMainCh().create();
this.getMainCh().set({uuid:this.__id},{uuid:this.__id,host:this.__host,ip:this.__ip});return ow.oJob};
OpenWrap.oJob.prototype.load=function(a,b,c,h,d){isUnDef(a)&&(a=[]);isUnDef(b)&&(b=[]);isDef(c)&&(this.__ojob=merge(this.__ojob,c));for(var g in b)if(isDef(c)&&isDef(c.sequential)&&c.sequential&&0<g){var m=$from(a).equals("name",isObject(b[g])?b[g].name:b[g]).first();isDef(m)&&(isUnDef(m.deps)&&(m.deps=[]),m.deps.push(isObject(b[g-1])?b[g-1].name:b[g-1]))}for(g in a)this.addJob(this.getJobsCh(),a[g].name,a[g].deps,a[g].type,a[g].typeArgs,a[g].args,a[g].exec,a[g].from,a[g].to,a[g].help);this.addTodos(b,
h,d);isDef(c.numThreads)&&(this.__ojob.numThreads=c.numThreads);if(isDef(this.__ojob.channels)&&this.__ojob.channels.expose&&isDef(this.__ojob.channels.port)&&isUnDef(this.__hs)){this.__hs=ow.loadServer().httpd.start(this.__ojob.channels.port,this.__ojob.channels.host,this.__ojob.channels.keyStorePath,this.__ojob.channels.keyPassword);var e=this;a=function(a,b,d,c){isUnDef(e.__ojob.channels.permissions)?c.channelPermission="r":c.channelPermission=e.__ojob.channels.permissions;return!0};isDef(e.__ojob.channels.auth)&&
(a=function(a,b,d,c){isUnDef(e.__ojob.channels.permissions)?c.channelPermission="r":c.channelPermission=e.__ojob.channels.permissions;a=$from(e.__ojob.channels.auth).equals("login",a).at(0);return isDef(a)&&isDef(a.pass)&&b==a.pass?(isDef(a.permissions)&&(c.channelPermission=a.permissions),!0):!1});isUnDef(this.__ojob.channels.list)&&(this.__ojob.channels.list=$ch().list(),this.__ojob.channels.list.push("__log"));for(g in this.__ojob.channels.list)$ch(this.__ojob.channels.list[g]).expose(this.__hs,
void 0,a)}};OpenWrap.oJob.prototype.loadJSON=function(a){if(!isObject(a))return{};if(isDef(a.include)&&isArray(a.include))for(var b in a.include)a.include[b].match(/\.js$/i)&&load(a.include[b]),a.include[b].match(/\.yaml$/i)&&(a=this.__merge(this.__loadFile(a.include[b]),a));if(!isArray(a.ojob)&&!isArray(a.todo))throw"ojob and todo entries need to be defined as arrays.";return a};
OpenWrap.oJob.prototype.__merge=function(a,b){var c={include:[],jobs:[],todo:[],ojob:{}};isDef(a.include)?c.include=a.include.concat(isDef(b.include)?b.include:[]):c.include=isDef(b.include)?b.include:[];isDef(a.jobs)?c.jobs=a.jobs.concat(isDef(b.jobs)?b.jobs:[]):c.jobs=isDef(b.jobs)?b.jobs:[];isDef(a.todo)?c.todo=a.todo.concat(isDef(b.todo)?b.todo:[]):c.todo=isDef(b.todo)?b.todo:[];isDef(a.ojob)?c.ojob=merge(a.ojob,b.ojob):c.ojob=isDef(b.ojob)?b.ojob:{};return c};
OpenWrap.oJob.prototype.__loadFile=function(a){function b(b){var d={};try{return d=b(a)}catch(m){if(m.message.match(/FileNotFoundException/)){var c=getOPackPaths();for(i in c)try{return c[i]=c[i].replace(/\\+/g,"/"),c[i]=c[i].replace(/\/+/g,"/"),d=b(c[i]+"/"+a)}catch(e){if(!e.message.match(/FileNotFoundException/))throw e;}throw"File not found! ("+a+")";}throw m;}}var c={};isDef(a)&&(a.match(/\.js$/i)&&(c=this.__merge(b(io.readFile),c)),a.match(/\.yaml$/i)&&(c=this.__merge(b(io.readFileYAML),c)));
return this.loadJSON(c)};OpenWrap.oJob.prototype.loadFile=function(a,b,c){a=this.__loadFile(a);isDef(a)&&this.load(a.jobs,a.todo,a.ojob,b,c)};OpenWrap.oJob.prototype.runFile=function(a,b,c){this.loadFile(a,b,c);this.start(b,!0,c)};OpenWrap.oJob.prototype.previewFile=function(a){return this.__loadFile(a)};OpenWrap.oJob.prototype.getJobsCh=function(){return $ch("oJob::jobs")};OpenWrap.oJob.prototype.getTodoCh=function(){return $ch("oJob::todo")};OpenWrap.oJob.prototype.getLogCh=function(){return $ch("oJob::log")};
OpenWrap.oJob.prototype.getMainCh=function(){return $ch("oJob::oJob")};OpenWrap.oJob.prototype.getID=function(){return this.__id};OpenWrap.oJob.prototype.setJob=function(a,b){this.getJobsCh().set(a,b);return this};OpenWrap.oJob.prototype.removeJob=function(a){this.getJobsCh().unset(a);return this};
OpenWrap.oJob.prototype.addTodos=function(a,b,c){var h=isDef(c)?c:"",d;for(d in a)isDef(b)&&isObject(a[d])&&(a[d].args=this.__processArgs(a[d].args,b,c)),isObject(a[d])?this.addTodo(this.getID()+h,this.getJobsCh(),this.getTodoCh(),a[d].name,a[d].args,a[d].type,a[d].typeArgs):this.addTodo(this.getID()+h,this.getJobsCh(),this.getTodoCh(),a[d],void 0,void 0,b);return this};
OpenWrap.oJob.prototype.__addLog=function(a,b,c,h,d,g){g=isDef(g)?g:"";var m={ojobId:this.__id+g,name:b,start:!1,error:!1,success:!1,deps:!1,count:0,totalTime:0,avgTime:0,log:[]},e=this.getLogCh().get({ojobId:this.__id+g,name:b});isUnDef(e)&&(m.createDate=now(),e=m);e.lastModify=now();c=isUnDef(c)?genUUID():c;switch(a.toLowerCase()){case "start":e.start=!0;e.deps=!0;e.log.push({id:c,startTime:now()});break;case "success":e.success=!0;e.count++;a=$from(e.log).equals("id",c).at(0);a.endTime=now();e.totalTime+=
a.endTime-a.startTime;e.avgTime=e.totalTime/e.count;break;case "error":e.error=!0;e.count++;a=$from(e.log).equals("id",c).at(0);a.error=d;a.endTime=now();e.totalTime+=a.endTime-a.startTime;e.avgTime=e.totalTime/e.count;break;case "depsfail":e.deps=!1;break;default:e=void 0}if(isDef(e)){d="";isDef(h)&&this.__ojob.logArgs&&(d=clone(h),delete d.objId,delete d.execid,d="["+e.name+"] | "+JSON.stringify(d)+"\n");try{a=h="";plugin("Console");var k=(new Console).getConsoleReader(),n=k.getTerminal().getWidth(),
f=k.getTerminal().isAnsiSupported()&&null!=java.lang.System.console(),l=JavaImporter(Packages.org.fusesource.jansi);f?(l.AnsiConsole.systemInstall(),h=repeat(n,"-")+"\n",a=repeat(n,"=")):(h=repeat(80,"-")+"\n",a=repeat(80,"=")+"\n");var k=function(a){return f?l.Ansi.ansi().boldOff().fg(l.Ansi.Color.GREEN).a(a).a(l.Ansi.Attribute.RESET):a},n=function(a){return f?l.Ansi.ansi().boldOff().a(a).a(l.Ansi.Attribute.RESET):a},m=function(a){return f?l.Ansi.ansi().bold().a(a).a(l.Ansi.Attribute.RESET):a},q=
function(a){return f?l.Ansi.ansi().bold().fg(l.Ansi.Color.RED).a(a).a(l.Ansi.Attribute.RESET):a};if("oJob Log"!=e.name){var p="["+e.name+"] | ";!e.start||e.error||e.success||printnl(m(p+"STARTED | "+new Date)+"\n"+n(d)+k(h));e.start&&e.error&&printErr("\n"+q(a)+n(d)+m(p+"Ended in ERROR  | "+new Date)+"\n"+stringify(e)+"\n"+q(a));e.start&&e.success&&(printnl("\n"+k(a)),print(n(d)+m(p+"Ended with SUCCESS | "+new Date)+"\n"))}}catch(r){logErr(r)}finally{f&&l.AnsiConsole.systemUninstall()}1E3<e.log.length&&
e.log.shift();this.getLogCh().set({ojobId:this.__id+g,name:b},e)}return c};OpenWrap.oJob.prototype.stop=function(){this.getLogCh().waitForJobs(2E3);for(var a in this.__threads)for(var b in this.__threads[a])this.__threads[a][b].stop();stopLog()};OpenWrap.oJob.prototype.__processArgs=function(a,b,c){var h={};isDef(a)&&(isArray(a)?h=merge(h,{__oJobRepeat:a}):isObject(a)?h=merge(h,a):isString(a)&&(h=merge(h,this.__processArgs(eval(a)))));isDef(b)&&(h=merge(h,this.__processArgs(b)));h.__id=c;return h};
OpenWrap.oJob.prototype.start=function(a,b,c){var h=isDef(a)?this.__processArgs(a,this.__expr,c):this.__expr,d=this;this.__ojob!={}&&(isUnDef(this.__ojob.timeInterval)&&(this.__ojob.timeInterval=2E3),isUnDef(this.__ojob.unique)&&(this.__ojob.unique={}),this.__ojob.unique!={}&&this.__ojob.daemon&&(isUnDef(this.__ojob.unique.pidFile)&&(this.__ojob.unique.pidFile="ojob.pid"),isUnDef(this.__ojob.unique.killPrevious)&&(this.__ojob.unique.killPrevious=!1),ow.loadServer().checkIn(this.__ojob.unique.pidFile,
function(a){return d.__ojob.unique.killPrevious||isDef(h.stop)||isDef(h.restart)?(pidKill(ow.server.getPid(a),!1)||pidKill(ow.server.getPid(a),!0),isDef(h.stop)?!1:!0):!1})));a=new Threads;var d=this,g=isDef(c)?c:"";a.addThread(function(){for(var a=void 0,b=!1;!b;){try{if($from(d.getTodoCh().getKeys()).equals("ojobId",d.getID()+g).any()){var k=d.getTodoCh().get($from(d.getTodoCh().getKeys()).equals("ojobId",d.getID()+g).first()),a=d.getJobsCh().get({name:k.name}),n=h;isDef(k.args)&&(n=d.__processArgs(h,
k.args,c));isDef(a)?1==d.runJob(a,n,c)&&d.getTodoCh().unset({ojobId:k.ojobId,todoId:k.todoId},k):(logErr("Job "+k.name+" not found!"),d.getTodoCh().unset({ojobId:k.ojobId,todoId:k.todoId}))}if(!(b||isDef(d.__ojob)&&isDef(d.__ojob.daemon)&&1==d.__ojob.daemon)&&$from(d.getTodoCh().getKeys()).equals("ojobId",d.getID()+g).none()){b=!0;try{d.stop()}catch(f){}}}catch(f){logErr(f),isDef(f.javaException)&&f.javaException.printStackTrace()}isDef(d.__ojob)&&1==d.__ojob.daemon?sleep(isDef(d.__ojob.timeInterval)?
d.__ojob.timeInterval:100):sleep(100)}});a.start();try{a.waitForThreads(2500),a.stop()}catch(m){}};OpenWrap.oJob.prototype.run=function(a,b){this.start(a,!0,b)};
OpenWrap.oJob.prototype.runJob=function(a,b,c){function h(a,b,c,d){var e=new Function("var args = arguments[0]; var job = arguments[1]; var id = arguments[2]; "+a);if(isDef(b.__oJobRepeat)){var f=[];parallel4Array(b.__oJobRepeat,function(a){try{return e(a,c,d)}catch(t){f.push(t)}},g.__ojob.numThreads);if(0<f.length)throw f.join(", ");}else e(b,c,d)}var d=isDef(b)?this.__processArgs(b,void 0,c):{},g=this,m=isDef(c)?c:"";b=!0;if(isDef(a.deps))for(var e in a.deps)b&&(b=a.deps[e],b=this.getLogCh().get({ojobId:this.getID()+
m,name:b}),isDef(b)&&b.success?b=!0:(b=!1,this.__addLog("depsFail",a.name,void 0,d,void 0,c)));if(b){d.objId=this.getID()+m;var k=this.__addLog("start",a.name,void 0,d,void 0,c);d.execid=k;d=merge(d,a.args);switch(a.type){case "single":try{h(a.exec,d,a,m),this.__addLog("success",a.name,k,d,void 0,c)}catch(f){this.__addLog("error",a.name,k,d,f,c)}break;case "jobs":if(isDef(a.typeArgs.file))try{if(isDef(d.__oJobRepeat)){var n=[];parallel4Array(d.__oJobRepeat,function(b){try{return g.runFile(a.typeArgs.file,
b,a.typeArgs.file+md5(stringify(b))),b}catch(l){n.push({k:b,e:l})}},g.__ojob.numThreads);if(0<n.length)throw stringify(n);}else g.runFile(a.typeArgs.file,d,a.typeArgs.file);this.__addLog("success",a.name,k,d,void 0,c)}catch(f){this.__addLog("error",a.name,k,d,f,c)}else this.__addLog("error",a.name,k,d,"No typeArgs.file provided.",c);break;case "shutdown":addOnOpenAFShutdown(function(){try{h(a.exec,d,a,m),g.__addLog("success",a.name,k,void 0,c)}catch(f){g.__addLog("error",a.name,k,d,f,c)}});break;
case "periodic":e=new Threads,e.addThread(function(){if(isDefined(a.typeArgs.cron)&&!ow.format.cron.isCronMatch(new Date,a.typeArgs.cron))return!1;k=g.__addLog("start",a.name,void 0,d,c);d.execid=k;try{h(a.exec,d,a,m),g.__addLog("success",a.name,k,d,void 0,c)}catch(f){g.__addLog("error",a.name,k,d,f,c)}return!0}),isDef(this.__threads[a.name])?g.__threads[a.name].push(e):g.__threads[a.name]=[e],isUnDef(a.typeArgs)&&(a.typeArgs={}),isUnDef(a.typeArgs.timeInterval)&&(a.typeArgs.timeInterval=2E3),isDef(a.typeArgs.waitForFinish)&&
a.typeArgs.waitForFinish?e.startWithFixedRate(a.typeArgs.timeInterval):e.startAtFixedRate(a.typeArgs.timeInterval)}}else return!1;return!0};
OpenWrap.oJob.prototype.addJob=function(a,b,c,h,d,g,m,e,k,n){isUnDef(c)&&(c=[]);isUnDef(h)&&(h="single");isUnDef(m)&&(m=function(){});isUnDef(n)&&(n="");var f={};m=m.toString();if(isDef(e)){var l=a.get({name:e});isDef(l)?(f.type=l.type,f.typeArgs=l.typeArgs,f.args=l.args,f.deps=l.deps,f.exec=l.exec,f.help=l.help):logWarn("Didn't found dep job '"+e+"' for job '"+b+"'")}f={name:b,type:h,typeArgs:isDef(f.typeArgs)?merge(f.typeArgs,d):d,args:isDef(f.args)?this.__processArgs(f.args,g):this.__processArgs(g),
deps:isDef(f.deps)?f.deps.concat(c):c,exec:(isDef(f.exec)?f.exec:"")+m,help:(isDef(f.help)?f.help:"")+n,from:e,to:k};isDef(k)&&(l=a.get({name:k}),isDef(l)&&(f.type=isDef(l.type)?l.type:f.type,f.typeArgs=isDef(l.typeArgs)?merge(f.typeArgs,l.typeArgs):f.typeArgs,f.args=isDef(l.args)?this.__processArgs(f.args,l.args):this.__processArgs(f.args),f.deps=isDef(l.deps)?f.deps.concat(l.deps):f.deps,f.exec+=isDef(l.exec)?l.exec:"",f.help+=isDef(l.help)?l.help:""));a.set({name:b},f)};
OpenWrap.oJob.prototype.addTodo=function(a,b,c,h,d,g,m){var e=genUUID(),k=b.get({name:h});if(isUnDef(k)||k=={})throw"Job '"+h+"' wasn't found.";b=isUnDef(g)?k.type:g;g=isUnDef(g)?k.typeArgs:m;c.set({ojobId:a,todoId:e},{ojobId:a,todoId:e,name:h,args:d,type:b,typeArgs:g});return e};ow.oJob=new OpenWrap.oJob;
