OpenWrap.ch=function(){return ow.ch};OpenWrap.ch.prototype.subscribers={};OpenWrap.ch.prototype.jobs={};OpenWrap.ch.prototype.vers={};OpenWrap.ch.prototype.channels={};OpenWrap.ch.prototype.type={};
OpenWrap.ch.prototype.__types={big:{__channels:{},create:function(a,b){this.__channels[a]=ow.loadObj().big.create(b)},destroy:function(a){delete this.__channels[a]},size:function(a){return this.__channels[a].getSize()},forEach:function(a,b){var c=this;this.__channels[a].find(function(e){b(e,c.get(a,e));return e})},getKeys:function(a,b){var c=[];if(b){a=this.__channels[a].getIndex();for(var e in a)c=c.concat(a[e])}else this.__channels[a].find(function(a){sync(function(){c.push(a)},c)});return c},getSortedKeys:function(a,
b){var c=[];a=this.__channels[a].getIndex();for(var e in a)c=c.concat(a[e]);a=$from($stream(c).sort(function(a,b){return a.t==b.t?a.n<b.n?-1:0:a.t<b.t?-1:1}).toArray());return b?a.select():a.select(function(a){return a.k})},getSet:function(a,b,c,e,f){var g;g=this.__channels[a].get(c);if($stream([g]).anyMatch(b))return this.__channels[a].set(c,e,f)},set:function(a,b,c,e){return this.__channels[a].set(b,c,e)},setAll:function(a,b,c,e){this.__channels[a].setAll(b,c,e)},get:function(a,b){return this.__channels[a].get(b)},
pop:function(a){a=$from($stream(this.getKeys(a,!0)).sort(function(a,c){return a.t==c.t?a.n<c.n?-1:0:a.t<c.t?-1:1}).reverse().toArray()).at(0);return isDef(a)?a.k:{}},shift:function(a){a=$from($stream(this.getKeys(a,!0)).sort(function(a,c){return a.t==c.t?a.n<c.n?-1:0:a.t<c.t?-1:1}).toArray()).at(0);return isDef(a)?a.k:{}},unset:function(a,b){this.__channels[a].remove(b)}},db:{__db:{},__table:{},create:function(a,b,c){isDef(c)&&isDef(c.db)?this.__db[a]=c.db:this.__db[a]=createDBInMem(a,!1,void 0,void 0,
!1,!0);isDef(c)&&isDef(c.tableName)?this.__table[a]=c.tableName:this.__table[a]="ch_"+a;b=4E3;isDef(c)&&isDef(c.keySize)&&(b=c.keySize);try{this.__db[a].q("select count(key) from "+this.__table[a])}catch(e){this.__db[a].u("CREATE TABLE "+this.__table[a]+" (key varchar2("+b+") primary key, ts number(15), value clob)")}},destroy:function(a){this.__db[a].close();this.__db=deleteFromArray(this.__db,this.__db.indexOf(a))},size:function(a){return Number(this.__db[a].q("select count(key) c from "+this.__table[a]).results[0].C)},
forEach:function(a,b,c){c=this.getKeys(a);for(j in c)b(c[j],this.get(a,c[j]))},getKeys:function(a,b){a=$stream(this.__db[a].q("select key from "+this.__table[a]).results).map("KEY").toArray();b=[];for(j in a)b.push(JSON.parse(a[j]));return b},getSortedKeys:function(a,b){a=$stream(this.__db[a].q("select key from "+this.__table[a]+" order by ts").results).map("KEY").toArray();b=[];for(j in a)b.push(JSON.parse(a[j]));return b},getSet:function(a,b,c,e,f){var g;try{g=this.__db[a].qs("select key from "+
this.__table[a]+" where key = ? for update",[stringify(c)],!0).results[0].KEY,isDef(g)&&$stream([JSON.parse(g)]).anyMatch(b)&&this.set(a,c,e,f),this.__db[a].commit()}catch(h){throw this.__db[a].rollback(),h;}},set:function(a,b,c,e,f){f=this.get(a,b);try{isDef(f)?this.__db[a].us("update "+this.__table[a]+" set value = ?, ts = ? where key = ?",[stringify(c),e,stringify(b)],!0):this.__db[a].us("insert into "+this.__table[a]+" (key, ts, value) values (?, ?, ?)",[stringify(b),e,stringify(c)],!0),this.__db[a].commit()}catch(g){throw this.__db[a].rollback(),
g;}},setAll:function(a,b,c,e){for(var f in c)this.set(a,ow.loadObj().filterKeys(b,c[f]),c[f],e)},get:function(a,b,c){var e;try{e=JSON.parse(this.__db[a].qs("select value from "+this.__table[a]+" where key = ?",[stringify(b)],!0).results[0].VALUE)}catch(f){}return e},pop:function(a){var b=this.getSortedKeys(a),b=b[b.length-1];this.get(a,b);return b},shift:function(a){var b=this.getSortedKeys(a)[0];this.get(a,b);return b},unset:function(a,b,c){try{this.__db[a].us("delete "+this.__table[a]+" where key = ?",
[stringify(b)],!0),this.__db[a].commit()}catch(e){throw this.__db[a].rollback(),e;}}},ops:{__ops:{},create:function(a,b,c){this.__ops[a]=c},destroy:function(a){delete this.__ops[a]},size:function(a){return Object.keys(this.__ops[a]).length},forEach:function(a,b,c){var e=this.getKeys(a),f;for(f in e)b(e[f].key,this.get(a,e[f],c))},getKeys:function(a,b){return Object.keys(this.__ops[a])},getSortedKeys:function(a,b){return this.getKeys(a,b).sort()},getSet:function(a,b,c,e,f){},set:function(a,b,c,e,f){if(isDef(this.__ops[a][b.key]))return this.__ops[a][b.key](c,
f)},setAll:function(a,b,c,e){},get:function(a,b,c){return this.set(a,b,{},void 0,c)},pop:function(a){},shift:function(a){},unset:function(a,b,c){}},cache:{__cacheFunc:{},__cacheCh:{},__cacheTTL:{},create:function(a,b,c){this.__cacheFunc[a]=isDef(c.func)?c.func:function(){return{}};this.__cacheTTL[a]=isDef(c.ttl)?c.ttl:5E3;isUnDef(c.ch)?($ch(a+"::__cache").create(),this.__cacheCh[a]=$ch(a+"::__cache")):this.__cacheCh[a]=c.ch},destroy:function(a){isDef(this.__cacheFunc[a])&&delete this.__cacheFunc[a];
isDef(this.__cacheCh[a])&&delete this.__cacheCh[a];isDef(this.__cacheTTL[a])&&delete this.__cacheTTL[a];$ch(a+"::__cache").destroy()},size:function(a){return this.__cacheCh[a].size()},forEach:function(a,b,c){var e=this.getKeys(a),f;for(f in e)b(e[f],this.get(a,e[f],c))},getKeys:function(a,b){return this.__cacheCh[a].getKeys(b)},getSortedKeys:function(a,b){return this.getKeys(a,b).sort()},getSet:function(a,b,c,e,f){c=this.get(a,aKey);if($stream([c]).anyMatch(b))return this.set(a,aKey,aValue,f)},set:function(a,
b,c,e,f){this.__cacheCh[a].set(b,this.__cacheFunc[a](b),e,f)},setAll:function(a,b,c,e){c=[];for(var f in b)c[f]=this.__cacheFunc[a](aK);this.__cacheCh[a].setAll(b,c,e)},get:function(a,b){var c;c=$stream(this.getKeys(a,!0)).filter({k:b}).toArray()[0];isDef(c)?c.t>now()-this.__cacheTTL[a]||(c=this.__cacheFunc[a](b),this.__cacheCh[a].set(b,c)):(c=this.__cacheFunc[a](b),this.__cacheCh[a].set(b,c));return c=this.__cacheCh[a].get(b)},pop:function(a){var b=this.getSortedKeys(a),b=b[b.length-1];this.get(a,
b);return b},shift:function(a){var b=this.getSortedKeys(a)[0];this.get(a,b);return b},unset:function(a,b,c){this.__cacheCh[a].unset(b)}},remote:{__channels:{},create:function(a,b,c){ow.loadObj();this.__channels[a]=c},destroy:function(a){delete this.__channels[a]},size:function(a){return this.getKeys(a).length},forEach:function(a,b){var c=this.getKeys(a),e;for(e in c)b(c[e],this.get(a,c[e]))},getAll:function(a,b){return ow.obj.rest.jsonGet(this.__channels[a].url,{o:"a"},this.__channels[a].login,this.__channels[a].password,
this.__channels[a].timeout).r},getKeys:function(a,b){return ow.obj.rest.jsonGet(this.__channels[a].url,{o:"k"},this.__channels[a].login,this.__channels[a].password,this.__channels[a].timeout).r},getSortedKeys:function(a,b){return ow.obj.rest.jsonGet(this.__channels[a].url,{o:"s"},this.__channels[a].login,this.__channels[a].password,this.__channels[a].timeout).r},getSet:function(a,b,c,e,f){return ow.obj.rest.jsonSet(this.__channels[a].url,{o:"es",m:b,k:c,t:f},e,this.__channels[a].login,this.__channels[a].password,
this.__channels[a].timeout).r},set:function(a,b,c,e){return ow.obj.rest.jsonSet(this.__channels[a].url,{o:"e",k:b,t:e},c,this.__channels[a].login,this.__channels[a].password,this.__channels[a].timeout).r},setAll:function(a,b,c,e){return ow.obj.rest.jsonSet(this.__channels[a].url,{o:"a",k:b,t:e},c,this.__channels[a].login,this.__channels[a].password,this.__channels[a].timeout).r},get:function(a,b){return ow.obj.rest.jsonGet(this.__channels[a].url,{o:"e",k:b},this.__channels[a].login,this.__channels[a].password,
this.__channels[a].timeout).r},pop:function(a){var b=this.getSortedKeys(a),b=b[b.length-1];this.get(a,b);return b},shift:function(a){var b=this.getSortedKeys(a)[0];this.get(a,b);return b},unset:function(a,b,c){return ow.obj.rest.jsonRemove(this.__channels[a].url,{o:"e",k:b,t:c},this.__channels[a].login,this.__channels[a].password,this.__channels[a].timeout)}},ignite:{create:function(a,b,c){plugin("Ignite");isUnDef(c)||isUnDef(c.ignite)?this.__ig=new Ignite:this.__ig=c.ignite;isUnDef(c)||isUnDef(c.gridName)?
this.__ig.start():this.__ig.start(c.gridName);this.__ig.getIgnite().getOrCreateCache(a)},destroy:function(a){this.__ig.getIgnite().getCache(a).destroy()},size:function(a){return this.__ig.getIgnite().getCache(a).size([Packages.org.apache.ignite.cache.CachePeekMode.ALL])},forEach:function(a,b){for(var c=this.getKeys(a);o in c;)b(o,this.get(a,o))},getKeys:function(a,b){a=this.__ig.getIgnite().getCache(a).primaryKeySet().iterator();for(b=[];a.hasNext();)b.push(af.fromJavaMap(a.next()));return b},getSortedKeys:function(a,
b){return this.getKeys(a,b)},getSet:function(a,b,c,e,f){f=this.__ig.getIgnite().transactions().txStart();try{var g=this.__ig.getIgnite().getCache(a),h=af.fromJavaMap(g.get(af.toJavaMap(c)));$stream([h]).anyMatch(b)?(g.put(af.toJavaMap(c),af.toJavaMap(e)),f.commit()):f.rollback()}catch(l){throw f.rollback(),l;}},set:function(a,b,c,e){return this.__ig.getIgnite().getCache(a).put(af.toJavaMap(b),af.toJavaMap(c))},setAll:function(a,b,c,e){for(var f in c)this.set(a,ow.loadObj().filterKeys(b,c[f]),c[f],
e)},get:function(a,b){a=this.__ig.getIgnite().getCache(a);return af.fromJavaMap(a.get(af.toJavaMap(b)))},pop:function(a){var b=this.getSortedKeys(a),b=b[b.length-1];this.get(a,b);return b},shift:function(a){var b=this.getSortedKeys(a)[0];this.get(a,b);return b},unset:function(a,b){this.__ig.getIgnite().getCache(a).remove(af.toJavaMap(b))}}};
OpenWrap.ch.prototype.create=function(a,b,c,e){0>Object.keys(this.channels).indexOf(a)&&(plugin("Threads"),c=isDef(c)?c:"big",this.__types[c].create(a,b,e),this.subscribers[a]={},this.jobs[a]=[],this.channels[a]=c,this.vers[a]=nowUTC());return this};OpenWrap.ch.prototype.getVersion=function(a){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";return this.vers[a]};
OpenWrap.ch.prototype.waitForJobs=function(a,b){isUnDef(b)&&(b=2500);for(var c in ow.ch.jobs[a])ow.ch.jobs[a][c].waitForThreads(b);return this};OpenWrap.ch.prototype.stopAllJobs=function(a){for(var b in ow.ch.jobs[a])ow.ch.jobs[a][b].stop();return this};OpenWrap.ch.prototype.list=function(){return Object.keys(this.channels)};
OpenWrap.ch.prototype.destroy=function(a){isDef(this.__types[this.channels[a]])&&(this.__types[this.channels[a]].destroy(a),delete this.channels[a],delete this.subscribers[a],delete this.jobs[a],delete this.vers[a]);return this};OpenWrap.ch.prototype.size=function(a){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";return this.__types[this.channels[a]].size(a)};
OpenWrap.ch.prototype.subscribe=function(a,b,c,e){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";isUnDef(e)&&(e=md5(b.toString()));if(isDef(this.subscribers[a][e]))return e;this.subscribers[a][e]=b;if(0<this.size(a)&&!c){var f=new Threads,g=new Threads,h=this;res=h.__types[h.channels[a]].forEach(a,function(c){var e=h.get(a,c);f.addThread(function(f){b(a,"set",c,e,h,f);return f})});g.addThread(function(){for(var b;0<h.jobs[a].length;)b=h.jobs[a].shift(),b.start(),b.stop();g.waitForThreads();
g.stop();return 1});h.jobs[a].push(f);g.startNoWait()}return e};OpenWrap.ch.prototype.unsubscribe=function(a,b){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";delete this.subscribers[a][b];return this};OpenWrap.ch.prototype.unsubscribeAll=function(a){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";this.subscribers[a]={};return this};
OpenWrap.ch.prototype.forEach=function(a,b,c){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";this.__types[this.channels[a]].forEach(a,b,c);return this};OpenWrap.ch.prototype.getAll=function(a,b){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";var c=[],e=this;isDef(this.__types[this.channels[a]].getAll)?sync(function(){c=c.concat(e.__types[e.channels[a]].getAll(a))},b):this.forEach(a,function(a,b){sync(function(){c.push(b)},c)},b);return c};
OpenWrap.ch.prototype.getKeys=function(a,b,c){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";return this.__types[this.channels[a]].getKeys(a,b,c)};OpenWrap.ch.prototype.getSortedKeys=function(a,b,c){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";return this.__types[this.channels[a]].getSortedKeys(a,b,c)};
OpenWrap.ch.prototype.set=function(a,b,c,e,f,g){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";if(isUnDef(e)&&(e=nowUTC(),this.getVersion(a)>e))return this;var h=b,l=c;"object"!=typeof b&&(h={key:b});"object"!=typeof c&&(l={key:b,value:c});var k=this,p;sync(function(){p=k.__types[k.channels[a]].set(a,h,l,e,g);k.vers[a]=nowUTC()},this.channels[a]);if(0<Object.keys(this.subscribers[a]).length){var m=new Threads,n=new Threads,q={},r;for(r in this.subscribers[a]){var u=m.addThread(function(h){q[h](a,
"set",b,c,k,e,f,g);return h});q[u]=k.subscribers[a][r]}n.addThread(function(){for(var b;0<k.jobs[a].length;)b=k.jobs[a].shift(),b.start(),b.stop();n.stop();return 1});k.jobs[a].push(m);n.startNoWait()}return p};OpenWrap.ch.prototype.push=function(a,b,c){return this.set(a,b,c)};
OpenWrap.ch.prototype.setAll=function(a,b,c,e,f,g){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";if(isUnDef(e)&&(e=nowUTC(),this.getVersion(a)>e))return this;var h=this,l;sync(function(){l=h.__types[h.channels[a]].setAll(a,b,c,e,g);h.vers[a]=nowUTC()},this.channels[a]);if(0<Object.keys(this.subscribers[a]).length){var k=new Threads,p=new Threads,m={},n;for(n in this.subscribers[a]){var q=k.addThread(function(k){m[k](a,"setall",b,c,h,e,f,g);return k});m[q]=h.subscribers[a][n]}p.addThread(function(){for(var b;0<
h.jobs[a].length;)b=h.jobs[a].shift(),b.start(),b.stop();p.stop();return 1});h.jobs[a].push(k);p.startNoWait()}return l};OpenWrap.ch.prototype.get=function(a,b,c){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";"object"!=typeof b&&(b={key:b});var e,f=this;sync(function(){e=f.__types[f.channels[a]].get(a,b,c)},this.channels[a]);return isDef(e)&&Object.keys(e)==["value"]?e.value:e};
OpenWrap.ch.prototype.pop=function(a){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";var b,c;0<this.size(a)&&(b=this.__types[this.channels[a]].pop(a),c=this.get(a,b),this.unset(a,b));return c};
OpenWrap.ch.prototype.getSet=function(a,b,c,e,f,g,h){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";var l,k=this;sync(function(){l=k.__types[k.channels[a]].getSet(a,b,c,e,f,h);k.vers[a]=nowUTC()},this.channels[a]);if(0<Object.keys(this.subscribers[a]).length){var p=new Threads,m=new Threads,n={},q;for(q in this.subscribers[a]){var r=p.addThread(function(b){n[b](a,"set",c,e,k,f,g,h);return b});n[r]=k.subscribers[a][q]}m.addThread(function(){for(var b;0<k.jobs[a].length;)b=k.jobs[a].shift(),
b.start(),b.stop();m.stop();return 1});k.jobs[a].push(p);m.startNoWait()}return l};OpenWrap.ch.prototype.shift=function(a){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";var b,c;0<this.size(a)&&(b=this.__types[this.channels[a]].shift(a),c=this.get(a,b),this.unset(a,b));return c};
OpenWrap.ch.prototype.unset=function(a,b,c,e,f){if(isUnDef(this.channels[a]))throw"Channel "+a+" doesn't exist.";if(isUnDef(c)&&(c=nowUTC(),this.getVersion(a)>c))return this;var g=b;"object"!=typeof b&&(g={key:b});var h=this;sync(function(){res=h.__types[h.channels[a]].unset(a,g,f);h.vers[a]=nowUTC()},this.channels[a]);if(0<Object.keys(this.subscribers[a]).length){var l=new Threads,k=new Threads,p={},m;for(m in this.subscribers[a]){var n=l.addThread(function(k){p[k](a,"unset",b,void 0,h,c,e,f);return k});
p[n]=h.subscribers[a][m]}k.addThread(function(){for(var b;0<h.jobs[a].length;)b=h.jobs[a].shift(),b.start(),b.stop();k.stop();return 1});h.jobs[a].push(l);k.startNoWait()}return this};OpenWrap.ch.prototype.utils={getMirrorSubscriber:function(a,b){return function(c,e,f,g){isUnDef(b)&&(b=function(){return!0});switch(e){case "set":b(f)&&$ch(a).set(f,g);break;case "setall":for(var h in f)b(f[h])&&$ch(a).set(f[h],g[h]);break;case "unset":b(f)&&$ch(a).unset(f)}}}};
OpenWrap.ch.prototype.comms={__counter:{},getSubscribeFunc:function(a,b,c,e,f){return function(g,h,l,k,p,m,n){function q(a,b,c,e,k){var f=nowUTC();$ch("__comm::"+g).set({timeStamp:f,operation:a,keys:c},{timeStamp:f,operation:a,keys:c,message:k,forcedTimeStamp:b,values:e})}isUnDef(n)&&(n=genUUID());if(n!=b){$ch("__comm::"+g).create();sync(function(){isUnDef(ow.ch.comms.__counter[g])&&(ow.ch.comms.__counter[g]=0)},ow.ch.comms.__counter[g]);try{var r=function(b){isDef(b.c)&&isDef(b.l)&&isDef(b.v)&&(b.c!=
ow.ch.comms.__counter[g]||b.l!=ow.ch.size(g))&&1>ow.ch.jobs[g].length&&0<ow.ch.size(g)&&(sync(function(){ow.ch.comms.__counter[g]=0},ow.ch.comms.__counter[g]),sync(function(){ow.obj.rest.set(a,{o:"r",k:Object.keys(ow.ch.getKeys(g)[0]),t:m},ow.ch.getAll(g),c,e,f)},a))},u=l,v=k;"object"!=typeof l&&(u={key:l});"object"!=typeof k&&(v={key:l,value:k});switch(h){case "setall":sync(function(){0!=ow.ch.comms.__counter[g]?ow.ch.comms.__counter[g]++:ow.ch.comms.__counter[g]=1},ow.ch.comms.__counter[g]);var t;
sync(function(){t=ow.obj.rest.jsonSet(a,{o:"a",k:l,t:m},k,c,e,f);r(t)},a);break;case "set":sync(function(){ow.ch.comms.__counter[g]++},ow.ch.comms.__counter[g]);sync(function(){t=ow.obj.rest.jsonSet(a,{o:"e",k:u,t:m},v,c,e,f);r(t)},a);break;case "unset":sync(function(){ow.ch.comms.__counter[g]++},ow.ch.comms.__counter[g]);sync(function(){t=ow.obj.rest.jsonRemove(a,{o:"e",k:u,t:m},c,e,f);r(t)},a);break;default:sync(function(){t=ow.obj.rest.jsonGet(a,{o:"e",k:u},c,e,f);r(t)},a)}}catch(w){q(h,m,u,k,
w)}}}}};
OpenWrap.ch.prototype.persistence={getSubscribeFunc:function(a){return function(b,c,e,f,g){try{io.writeFileBytes(a,compress(g.getAll(b)))}catch(h){b=nowUTC(),$ch("__store::"+ch).create(),$ch("__store::"+na).set({timeStamp:b,operation:c,keys:e},{timeStamp:b,operation:c,keys:e,message:h,values:f})}}},restore:function(a,b,c){if(isUnDef(ow.ch.channels[a]))throw"Channel "+a+" doesn't exist.";ow.loadObj();var e;try{e=uncompress(io.readFileBytes(b)),null!=e&&0<e.length&&(isUnDef(c)&&isDef(e[0].key)&&isDef(e[0].value)&&
(c=["key"]),ow.ch.setAll(a,c,e))}catch(f){return-1}return e.length},create:function(a,b,c,e){ow.ch.create(a,e);ow.ch.persistence.restore(a,b,c);ow.ch.subscribe(a,ow.ch.persistence.getSubscribeFunc(b));return this}};
OpenWrap.ch.prototype.server={__counter:{},expose:function(a,b,c,e,f){var g,h=genUUID();ow.loadServer();if(isUnDef(ow.ch.size(a)))throw"Channel "+a+" doesn't exist.";g=isObject(b)?b:ow.server.httpd.start(b);isUnDef(c)&&(c="/"+a);b={};isDef(e)?b[c]=function(b){return ow.server.httpd.authBasic(a,g,b,e,function(b,e){isUnDef(e.channelPermission)&&(e.channelPermission="rw");return ow.ch.server.routeProcessing(c,e,a,h)},f)}:b[c]=function(b){return ow.ch.server.routeProcessing(c,b,a,h)};var l=ow.server.httpd.getDefaultRoute(g);
isUnDef(l)&&(l=function(a){return g.reply("not found",ow.server.httpd.mimes.TXT,ow.server.httpd.codes.NOTFOUND)});ow.server.httpd.route(g,ow.server.httpd.mapWithExistingRoutes(g,b),l);return h},peer:function(a,b,c,e,f,g){b=ow.ch.server.expose(a,b,c,f,g);if(isArray(e))for(var h in e)ow.ch.subscribe(a,ow.ch.comms.getSubscribeFunc(e[h],b));else ow.ch.subscribe(a,ow.ch.comms.getSubscribeFunc(e,b))},routeProcessing:function(a,b,c,e){function f(a,f){var g;sync(function(){isUnDef(ow.ch.server.__counter[c])&&
(g=ow.ch.server.__counter[c]=0)},ow.ch.server.__counter[c]);if(isDef(a.o))switch(a.o){case "a":if(isArray(a.k)&&isArray(f))return sync(function(){g=++ow.ch.server.__counter[c]},ow.ch.server.__counter),f=$ch(c).setAll(a.k,f,a.t,e,b),{c:g,r:f};break;case "r":if(isArray(a.k)&&isArray(f)){var k=[],h;for(h in f)k.push(ow.loadObj().filterKeys(a.k,f[h]));$ch(c).forEach(function(f,g){0>k.indexOf(f)&&$ch(c).unset(f,a.t,e,b);return f});sync(function(){g=ow.ch.server.__counter[c]=0},ow.ch.server.__counter);
f=$ch(c).setAll(a.k,f,a.t,e,b);return{c:g,r:f}}break;case "e":return sync(function(){g=++ow.ch.server.__counter[c]},ow.ch.server.__counter),f=$ch(c).set(a.k,f,a.t,e,b),{c:g,r:f};case "es":return sync(function(){g=++ow.ch.server.__counter[c]},ow.ch.server.__counter),f=$ch(c).getSet(a.m,a.k,f,a.t,e,b),{c:g,r:f}}}function g(a){var f;sync(function(){isUnDef(ow.ch.server.__counter[c])&&(f=ow.ch.server.__counter[c]=0)},ow.ch.server.__counter);if(isDef(a.o)&&"e"==a.o)return sync(function(){f=++ow.ch.server.__counter[c]},
ow.ch.server.__counter),a=$ch(c).unset(a.k,a.t,e,b),{c:f,r:a}}function h(a){if(isDef(a.o))switch(a.o){case "a":return{r:$ch(c).getAll(b),c:ow.ch.server.__counter[c]};case "e":return{r:$ch(c).get(a.k,b),c:ow.ch.server.__counter[c]};case "k":return{r:$ch(c).getKeys(!1,b),c:ow.ch.server.__counter[c]};case "s":return{r:$ch(c).getSortedKeys(!1,b),c:ow.ch.server.__counter[c]}}}function l(a,b,c,e,f){var g=nowUTC();$ch("__comm::"+na).set({timeStamp:g,operation:a,keys:c},{timeStamp:g,operation:a,keys:c,message:f,
forcedTimeStamp:b,values:e})}ow.loadServer();$ch("__commServer::"+c).create();return ow.server.rest.reply(a,b,function(a,e){try{if(isDef(b.channelPermission)&&0>b.channelPermission.indexOf("w"))return{l:$ch(c).size(),v:$ch(c).getVersion(),c:-1,r:{}};var g=f(a,e);return isUnDef(g)?{}:{l:$ch(c).size(),v:$ch(c).getVersion(),c:g.c,r:g.r}}catch(n){return l("create",void 0,a,e,n),{}}},function(a){try{if(isDef(b.channelPermission)&&0>b.channelPermission.indexOf("r"))return{l:$ch(c).size(),v:$ch(c).getVersion(),
c:-1,r:{}};var e=h(a);return isUnDef(e)?{}:{l:$ch(c).size(),v:$ch(c).getVersion(),c:e.c,r:e.r}}catch(m){return l("get",void 0,a,d,m),{}}},function(a,e){try{if(isDef(b.channelPermission)&&0>b.channelPermission.indexOf("w"))return{l:$ch(c).size(),v:$ch(c).getVersion(),c:-1,r:{}};var g=f(a,e);return isUnDef(g)?{}:{l:$ch(c).size(),v:$ch(c).getVersion(),c:g.c,r:g.r}}catch(n){return l("set",void 0,a,e,n),{}}},function(a){try{if(isDef(b.channelPermission)&&0>b.channelPermission.indexOf("w"))return{l:$ch(c).size(),
v:$ch(c).getVersion(),c:-1,r:{}};var e=g(a);return isUnDef(e)?{}:{l:$ch(c).size(),v:$ch(c).getVersion(),c:e.c,r:e.r}}catch(m){return l("remove",void 0,a,d,m),{}}})}};
