const fs = require('node:fs');
const path = require('node:path');
const browserify = require('browserify');
const babel = require('@babel/core');
const terser = require('terser');

browserify(path.join(__dirname, 'entry.cjs'), { standalone: 'Ajv' }).bundle(async function(error, buffer) {
  if (error) throw error;
  const transformed = babel.transformSync(buffer.toString(), {
    babelrc: false,
    configFile: false,
    comments: false,
    compact: false,
    presets: [[require.resolve('@babel/preset-env'), { targets: { ie: '11' }, modules: false }]]
  });
  // Rhino 1.9.1 Reflect.get ignores the receiver for inherited getters.
  // Use Babel's descriptor-based fallback inside this bundle only.
  const reflectGet = '"undefined" != typeof Reflect && Reflect.get ? Reflect.get.bind() :';
  if (!transformed.code.includes(reflectGet)) throw new Error('Babel Reflect.get helper changed; review Rhino compatibility');
  const compatible = transformed.code.replace(reflectGet, 'false ? Reflect.get.bind() :');
  const output = await terser.minify('(function(){' + compatible + '\n}).call(this);', {
    ecma: 5,
    compress: { passes: 2 },
    mangle: true,
    format: { ascii_only: true, comments: false }
  });
  const root = path.resolve(__dirname, '../..');
  const header = '/* OpenAF Ajv 8.20.0 bundle. Generated by tools/ajv/build.cjs; see tools/ajv/LICENSES.txt. */\n';
  fs.writeFileSync(path.join(root, 'js/ajv.js'), header + output.code + '\n');
  const packages = ['ajv', 'ajv-formats', 'fast-deep-equal', 'fast-uri', 'json-schema-traverse', 'require-from-string', '@babel/helpers', 'browser-pack', 'umd'];
  const licenses = packages.map(function(name) {
    const dir = path.dirname(require.resolve(name + '/package.json'));
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const license = ['LICENSE', 'LICENSE.txt', 'license'].find(function(file) { return fs.existsSync(path.join(dir, file)); });
    return name + ' ' + pkg.version + '\n' + fs.readFileSync(path.join(dir, license), 'utf8');
  }).join('\n-----------------------\n\n');
  fs.writeFileSync(path.join(__dirname, 'LICENSES.txt'), licenses);
});
